from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

if __name__ == "__main__" and sys.version_info < (3, 11):
    print("Python 3.11 or newer is required", file=sys.stderr)
    raise SystemExit(2)

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from env.manifest import Manifest, ManifestError, Target, Var, effective_var, load_manifest, target_digest, vault_secret_map
from env.secret_refs import SecretNotFound, SecretUnavailable, resolve_secret


HEADER_LINE = "# GENERATED by make env-render from config/env/manifest.d - do not edit."
_DERIVE_REF = re.compile(r"\$\{([^}]+)\}")
_ASSIGNMENT = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")


def _target(manifest: Manifest, target_name: str) -> Target:
    target = manifest.targets.get(target_name)
    if target is None:
        raise ManifestError(f"targets.toml: {target_name}: unknown target")
    return target


def _target_vars(manifest: Manifest, target_name: str) -> tuple[Var, ...]:
    return tuple(effective_var(manifest, var, target_name)
                 for var in manifest.vars if target_name in var.targets)


def host_secret_required(var: Var, variables: tuple[Var, ...], env: str) -> bool:
    # The input is the live host env file: oci_vault must fail closed for an
    # absent, blank or quoted-empty host map, in both checks and writes.
    return var.required or (
        var.name == "RECOGNITION_VAULT_SECRET_MAP" and any(
            item.name == "RECOGNITION_SECRET_BACKEND" and item.values.get(env) == "oci_vault"
            for item in variables
        )
    )


def _assignment_has_value(line: str) -> bool:
    match = _ASSIGNMENT.match(line)
    if match is None:
        return False
    try:
        return any(shlex.split(match.group(2), comments=False))
    except ValueError:
        return False


def _format_value(value: str, name: str, *, references: bool = True) -> str:
    if "\r" in value or "\n" in value:
        raise ValueError(f"{name}: value cannot be represented portably")
    if re.fullmatch(r"[A-Za-z0-9_./:@,+=%?-]*", value):
        return value
    if references and re.fullmatch(r"(?:[A-Za-z0-9_./:@,+=%?-]|\$\{[A-Za-z_][A-Za-z0-9_]*\})+", value):
        return '"' + value + '"'
    if "'" not in value:
        return "'" + value + "'"
    if not any(char in value for char in '\"\\$`'):
        return '"' + value + '"'
    raise ValueError(f"{name}: value cannot be represented portably")


def _doc_lines(doc: str) -> list[str]:
    return ["# " + line.rstrip() if line.rstrip() else "#" for line in doc.split("\n")]


def _resolve_runtime_secret(
    var: Var, reference: str, resolve: Callable[[str, str], str]
) -> str | None:
    scheme, separator, _ = reference.partition(":")
    shown_scheme = scheme if separator else "missing"
    message = f"secret {var.name!r} unavailable for scheme {shown_scheme!r}"
    try:
        value = resolve(var.name, reference)
    except SecretNotFound:
        if not var.required:
            return None
        raise SecretUnavailable(message) from None
    except SecretUnavailable:
        raise SecretUnavailable(message) from None
    except Exception:
        raise SecretUnavailable(
            f"secret {var.name!r} unavailable for configured scheme"
        ) from None
    if not isinstance(value, str):
        raise SecretUnavailable(
            f"secret {var.name!r} unavailable for configured scheme"
        )
    return value


def render_target(
    manifest: Manifest,
    target_name: str,
    env: str | None,
    *,
    resolve: Callable[[str, str], str] = resolve_secret,
    host_lines: dict[str, list[str]] | None = None,
    missing_host_keys: set[str] | None = None,
) -> str:
    target = _target(manifest, target_name)
    if env is not None and env not in target.envs:
        raise ManifestError(f"{target_name}: unsupported env {env}")
    variables = _target_vars(manifest, target_name)
    values_by_name: dict[str, str | None] = {}
    literal_values: set[str] = set()

    def runtime_value(var: Var, visiting: frozenset[str] = frozenset()) -> str | None:
        if var.name in values_by_name:
            return values_by_name[var.name]
        if var.name in visiting:
            raise ManifestError(f"{var.source}: {var.name}: derive cycle")

        value: str | None
        if var.derive_vault_map:
            value = json.dumps(vault_secret_map(manifest, target_name, env), separators=(",", ":"), sort_keys=True)
        elif var.derive is not None:
            literal_values.add(var.name)
            missing_reference = False

            def replace_reference(match: re.Match[str]) -> str:
                nonlocal missing_reference
                reference_name = match.group(1)
                reference = next(
                    (item for item in variables if item.name == reference_name), None
                )
                if reference is None:
                    missing_reference = True
                    return ""
                reference_value = runtime_value(reference, visiting | {var.name})
                if reference_value is None:
                    missing_reference = True
                    return ""
                return reference_value

            value = _DERIVE_REF.sub(replace_reference, var.derive)
            if missing_reference:
                value = None
        elif var.cls == "secret":
            literal_values.add(var.name)
            reference = var.secret.get(env or "")
            if reference is None:
                value = None
            elif reference.startswith("vault:"):
                value = ""
            else:
                value = _resolve_runtime_secret(var, reference, resolve)
        else:
            value = var.values.get(env or "")

        if value is None and var.required:
            raise ManifestError(f"{var.source}: {var.name}: missing value for env {env}")
        values_by_name[var.name] = value
        return value

    lines = [
        HEADER_LINE,
        f"# target: {target_name} env: {env if env is not None else 'example'} digest: {target_digest(manifest, target_name)}",
        "",
    ]
    if target.doc is not None:
        lines.extend(_doc_lines(target.doc))
        lines.append("")
    for section_index, section in enumerate(target.sections):
        lines.append(f"# == {section} ==")
        for var in variables:
            if var.section != section:
                continue
            if var.doc:
                lines.extend(_doc_lines(var.doc))
            if env is not None and var.secret.get(env) == "host:":
                rendered_host_lines = (host_lines or {}).get(var.name, [])
                if host_secret_required(var, variables, env) and not any(
                    _assignment_has_value(line) for line in rendered_host_lines
                ):
                    if missing_host_keys is None:
                        raise ManifestError(f"{var.source}: {var.name}: host secret unavailable for env {env}")
                    missing_host_keys.add(var.name)
                lines.extend(rendered_host_lines)
                continue
            if env is None:
                value = var.example
            else:
                value = runtime_value(var)
            if value is None:
                continue
            formatted = value if env is not None and var.derive_vault_map else _format_value(value, var.name, references=var.name not in literal_values)
            assignment = f"{var.name}={formatted}"
            if env is None and not var.required:
                assignment = f"# {assignment}"
            lines.append(assignment)
        if section_index != len(target.sections) - 1:
            lines.append("")
    return "\n".join(lines) + "\n"


def _path_error(path: Path, detail: str) -> ValueError:
    return ValueError(f"{path}: {detail}")


def _inspect_path(path: Path) -> os.stat_result | None:
    absolute_path = Path(os.path.abspath(path))
    components = [*reversed(absolute_path.parents), absolute_path]
    leaf_stat: os.stat_result | None = None
    for index, component in enumerate(components):
        try:
            component_stat = os.lstat(component)
        except FileNotFoundError:
            continue
        except OSError:
            raise _path_error(path, "cannot inspect path") from None
        if stat.S_ISLNK(component_stat.st_mode):
            raise _path_error(path, "symlink path component is refused")
        if index < len(components) - 1 and not stat.S_ISDIR(component_stat.st_mode):
            raise _path_error(path, "parent path component is not a directory")
        if index == len(components) - 1:
            leaf_stat = component_stat
    if leaf_stat is not None and not stat.S_ISREG(leaf_stat.st_mode):
        if stat.S_ISDIR(leaf_stat.st_mode):
            raise _path_error(path, "directory path is refused")
        raise _path_error(path, "non-regular file path is refused")
    return leaf_stat


def _atomic_write(path: Path, data: bytes) -> None:
    descriptor, temporary_name = tempfile.mkstemp(prefix=f"{path.name}.envman-tmp-", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb") as stream:
            descriptor = -1
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
        temporary_path = Path()
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary_path != Path():
            try:
                temporary_path.unlink()
            except FileNotFoundError:
                pass


def _keys(text: str) -> set[str]:
    found: set[str] = set()
    for line in text.splitlines():
        match = _ASSIGNMENT.match(line)
        if match is not None:
            found.add(match.group(1))
    return found


def _validate_adoption(path: Path, text: str) -> None:
    for number, line in enumerate(text.splitlines(), 1):
        if line.strip() and not line.lstrip().startswith("#") and not _ASSIGNMENT.match(line):
            raise _path_error(path, f"unparseable line {number}")


@dataclass(frozen=True)
class _WritePlan:
    path: Path
    data: bytes
    backup: bytes | None


def _preflight_env_file(
    path: Path,
    text: str,
    *,
    adopt: bool = False,
    allow_unmanaged: frozenset[str] = frozenset(),
    runtime: bool = False,
) -> _WritePlan:
    path = Path(path)
    existing_stat = _inspect_path(path)
    parent = path.parent
    while not parent.exists():
        parent = parent.parent
    if not os.access(parent, os.W_OK | os.X_OK):
        raise _path_error(path, "cannot create parent directory")

    old_bytes: bytes | None = None
    adopting_unheaded = False
    if existing_stat is not None:
        try:
            old_bytes = path.read_bytes()
        except OSError:
            raise _path_error(path, "cannot read existing file") from None
        first_line = old_bytes.split(b"\n", 1)[0].removesuffix(b"\r")
        headed = first_line == HEADER_LINE.encode("utf-8")
        if not headed and not adopt:
            raise _path_error(path, "existing file is not generated")
        if not headed or runtime:
            try:
                old_text = old_bytes.decode("utf-8")
            except UnicodeDecodeError:
                raise _path_error(path, "existing file is not UTF-8") from None
            if not headed:
                _validate_adoption(path, old_text)
            new_text = text
            unmanaged = sorted(_keys(old_text) - _keys(new_text) - set(allow_unmanaged))
            if unmanaged:
                raise ValueError(f"{path}: unmanaged key {unmanaged[0]}")
            adopting_unheaded = not headed

    if adopting_unheaded and old_bytes is not None:
        backup_path = Path(f"{path}.pre-envman")
        backup_stat = _inspect_path(backup_path)
        if backup_stat is not None:
            try:
                backup_bytes = backup_path.read_bytes()
            except OSError:
                raise _path_error(backup_path, "cannot read existing file") from None
            if backup_bytes != old_bytes:
                raise ValueError(f"{backup_path}: backup exists")
    return _WritePlan(path, text.encode("utf-8"), old_bytes if adopting_unheaded else None)


def _apply_env_file(plan: _WritePlan) -> None:
    path = plan.path
    _inspect_path(path)
    if plan.backup is not None:
        _inspect_path(Path(f"{path}.pre-envman"))
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
    except OSError:
        raise _path_error(path, "cannot create parent directory") from None
    if plan.backup is not None:
        backup_path = Path(f"{path}.pre-envman")
        _inspect_path(backup_path)
        _atomic_write(backup_path, plan.backup)
    _inspect_path(path)
    _atomic_write(path, plan.data)


def write_env_file(
    path: Path,
    text: str,
    *,
    adopt: bool = False,
    allow_unmanaged: frozenset[str] = frozenset(),
    runtime: bool = False,
) -> None:
    _apply_env_file(_preflight_env_file(
        path, text, adopt=adopt, allow_unmanaged=allow_unmanaged, runtime=runtime,
    ))


def _read_text(path: Path) -> str | None:
    try:
        return path.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def check_example(manifest: Manifest, target_name: str, repo_root: Path) -> list[str]:
    target = _target(manifest, target_name)
    if target.example is None:
        return [f"{target_name}: no example path configured"]
    path = Path(repo_root) / target.example
    expected = render_target(manifest, target_name, None).encode("utf-8")
    try:
        actual = path.read_bytes()
    except OSError:
        return [f"{path}: example is missing or unreadable"]
    if actual != expected:
        return [f"{path}: example differs"]
    return []


def _runtime_assignments(text: str) -> dict[str, list[str]]:
    assignments: dict[str, list[str]] = {}
    for line in text.split("\n"):
        match = _ASSIGNMENT.match(line)
        if match is not None:
            assignments.setdefault(match.group(1), []).append(line)
    return assignments


def _without_assignments(text: str) -> tuple[str, ...]:
    return tuple(line for line in text.split("\n") if _ASSIGNMENT.match(line) is None)


def check_runtime(
    manifest: Manifest,
    target_name: str,
    env: str,
    path: Path,
    *,
    resolve: Callable[[str, str], str] = resolve_secret,
) -> list[str]:
    rendered = render_target(manifest, target_name, env, resolve=resolve)
    actual_text = _read_text(Path(path))
    if actual_text is None:
        return [f"{path}: runtime file is missing or unreadable"]

    expected_assignments = _runtime_assignments(rendered)
    actual_assignments = _runtime_assignments(actual_text)
    secret_names = {var.name for var in _target_vars(manifest, target_name) if var.cls == "secret"}
    messages = [f"{name}: duplicate assignment"
                for name, lines in actual_assignments.items() if len(lines) > 1]
    if stat.S_IMODE(Path(path).stat().st_mode) != 0o600:
        messages.append(f"{path}: mode is not 0600")
    for name, expected_value in expected_assignments.items():
        actual_value = actual_assignments.get(name)
        if actual_value == expected_value:
            continue
        if name in secret_names:
            messages.append(f"{name}: secret differs")
        elif actual_value is None:
            messages.append(f"{name}: missing")
        else:
            messages.append(f"{name}: differs")
    for name in sorted(actual_assignments.keys() - expected_assignments.keys()):
        messages.append(f"{name}: unmanaged key")

    if _without_assignments(actual_text) != _without_assignments(rendered):
        messages.append(f"{path}: non-assignment lines differ")
    return messages


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="render_env.py")
    commands = parser.add_subparsers(dest="command", required=True)
    materialize = commands.add_parser("materialize")
    materialize.add_argument("--root", type=Path, required=True)
    for name in ("env", "target", "into"):
        materialize.add_argument(f"--{name}", required=True)
    materialize.add_argument("--check", action="store_true")
    materialize.add_argument("--adopt", action="store_true")
    materialize.add_argument("--allow-unmanaged", default="")
    for command in ("render", "check"):
        command_parser = commands.add_parser(command)
        command_parser.add_argument("--root", type=Path, default=Path("config/env"))
        command_parser.add_argument("--repo-root", type=Path, default=Path("."))
        command_parser.add_argument("--env")
        command_parser.add_argument("--target")
        command_parser.add_argument("--all-examples", action="store_true")
        command_parser.add_argument("--adopt", action="store_true")
        command_parser.add_argument("--allow-unmanaged", default="")
    return parser


def _allow_unmanaged(value: str) -> frozenset[str]:
    return frozenset(name.strip() for name in value.split(",") if name.strip())


def main(argv: list[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    if args.command == "materialize":
        from env.materialize import run
        return run(args.root, env=args.env, target=args.target, into=args.into,
                   check=args.check, adopt=args.adopt,
                   allow_unmanaged=_allow_unmanaged(args.allow_unmanaged))
    if args.all_examples and (args.target is not None or args.env is not None):
        parser.error("--all-examples cannot be combined with --target or --env")
    if args.env is not None and args.target is None:
        parser.error("--env requires --target")
    if not args.all_examples and args.target is None:
        parser.error("provide --target or --all-examples")
    if args.command == "check" and (args.adopt or args.allow_unmanaged):
        parser.error("--adopt and --allow-unmanaged are only valid with render")
    if args.allow_unmanaged and not args.adopt and args.env is None:
        parser.error("--allow-unmanaged requires --adopt or --env")

    try:
        manifest = load_manifest(args.root)
        allow_unmanaged = _allow_unmanaged(args.allow_unmanaged)

        if args.all_examples:
            messages: list[str] = []
            plans: list[_WritePlan] = []
            for target_name in sorted(manifest.targets):
                target = manifest.targets[target_name]
                if target.example is None:
                    continue
                path = args.repo_root / target.example
                if args.command == "render":
                    plans.append(_preflight_env_file(
                        path,
                        render_target(manifest, target_name, None),
                        adopt=args.adopt,
                        allow_unmanaged=allow_unmanaged,
                    ))
                else:
                    messages.extend(check_example(manifest, target_name, args.repo_root))
            for plan in plans:
                _apply_env_file(plan)
            for message in messages:
                print(message)
            return 1 if messages else 0

        target = manifest.targets.get(args.target)
        if target is None:
            parser.error(f"unknown target {args.target}")
        if args.env is not None and args.env not in target.envs:
            parser.error(f"target {args.target} does not support env {args.env}")
        if args.env is None:
            if target.example is None:
                parser.error(f"target {args.target} has no example path configured")
            path = args.repo_root / target.example
            if args.command == "render":
                write_env_file(
                    path,
                    render_target(manifest, args.target, None),
                    adopt=args.adopt,
                    allow_unmanaged=allow_unmanaged,
                )
                return 0
            messages = check_example(manifest, args.target, args.repo_root)
        else:
            if target.path is None:
                parser.error(f"target {args.target} has no runtime path configured")
            path = args.repo_root / target.path
            if args.command == "render":
                write_env_file(
                    path,
                    render_target(manifest, args.target, args.env),
                    adopt=args.adopt,
                    allow_unmanaged=allow_unmanaged,
                    runtime=True,
                )
                return 0
            messages = check_runtime(manifest, args.target, args.env, path)

        for message in messages:
            print(message)
        return 1 if messages else 0
    except SecretUnavailable as error:
        print(str(error), file=sys.stderr)
        return 3
    except (ManifestError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 2
    except OSError:
        print("filesystem operation failed", file=sys.stderr)
        return 2

    except Exception as error:
        print(type(error).__name__, file=sys.stderr)
        return 4


if __name__ == "__main__":
    raise SystemExit(main())
