from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import stat
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

if __name__ == "__main__" and sys.version_info < (3, 11):
    print("Python 3.11 or newer is required", file=sys.stderr)
    raise SystemExit(2)

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from env.manifest import Manifest, ManifestError, Target, Var, effective_var, load_manifest, target_digest, vault_secret_map
from env.secret_refs import SecretNotFound, SecretUnavailable, resolve_secret


HEADER_LINE = "# GENERATED by make env-render from config/env/manifest.d - do not edit."
_DERIVE_REF = re.compile(r"\$\{([^}]+)\}")
_ASSIGNMENT = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$")


def _target(manifest: Manifest, target_name: str) -> Target:
    target = manifest.targets.get(target_name)
    if target is None:
        raise ManifestError(f"targets.toml: {target_name}: unknown target")
    return target


def _target_vars(manifest: Manifest, target_name: str) -> tuple[Var, ...]:
    return tuple(effective_var(manifest, var, target_name)
                 for var in manifest.vars if target_name in var.targets)


def host_secret_required(var: Var, variables: tuple[Var, ...], env: str) -> bool:
    # The input is the live host env file: oci_vault must fail closed for an
    # absent, blank or quoted-empty host map, in both checks and writes.
    required = var.required or (
        var.name == "RECOGNITION_VAULT_SECRET_MAP" and any(
            item.name == "RECOGNITION_SECRET_BACKEND" and item.values.get(env) == "oci_vault"
            for item in variables
        )
    )
    if not required:
        return False
    for name, accepted_values in (var.required_when or {}).items():
        condition = next((item for item in variables if item.name == name), None)
        if condition is None or condition.cls != "config":
            raise ManifestError(
                f"{var.source}: {var.name}: required_when cannot evaluate {name}"
            )
        value = condition.values.get(env, "")
        if accepted_values == ("*",):
            if not value:
                return False
        elif value not in accepted_values:
            return False
    return True


@dataclass
class _ShellCase:
    phase: str
    pattern_started: bool = False


@dataclass
class _HereDoc:
    delimiter: str
    strip_tabs: bool


@dataclass
class _ShellContext:
    kind: str
    parent_quote: str
    paren_depth: int = 0
    case_stack: list[_ShellCase] = field(default_factory=list)
    word: list[str] = field(default_factory=list)
    command_start: bool = True


@dataclass
class _ShellState:
    quote: str = ""
    escaped: bool = False
    in_word: bool = False
    contexts: list[_ShellContext] = field(default_factory=list)
    heredocs: list[_HereDoc] = field(default_factory=list)
    has_substitution: bool = False
    quarantined: bool = False


def _finish_shell_word(context: _ShellContext) -> None:
    if not context.word:
        return
    word = "".join(context.word)
    context.word.clear()

    current_case = context.case_stack[-1] if context.case_stack else None
    if current_case is not None and current_case.phase == "pattern":
        if word == "esac" and not current_case.pattern_started:
            context.case_stack.pop()
        else:
            current_case.pattern_started = True
        context.command_start = False
    elif word == "case" and context.command_start:
        context.case_stack.append(_ShellCase("header"))
        context.command_start = False
    elif current_case is not None and current_case.phase == "header" and word == "in":
        current_case.phase = "pattern"
        current_case.pattern_started = False
        context.command_start = False
    elif current_case is not None and current_case.phase == "body" and word == "esac" and context.command_start:
        context.case_stack.pop()
        context.command_start = False
    elif word in {"then", "else", "do", "elif", "!"}:
        context.command_start = True
    else:
        context.command_start = False


def _parse_heredoc(raw: str, index: int) -> tuple[_HereDoc, int] | None:
    """Accept only simple identifier delimiters, optionally singly/doubly quoted."""
    strip_tabs = raw.startswith("<<-", index)
    cursor = index + (3 if strip_tabs else 2)
    while cursor < len(raw) and raw[cursor] in " \t":
        cursor += 1
    if cursor >= len(raw):
        return None

    quote = raw[cursor] if raw[cursor] in "'\"" else ""
    if quote:
        end = raw.find(quote, cursor + 1)
        if end < 0:
            return None
        delimiter = raw[cursor + 1:end]
        cursor = end + 1
    else:
        match = re.match(r"[A-Za-z_][A-Za-z0-9_]*", raw[cursor:])
        if match is None:
            return None
        delimiter = match.group(0)
        cursor += len(delimiter)

    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", delimiter) is None:
        return None
    if cursor < len(raw) and raw[cursor] not in " \t\r;|&()<>":
        return None
    return _HereDoc(delimiter, strip_tabs), cursor


def _scan_shell_line(raw: str, state: _ShellState) -> str:
    # Track shell quote and substitution context so inner command text cannot
    # become an env assignment. Substitutions are never evaluated (SECD-05).
    if state.quarantined:
        return raw

    # Here-document data is not shell syntax. A recognized delimiter starts a
    # body on the next non-continued physical line; its terminator also stays
    # opaque, after which substitution scanning resumes.
    if state.heredocs and not state.escaped:
        heredoc = state.heredocs[0]
        candidate = raw.lstrip("\t") if heredoc.strip_tabs else raw
        if candidate == heredoc.delimiter:
            state.heredocs.pop(0)
        return raw

    comment_at: int | None = None
    index = 0
    while index < len(raw):
        char = raw[index]
        if state.escaped:
            state.escaped = False
            state.in_word = True
            if state.contexts and state.contexts[-1].kind == "paren":
                state.contexts[-1].word.extend(("\0", char))
            index += 1
            continue

        if state.quote == "'":
            if char == "'":
                state.quote = ""
            state.in_word = True
            index += 1
            continue

        if char == "\\":
            state.escaped = True
            state.in_word = True
            index += 1
            continue

        if state.quote == '"':
            if char == '"':
                state.quote = ""
            elif char == "$" and index + 1 < len(raw) and raw[index + 1] == "(":
                state.has_substitution = True
                if state.contexts and state.contexts[-1].kind == "paren":
                    state.contexts[-1].word.append("\0")
                state.contexts.append(_ShellContext("paren", state.quote, 1))
                state.quote = ""
                state.in_word = False
                index += 1
            elif char == "`":
                state.has_substitution = True
                if state.contexts and state.contexts[-1].kind == "paren":
                    state.contexts[-1].word.append("\0")
                state.contexts.append(_ShellContext("backtick", state.quote))
                state.quote = ""
                state.in_word = False
            else:
                state.in_word = True
            index += 1
            continue

        if char in "\"'":
            if state.contexts and state.contexts[-1].kind == "paren":
                state.contexts[-1].word.append("\0")
            state.quote = char
            state.in_word = True
            index += 1
            continue

        if char == "$" and index + 1 < len(raw) and raw[index + 1] == "(":
            state.has_substitution = True
            if state.contexts and state.contexts[-1].kind == "paren":
                state.contexts[-1].word.append("\0")
            state.contexts.append(_ShellContext("paren", state.quote, 1))
            state.quote = ""
            state.in_word = False
            index += 2
            continue

        if char in "<>" and index + 1 < len(raw) and raw[index + 1] == "(":
            state.has_substitution = True
            if state.contexts and state.contexts[-1].kind == "paren":
                state.contexts[-1].word.append("\0")
            state.contexts.append(_ShellContext("paren", state.quote, 1))
            state.quote = ""
            state.in_word = False
            index += 2
            continue

        context = state.contexts[-1] if state.contexts else None
        if context is not None and context.kind == "backtick" and char == "`":
            state.contexts.pop()
            state.quote = context.parent_quote
            state.in_word = True
            index += 1
            continue

        if char == "`":
            state.has_substitution = True
            if state.contexts and state.contexts[-1].kind == "paren":
                state.contexts[-1].word.append("\0")
            state.contexts.append(_ShellContext("backtick", state.quote))
            state.quote = ""
            state.in_word = False
            index += 1
            continue

        if char == "#" and not state.in_word:
            comment_at = index
            break

        context = state.contexts[-1] if state.contexts else None
        if (
            context is not None
            and context.kind in {"paren", "backtick"}
            and char == "<"
            and raw[index:index + 2] == "<<"
            and raw[index:index + 3] != "<<<"
        ):
            parsed = _parse_heredoc(raw, index)
            if parsed is None:
                # Expansions, concatenated delimiter words and other shell
                # forms are intentionally outside this bounded scanner.
                state.quarantined = True
                return raw
            heredoc, end = parsed
            if context.kind == "paren":
                _finish_shell_word(context)
            state.heredocs.append(heredoc)
            state.in_word = False
            index = end
            continue

        if context is not None and context.kind == "paren":
            current_case = context.case_stack[-1] if context.case_stack else None
            if char == "(" and current_case is not None and current_case.phase == "pattern":
                _finish_shell_word(context)
                current_case.pattern_started = True
                state.in_word = True
            elif char == "(":
                _finish_shell_word(context)
                context.paren_depth += 1
                context.command_start = True
                state.in_word = False
            elif char == ")":
                _finish_shell_word(context)
                current_case = context.case_stack[-1] if context.case_stack else None
                if current_case is not None and current_case.phase == "pattern":
                    if current_case.pattern_started:
                        current_case.phase = "body"
                        context.command_start = True
                    state.in_word = False
                elif current_case is not None and context.paren_depth <= 1:
                    # A case construct without a proven esac boundary keeps the
                    # substitution open, so malformed input cannot expose its tail.
                    state.in_word = False
                else:
                    context.paren_depth -= 1
                    if context.paren_depth == 0 and not context.case_stack:
                        state.contexts.pop()
                        state.quote = context.parent_quote
                        state.in_word = True
                    else:
                        state.in_word = False
            elif current_case is not None and current_case.phase == "pattern":
                if char in " \t\r;|&":
                    _finish_shell_word(context)
                    state.in_word = False
                else:
                    context.word.append(char)
                    state.in_word = True
            elif char in ";|&":
                _finish_shell_word(context)
                if char == ";" and raw[index:index + 3] == ";;&":
                    if current_case is not None and current_case.phase == "body":
                        current_case.phase = "pattern"
                        current_case.pattern_started = False
                    context.command_start = True
                    state.in_word = False
                    index += 3
                    continue
                if char == ";" and raw[index:index + 2] in {";;", ";&"}:
                    if current_case is not None and current_case.phase == "body":
                        current_case.phase = "pattern"
                        current_case.pattern_started = False
                    context.command_start = True
                    state.in_word = False
                    index += 2
                    continue
                context.command_start = True
                state.in_word = False
            elif char in " \t\r":
                _finish_shell_word(context)
                state.in_word = False
            else:
                context.word.append(char)
                state.in_word = True
        elif char in " \t\r;|&":
            state.in_word = False
        else:
            state.in_word = True
        index += 1

    if state.contexts and state.contexts[-1].kind == "paren":
        context = state.contexts[-1]
        _finish_shell_word(context)
        if not state.escaped:
            context.command_start = True
    if not state.escaped:
        if state.quote:
            state.in_word = True
        else:
            state.in_word = False
    return raw[:comment_at] if comment_at is not None else raw


def _shell_line(raw: str, quote: str = "") -> tuple[str, str, bool]:
    state = _ShellState(quote=quote, in_word=bool(quote))
    clean = _scan_shell_line(raw, state)
    return clean, state.quote, state.escaped


def _starts_value_word(raw: str) -> bool:
    return bool(
        raw
        and not raw[0].isspace()
        and not (raw.startswith("#") and (len(raw) == 1 or raw[1] in " \t\r\n"))
    )


def shell_words(raw: str) -> list[str] | None:
    """Unquote a single physical value line, preserving embedded hashes."""
    if "\n" in raw:
        return None
    state = _ShellState(in_word=_starts_value_word(raw))
    raw = _scan_shell_line(raw, state)
    if (
        state.has_substitution or state.quote or state.escaped or state.contexts
        or state.heredocs or state.quarantined
    ):
        return None
    try:
        return shlex.split(raw, posix=True)
    except ValueError:
        return None


def shell_assignments(text: str) -> dict[str, list[str]]:
    """Collect assignment occurrences without interpreting quoted inner lines."""
    assignments: dict[str, list[str]] = {}
    state = _ShellState()
    current: list[str] | None = None
    for line in text.split("\n"):
        if state.quote or state.contexts or state.escaped or state.heredocs or state.quarantined:
            raw = _scan_shell_line(line, state)
            if current is not None:
                current[-1] += "\n" + raw
        else:
            match = _ASSIGNMENT.match(line)
            current = None
            if match is not None:
                current = assignments.setdefault(match.group(1), [])
                value = match.group(2)
                state.in_word = _starts_value_word(value)
                raw = _scan_shell_line(value, state)
                current.append(raw)
            else:
                raw = _scan_shell_line(line, state)
    return assignments


def _assignment_has_value(line: str) -> bool:
    match = _ASSIGNMENT.match(line)
    if match is None:
        return False
    tokens = shell_words(match.group(2))
    return tokens is not None and len(tokens) == 1 and bool(tokens[0])


def _format_value(value: str, name: str, *, references: bool = True) -> str:
    if "\r" in value or "\n" in value:
        raise ValueError(f"{name}: value cannot be represented portably")
    if re.fullmatch(r"[A-Za-z0-9_./:@,+=%?-]*", value):
        return value
    if references and re.fullmatch(r"(?:[A-Za-z0-9_./:@,+=%?-]|\$\{[A-Za-z_][A-Za-z0-9_]*\})+", value):
        return '"' + value + '"'
    if "'" not in value:
        return "'" + value + "'"
    if not any(char in value for char in '\"\\$`'):
        return '"' + value + '"'
    raise ValueError(f"{name}: value cannot be represented portably")


def _doc_lines(doc: str) -> list[str]:
    return ["# " + line.rstrip() if line.rstrip() else "#" for line in doc.split("\n")]


def _resolve_runtime_secret(
    var: Var, reference: str, resolve: Callable[[str, str], str]
) -> str | None:
    scheme, separator, _ = reference.partition(":")
    shown_scheme = scheme if separator else "missing"
    message = f"secret {var.name!r} unavailable for scheme {shown_scheme!r}"
    try:
        value = resolve(var.name, reference)
    except SecretNotFound:
        if not var.required:
            return None
        raise SecretUnavailable(message) from None
    except SecretUnavailable:
        raise SecretUnavailable(message) from None
    except Exception:
        raise SecretUnavailable(
            f"secret {var.name!r} unavailable for configured scheme"
        ) from None
    if not isinstance(value, str):
        raise SecretUnavailable(
            f"secret {var.name!r} unavailable for configured scheme"
        )
    return value


def render_target(
    manifest: Manifest,
    target_name: str,
    env: str | None,
    *,
    resolve: Callable[[str, str], str] = resolve_secret,
    host_lines: dict[str, list[str]] | None = None,
    missing_host_keys: set[str] | None = None,
) -> str:
    target = _target(manifest, target_name)
    if env is not None and env not in target.envs:
        raise ManifestError(f"{target_name}: unsupported env {env}")
    variables = _target_vars(manifest, target_name)
    values_by_name: dict[str, str | None] = {}
    literal_values: set[str] = set()

    def runtime_value(var: Var, visiting: frozenset[str] = frozenset()) -> str | None:
        if var.name in values_by_name:
            return values_by_name[var.name]
        if var.name in visiting:
            raise ManifestError(f"{var.source}: {var.name}: derive cycle")

        value: str | None
        if var.derive_vault_map:
            value = json.dumps(vault_secret_map(manifest, target_name, env), separators=(",", ":"), sort_keys=True)
        elif var.derive is not None:
            literal_values.add(var.name)
            missing_reference = False

            def replace_reference(match: re.Match[str]) -> str:
                nonlocal missing_reference
                reference_name = match.group(1)
                reference = next(
                    (item for item in variables if item.name == reference_name), None
                )
                if reference is None:
                    missing_reference = True
                    return ""
                reference_value = runtime_value(reference, visiting | {var.name})
                if reference_value is None:
                    missing_reference = True
                    return ""
                return reference_value

            value = _DERIVE_REF.sub(replace_reference, var.derive)
            if missing_reference:
                value = None
        elif var.cls == "secret":
            literal_values.add(var.name)
            reference = var.secret.get(env or "")
            if reference is None:
                value = None
            elif reference.startswith("vault:"):
                value = ""
            else:
                value = _resolve_runtime_secret(var, reference, resolve)
        else:
            value = var.values.get(env or "")

        if value is None and var.required:
            raise ManifestError(f"{var.source}: {var.name}: missing value for env {env}")
        values_by_name[var.name] = value
        return value

    lines = [
        HEADER_LINE,
        f"# target: {target_name} env: {env if env is not None else 'example'} digest: {target_digest(manifest, target_name)}",
        "",
    ]
    if target.doc is not None:
        lines.extend(_doc_lines(target.doc))
        lines.append("")
    for section_index, section in enumerate(target.sections):
        lines.append(f"# == {section} ==")
        for var in variables:
            if var.section != section:
                continue
            if var.doc:
                lines.extend(_doc_lines(var.doc))
            if env is not None and var.secret.get(env) == "host:":
                rendered_host_lines = (host_lines or {}).get(var.name, [])
                if host_secret_required(var, variables, env) and not any(
                    _assignment_has_value(line) for line in rendered_host_lines
                ):
                    if missing_host_keys is None:
                        raise ManifestError(f"{var.source}: {var.name}: host secret unavailable for env {env}")
                    missing_host_keys.add(var.name)
                lines.extend(rendered_host_lines)
                continue
            if env is None:
                value = var.example
            else:
                value = runtime_value(var)
            if value is None:
                continue
            formatted = value if env is not None and var.derive_vault_map else _format_value(value, var.name, references=var.name not in literal_values)
            assignment = f"{var.name}={formatted}"
            if env is None and not var.required:
                assignment = f"# {assignment}"
            lines.append(assignment)
        if section_index != len(target.sections) - 1:
            lines.append("")
    return "\n".join(lines) + "\n"


def _path_error(path: Path, detail: str) -> ValueError:
    return ValueError(f"{path}: {detail}")


def _inspect_path(path: Path) -> os.stat_result | None:
    absolute_path = Path(os.path.abspath(path))
    components = [*reversed(absolute_path.parents), absolute_path]
    leaf_stat: os.stat_result | None = None
    for index, component in enumerate(components):
        try:
            component_stat = os.lstat(component)
        except FileNotFoundError:
            continue
        except OSError:
            raise _path_error(path, "cannot inspect path") from None
        if stat.S_ISLNK(component_stat.st_mode):
            raise _path_error(path, "symlink path component is refused")
        if index < len(components) - 1 and not stat.S_ISDIR(component_stat.st_mode):
            raise _path_error(path, "parent path component is not a directory")
        if index == len(components) - 1:
            leaf_stat = component_stat
    if leaf_stat is not None and not stat.S_ISREG(leaf_stat.st_mode):
        if stat.S_ISDIR(leaf_stat.st_mode):
            raise _path_error(path, "directory path is refused")
        raise _path_error(path, "non-regular file path is refused")
    return leaf_stat


def _atomic_write(path: Path, data: bytes) -> None:
    descriptor, temporary_name = tempfile.mkstemp(prefix=f"{path.name}.envman-tmp-", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb") as stream:
            descriptor = -1
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
        temporary_path = Path()
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary_path != Path():
            try:
                temporary_path.unlink()
            except FileNotFoundError:
                pass


def _keys(text: str) -> set[str]:
    found: set[str] = set()
    for line in text.splitlines():
        match = _ASSIGNMENT.match(line)
        if match is not None:
            found.add(match.group(1))
    return found


def _validate_adoption(path: Path, text: str) -> None:
    for number, line in enumerate(text.splitlines(), 1):
        if line.strip() and not line.lstrip().startswith("#") and not _ASSIGNMENT.match(line):
            raise _path_error(path, f"unparseable line {number}")


@dataclass(frozen=True)
class _WritePlan:
    path: Path
    data: bytes
    backup: bytes | None


def _preflight_env_file(
    path: Path,
    text: str,
    *,
    adopt: bool = False,
    allow_unmanaged: frozenset[str] = frozenset(),
    runtime: bool = False,
) -> _WritePlan:
    path = Path(path)
    existing_stat = _inspect_path(path)
    parent = path.parent
    while not parent.exists():
        parent = parent.parent
    if not os.access(parent, os.W_OK | os.X_OK):
        raise _path_error(path, "cannot create parent directory")

    old_bytes: bytes | None = None
    adopting_unheaded = False
    if existing_stat is not None:
        try:
            old_bytes = path.read_bytes()
        except OSError:
            raise _path_error(path, "cannot read existing file") from None
        first_line = old_bytes.split(b"\n", 1)[0].removesuffix(b"\r")
        headed = first_line == HEADER_LINE.encode("utf-8")
        if not headed and not adopt:
            raise _path_error(path, "existing file is not generated")
        if not headed or runtime:
            try:
                old_text = old_bytes.decode("utf-8")
            except UnicodeDecodeError:
                raise _path_error(path, "existing file is not UTF-8") from None
            if not headed:
                _validate_adoption(path, old_text)
            new_text = text
            unmanaged = sorted(_keys(old_text) - _keys(new_text) - set(allow_unmanaged))
            if unmanaged:
                raise ValueError(f"{path}: unmanaged key {unmanaged[0]}")
            adopting_unheaded = not headed

    if adopting_unheaded and old_bytes is not None:
        backup_path = Path(f"{path}.pre-envman")
        backup_stat = _inspect_path(backup_path)
        if backup_stat is not None:
            try:
                backup_bytes = backup_path.read_bytes()
            except OSError:
                raise _path_error(backup_path, "cannot read existing file") from None
            if backup_bytes != old_bytes:
                raise ValueError(f"{backup_path}: backup exists")
    return _WritePlan(path, text.encode("utf-8"), old_bytes if adopting_unheaded else None)


def _apply_env_file(plan: _WritePlan) -> None:
    path = plan.path
    _inspect_path(path)
    if plan.backup is not None:
        _inspect_path(Path(f"{path}.pre-envman"))
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
    except OSError:
        raise _path_error(path, "cannot create parent directory") from None
    if plan.backup is not None:
        backup_path = Path(f"{path}.pre-envman")
        _inspect_path(backup_path)
        _atomic_write(backup_path, plan.backup)
    _inspect_path(path)
    _atomic_write(path, plan.data)


def write_env_file(
    path: Path,
    text: str,
    *,
    adopt: bool = False,
    allow_unmanaged: frozenset[str] = frozenset(),
    runtime: bool = False,
) -> None:
    _apply_env_file(_preflight_env_file(
        path, text, adopt=adopt, allow_unmanaged=allow_unmanaged, runtime=runtime,
    ))


def _read_text(path: Path) -> str | None:
    try:
        return path.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def check_example(manifest: Manifest, target_name: str, repo_root: Path) -> list[str]:
    target = _target(manifest, target_name)
    if target.example is None:
        return [f"{target_name}: no example path configured"]
    path = Path(repo_root) / target.example
    expected = render_target(manifest, target_name, None).encode("utf-8")
    try:
        actual = path.read_bytes()
    except OSError:
        return [f"{path}: example is missing or unreadable"]
    if actual != expected:
        return [f"{path}: example differs"]
    return []


def _runtime_assignments(text: str) -> dict[str, list[str]]:
    assignments: dict[str, list[str]] = {}
    for line in text.split("\n"):
        match = _ASSIGNMENT.match(line)
        if match is not None:
            assignments.setdefault(match.group(1), []).append(line)
    return assignments


def _without_assignments(text: str) -> tuple[str, ...]:
    return tuple(line for line in text.split("\n") if _ASSIGNMENT.match(line) is None)


def check_runtime(
    manifest: Manifest,
    target_name: str,
    env: str,
    path: Path,
    *,
    resolve: Callable[[str, str], str] = resolve_secret,
) -> list[str]:
    rendered = render_target(manifest, target_name, env, resolve=resolve)
    actual_text = _read_text(Path(path))
    if actual_text is None:
        return [f"{path}: runtime file is missing or unreadable"]

    expected_assignments = _runtime_assignments(rendered)
    actual_assignments = _runtime_assignments(actual_text)
    secret_names = {var.name for var in _target_vars(manifest, target_name) if var.cls == "secret"}
    messages = [f"{name}: duplicate assignment"
                for name, lines in actual_assignments.items() if len(lines) > 1]
    if stat.S_IMODE(Path(path).stat().st_mode) != 0o600:
        messages.append(f"{path}: mode is not 0600")
    for name, expected_value in expected_assignments.items():
        actual_value = actual_assignments.get(name)
        if actual_value == expected_value:
            continue
        if name in secret_names:
            messages.append(f"{name}: secret differs")
        elif actual_value is None:
            messages.append(f"{name}: missing")
        else:
            messages.append(f"{name}: differs")
    for name in sorted(actual_assignments.keys() - expected_assignments.keys()):
        messages.append(f"{name}: unmanaged key")

    if _without_assignments(actual_text) != _without_assignments(rendered):
        messages.append(f"{path}: non-assignment lines differ")
    return messages


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="render_env.py")
    commands = parser.add_subparsers(dest="command", required=True)
    materialize = commands.add_parser("materialize")
    materialize.add_argument("--root", type=Path, required=True)
    for name in ("env", "target", "into"):
        materialize.add_argument(f"--{name}", required=True)
    materialize.add_argument("--check", action="store_true")
    materialize.add_argument("--adopt", action="store_true")
    materialize.add_argument("--allow-unmanaged", default="")
    for command in ("render", "check"):
        command_parser = commands.add_parser(command)
        command_parser.add_argument("--root", type=Path, default=Path("config/env"))
        command_parser.add_argument("--repo-root", type=Path, default=Path("."))
        command_parser.add_argument("--env")
        command_parser.add_argument("--target")
        command_parser.add_argument("--all-examples", action="store_true")
        command_parser.add_argument("--adopt", action="store_true")
        command_parser.add_argument("--allow-unmanaged", default="")
    return parser


def _allow_unmanaged(value: str) -> frozenset[str]:
    return frozenset(name.strip() for name in value.split(",") if name.strip())


def main(argv: list[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    if args.command == "materialize":
        from env.materialize import run
        return run(args.root, env=args.env, target=args.target, into=args.into,
                   check=args.check, adopt=args.adopt,
                   allow_unmanaged=_allow_unmanaged(args.allow_unmanaged))
    if args.all_examples and (args.target is not None or args.env is not None):
        parser.error("--all-examples cannot be combined with --target or --env")
    if args.env is not None and args.target is None:
        parser.error("--env requires --target")
    if not args.all_examples and args.target is None:
        parser.error("provide --target or --all-examples")
    if args.command == "check" and (args.adopt or args.allow_unmanaged):
        parser.error("--adopt and --allow-unmanaged are only valid with render")
    if args.allow_unmanaged and not args.adopt and args.env is None:
        parser.error("--allow-unmanaged requires --adopt or --env")

    try:
        manifest = load_manifest(args.root)
        allow_unmanaged = _allow_unmanaged(args.allow_unmanaged)

        if args.all_examples:
            messages: list[str] = []
            plans: list[_WritePlan] = []
            for target_name in sorted(manifest.targets):
                target = manifest.targets[target_name]
                if target.example is None:
                    continue
                path = args.repo_root / target.example
                if args.command == "render":
                    plans.append(_preflight_env_file(
                        path,
                        render_target(manifest, target_name, None),
                        adopt=args.adopt,
                        allow_unmanaged=allow_unmanaged,
                    ))
                else:
                    messages.extend(check_example(manifest, target_name, args.repo_root))
            for plan in plans:
                _apply_env_file(plan)
            for message in messages:
                print(message)
            return 1 if messages else 0

        target = manifest.targets.get(args.target)
        if target is None:
            parser.error(f"unknown target {args.target}")
        if args.env is not None and args.env not in target.envs:
            parser.error(f"target {args.target} does not support env {args.env}")
        if args.env is None:
            if target.example is None:
                parser.error(f"target {args.target} has no example path configured")
            path = args.repo_root / target.example
            if args.command == "render":
                write_env_file(
                    path,
                    render_target(manifest, args.target, None),
                    adopt=args.adopt,
                    allow_unmanaged=allow_unmanaged,
                )
                return 0
            messages = check_example(manifest, args.target, args.repo_root)
        else:
            if target.path is None:
                parser.error(f"target {args.target} has no runtime path configured")
            path = args.repo_root / target.path
            if args.command == "render":
                write_env_file(
                    path,
                    render_target(manifest, args.target, args.env),
                    adopt=args.adopt,
                    allow_unmanaged=allow_unmanaged,
                    runtime=True,
                )
                return 0
            messages = check_runtime(manifest, args.target, args.env, path)

        for message in messages:
            print(message)
        return 1 if messages else 0
    except SecretUnavailable as error:
        print(str(error), file=sys.stderr)
        return 3
    except (ManifestError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 2
    except OSError:
        print("filesystem operation failed", file=sys.stderr)
        return 2

    except Exception as error:
        print(type(error).__name__, file=sys.stderr)
        return 4


if __name__ == "__main__":
    raise SystemExit(main())
