from __future__ import annotations

import importlib
import json
import os
import stat
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest


CLI_PATH = Path(__file__).resolve().parents[1] / "render_env.py"
HEADER_LINE = "# GENERATED by make env-render from config/env/manifest.d - do not edit."


def _toml_table(values: dict[str, str]) -> str:
    return "{ " + ", ".join(f"{key} = {json.dumps(value)}" for key, value in values.items()) + " }"


def _modules():
    """Import implementation modules lazily so this RED suite still collects."""
    manifest = importlib.import_module("env.manifest")
    render = importlib.import_module("env.render_env")
    return manifest, render


def _targets(
    *,
    sections: tuple[str, ...] = ("Database",),
    envs: tuple[str, ...] = ("local",),
    audience: str = "backend",
    path: str | None = None,
    example: str | None = None,
    version: int = 1,
) -> str:
    lines = [
        f"version = {version}",
        "",
        "[targets.t]",
        f"audience = {json.dumps(audience)}",
        f"envs = {json.dumps(list(envs))}",
    ]
    if path is not None:
        lines.append(f"path = {json.dumps(path)}")
    if example is not None:
        lines.append(f"example = {json.dumps(example)}")
    lines.append(f"sections = {json.dumps(list(sections))}")
    return "\n".join(lines)


def _var(
    name: str,
    *,
    cls: str = "config",
    section: str = "Database",
    example: str = "example-value",
    values: dict[str, str] | None = None,
    secret: dict[str, str] | None = None,
    derive: str | None = None,
    doc: str | None = None,
    required: bool = True,
) -> str:
    lines = [
        "[[var]]",
        f"name = {json.dumps(name)}",
        f"class = {json.dumps(cls)}",
        'targets = ["t"]',
        f"section = {json.dumps(section)}",
    ]
    if doc is not None:
        lines.append(f"doc = {json.dumps(doc)}")
    lines.append(f"example = {json.dumps(example)}")
    if not required:
        lines.append("required = false")
    if values is not None:
        lines.append(f"values = {_toml_table(values)}")
    if secret is not None:
        lines.append(f"secret = {_toml_table(secret)}")
    if derive is not None:
        lines.append(f"derive = {json.dumps(derive)}")
    return "\n".join(lines)


def _cli_env(**updates: str | None) -> dict[str, str]:
    child_env = os.environ.copy()
    for key, value in updates.items():
        if value is None:
            child_env.pop(key, None)
        else:
            child_env[key] = value
    return child_env


def _run_cli(root: Path, repo_root: Path, *args: str, env: dict[str, str] | None = None):
    return subprocess.run(
        [
            sys.executable,
            str(CLI_PATH),
            *args,
            "--root",
            str(root),
            "--repo-root",
            str(repo_root),
        ],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )


def test_example_render_has_exact_bytes_and_layout(write_manifest, tmp_path: Path):
    manifest_module, render_module = _modules()
    fragment = "\n\n".join(
        (
            _var(
                "DATABASE_URL",
                section="Database",
                example="https://db.example.test/name with space",
                values={"local": "https://db.example.test/name with space"},
                doc="doc line",
            ),
            _var(
                "OPTIONAL_FEATURE",
                section="Security",
                example="placeholder",
                values={"local": "enabled"},
                required=False,
            ),
        )
    )
    root = write_manifest(
        _targets(sections=("Database", "Security")),
        **{"10-main": f"version = 1\n\n{fragment}"},
    )
    manifest = manifest_module.load_manifest(root)
    rendered = render_module.render_target(manifest, "t", None)
    digest = manifest_module.target_digest(manifest, "t")

    assert render_module.HEADER_LINE == HEADER_LINE
    assert rendered == (
        f"{HEADER_LINE}\n"
        f"# target: t env: example digest: {digest}\n"
        "\n"
        "# == Database ==\n"
        "# doc line\n"
        "DATABASE_URL='https://db.example.test/name with space'\n"
        "\n"
        "# == Security ==\n"
        "# OPTIONAL_FEATURE=placeholder\n"
    )


@pytest.mark.parametrize(
    ("value", "expected"),
    (
        ("has space", "'has space'"),
        ("has#hash", "'has#hash'"),
        ('with"quote', "'with\"quote'"),
        ("it's quoted", '"it\'s quoted"'),
        ("cash$value", "'cash$value'"),
        ("slash\\value", "'slash\\value'"),
        ("https://example.test/path?x=1", "https://example.test/path?x=1"),
        ('{"k":"v","x":"y"}', "'{\"k\":\"v\",\"x\":\"y\"}'"),
        ("", ""),
        ("tilde~home", "'tilde~home'"),
        ("define('A', true);", '"define(\'A\', true);"'),
    ),
    ids=(
        "space",
        "hash",
        "double-quote",
        "single-quote",
        "dollar",
        "backslash",
        "plain-url",
        "json",
        "empty",
        "tilde",
        "php-single-quotes",
    ),
)
def test_values_use_contract_quoting(write_manifest, value: str, expected: str):
    _, render_module = _modules()
    fragment = f"version = 1\n\n{_var('VALUE', example=value, values={'local': value})}"
    root = write_manifest(_targets(), **{"10-values": fragment})
    rendered = render_module.render_target(
        importlib.import_module("env.manifest").load_manifest(root), "t", None
    )

    assert f"VALUE={expected}" in rendered.splitlines()


@pytest.mark.parametrize(
    "value",
    (
        'it\'s "both"',
        "it's $cash",
        "it's back\\slash",
        "it's `tick`",
        "line\nbreak",
        "cr\rreturn",
    ),
    ids=("both-quotes", "dollar", "backslash", "backtick", "newline", "carriage-return"),
)
def test_unrepresentable_values_are_refused(write_manifest, value: str):
    _, render_module = _modules()
    runtime = "\n" in value or "\r" in value
    example = "plain-example" if runtime else value
    fragment = f"version = 1\n\n{_var('VALUE', example=example, values={'local': value})}"
    parsed = tomllib.loads(fragment)
    assert parsed["var"][0]["example"] == example
    assert parsed["var"][0]["values"]["local"] == value
    root = write_manifest(_targets(), **{"10-values": fragment})

    manifest = importlib.import_module("env.manifest").load_manifest(root)
    with pytest.raises(ValueError) as exc_info:
        render_module.render_target(manifest, "t", "local" if runtime else None)

    assert type(exc_info.value) is ValueError
    assert "VALUE" in str(exc_info.value)
    assert value not in str(exc_info.value)


def test_example_mode_uses_secret_example_without_resolving(write_manifest):
    _, render_module = _modules()
    root = write_manifest(
        _targets(),
        **{
            "10-secret": (
                "version = 1\n\n"
                + _var(
                    "SERVICE_PASSWORD",
                    cls="secret",
                    example="example-password",
                    secret={"local": "keychain:acx-local/SERVICE_PASSWORD"},
                )
            )
        },
    )

    def unexpected_resolve(name: str, ref: str) -> str:
        raise AssertionError(f"resolver called for {name} using {ref}")

    rendered = render_module.render_target(
        importlib.import_module("env.manifest").load_manifest(root),
        "t",
        None,
        resolve=unexpected_resolve,
    )

    assert "SERVICE_PASSWORD=example-password" in rendered.splitlines()


def test_runtime_uses_values_and_resolves_secret_ref(write_manifest):
    _, render_module = _modules()
    fragment = "\n\n".join(
        (
            _var("PUBLIC_URL", cls="public", values={"local": "https://public.example.test"}),
            _var("APP_MODE", values={"local": "development"}),
            _var(
                "SERVICE_PASSWORD",
                cls="secret",
                secret={"local": "env:ACX_SERVICE_PASSWORD"},
            ),
        )
    )
    root = write_manifest(_targets(), **{"10-runtime": f"version = 1\n\n{fragment}"})
    manifest = importlib.import_module("env.manifest").load_manifest(root)
    calls: list[tuple[str, str]] = []

    def resolve(name: str, ref: str) -> str:
        calls.append((name, ref))
        return "runtime-secret-value"

    rendered = render_module.render_target(manifest, "t", "local", resolve=resolve)

    assert rendered.splitlines()[1].startswith("# target: t env: local digest: ")
    assert "PUBLIC_URL=https://public.example.test" in rendered.splitlines()
    assert "APP_MODE=development" in rendered.splitlines()
    assert "SERVICE_PASSWORD=runtime-secret-value" in rendered.splitlines()
    assert calls == [("SERVICE_PASSWORD", "env:ACX_SERVICE_PASSWORD")]


def test_runtime_omits_missing_optional_value(write_manifest):
    _, render_module = _modules()
    root = write_manifest(
        _targets(envs=("local", "ci")),
        **{
            "10-optional": (
                "version = 1\n\n"
                + _var("OPTIONAL_LOCAL", values={"ci": "ci-value"}, required=False)
            )
        },
    )
    rendered = render_module.render_target(
        importlib.import_module("env.manifest").load_manifest(root), "t", "local"
    )

    assert "OPTIONAL_LOCAL=" not in rendered


def test_runtime_missing_required_value_names_var_in_manifest_error(write_manifest):
    manifest_module, render_module = _modules()
    root = write_manifest(
        _targets(envs=("local", "ci")),
        **{
            "10-required": (
                "version = 1\n\n"
                + _var("REQUIRED_LOCAL", values={"ci": "ci-value"})
            )
        },
    )
    manifest = manifest_module.load_manifest(root)

    with pytest.raises(manifest_module.ManifestError) as exc_info:
        render_module.render_target(manifest, "t", "local")
    assert type(exc_info.value) is manifest_module.ManifestError
    assert "REQUIRED_LOCAL" in str(exc_info.value)


def test_derived_dsn_tracks_one_password_rotation(write_manifest):
    _, render_module = _modules()
    fragment = "\n\n".join(
        (
            _var("PGUSER", values={"local": "acx"}),
            _var("PGPASSWORD", cls="secret", secret={"local": "env:ACX_PGPASSWORD"}),
            _var("PGHOST", values={"local": "localhost:5432"}),
            _var(
                "POSTGRES_DSN",
                cls="secret",
                derive="postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}/service",
            ),
        )
    )
    root = write_manifest(_targets(), **{"10-database": f"version = 1\n\n{fragment}"})
    manifest = importlib.import_module("env.manifest").load_manifest(root)

    def render_with(password: str) -> str:
        return render_module.render_target(
            manifest,
            "t",
            "local",
            resolve=lambda name, ref: password,
        )

    before = render_with("pw1").splitlines()
    after = render_with("pw2").splitlines()
    changed_names = ("PGPASSWORD=", "POSTGRES_DSN=")
    assert "PGPASSWORD=pw1" in before
    assert "POSTGRES_DSN=postgresql://acx:pw1@localhost:5432/service" in before
    assert [line for line in before if not line.startswith(changed_names)] == [
        line for line in after if not line.startswith(changed_names)
    ]
    assert "PGPASSWORD=pw2" in after
    assert "POSTGRES_DSN=postgresql://acx:pw2@localhost:5432/service" in after


def test_render_is_deterministic_when_fragment_files_are_renamed(write_manifest):
    manifest_module, render_module = _modules()
    fragments = {
        "10-first": f"version = 1\n\n{_var('FIRST', values={'local': 'one'})}",
        "20-second": f"version = 1\n\n{_var('SECOND', values={'local': 'two'})}",
    }
    root = write_manifest(_targets(), **fragments)
    first_manifest = manifest_module.load_manifest(root)
    first_render = render_module.render_target(first_manifest, "t", None)
    first_digest = manifest_module.target_digest(first_manifest, "t")
    manifest_dir = root / "manifest.d"
    (manifest_dir / "10-first.toml").rename(manifest_dir / "15-renamed-first.toml")
    (manifest_dir / "20-second.toml").rename(manifest_dir / "25-renamed-second.toml")
    second_manifest = manifest_module.load_manifest(root)
    second_render = render_module.render_target(second_manifest, "t", None)

    assert second_render == first_render
    assert manifest_module.target_digest(second_manifest, "t") == first_digest
    assert second_render.splitlines()[1] == first_render.splitlines()[1]


def test_write_new_file_uses_mode_600_and_leaves_no_temp_file(write_manifest, tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "runtime.env"

    render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nKEY=value\n")

    assert stat.S_IMODE(path.stat().st_mode) == 0o600
    assert [entry.name for entry in tmp_path.iterdir()] == ["runtime.env"]


def test_overwriting_generated_file_keeps_mode_600(tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "runtime.env"
    render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nKEY=first\n")

    render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nKEY=second\n")

    assert stat.S_IMODE(path.stat().st_mode) == 0o600
    assert path.read_text(encoding="utf-8").endswith("KEY=second\n")


def test_failed_write_preserves_existing_file_and_cleans_up_temp_file(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    _, render_module = _modules()
    path = tmp_path / "runtime.env"
    render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nKEY=first\n")

    def boom(*args, **kwargs):
        raise OSError("replace failed")

    monkeypatch.setattr(render_module.os, "replace", boom)

    with pytest.raises(OSError, match="replace failed"):
        render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nKEY=second\n")

    assert path.read_text(encoding="utf-8").endswith("KEY=first\n")
    assert stat.S_IMODE(path.stat().st_mode) == 0o600
    assert [entry.name for entry in tmp_path.iterdir()] == ["runtime.env"]


@pytest.mark.parametrize("kind", ("live symlink", "broken symlink", "directory"))
def test_writer_refuses_symlinks_and_directories_with_path(kind: str, tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "blocked.env"
    if kind == "live symlink":
        destination = tmp_path / "destination.env"
        destination.write_text("untouched\n", encoding="utf-8")
        path.symlink_to(destination)
    elif kind == "broken symlink":
        path.symlink_to(tmp_path / "missing-destination.env")
    else:
        path.mkdir()

    with pytest.raises(ValueError) as exc_info:
        render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nKEY=value\n")

    assert type(exc_info.value) is ValueError
    assert str(path) in str(exc_info.value)
    if kind == "live symlink":
        assert destination.read_text(encoding="utf-8") == "untouched\n"
        assert path.is_symlink()


def test_writer_refuses_unheaded_file_without_adopt(tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "manual.env"
    path.write_text("APP_MODE=old\n", encoding="utf-8")

    with pytest.raises(ValueError) as exc_info:
        render_module.write_env_file(path, f"{render_module.HEADER_LINE}\nAPP_MODE=new\n")

    assert type(exc_info.value) is ValueError
    assert str(path) in str(exc_info.value)


def test_adopt_backs_up_old_bytes_with_mode_600(tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "adopt.env"
    old_bytes = b"APP_MODE=old-placeholder\n"
    path.write_bytes(old_bytes)

    render_module.write_env_file(
        path,
        f"{render_module.HEADER_LINE}\nAPP_MODE=new-placeholder\n",
        adopt=True,
    )

    backup = tmp_path / "adopt.env.pre-envman"
    assert backup.read_bytes() == old_bytes
    assert stat.S_IMODE(backup.stat().st_mode) == 0o600


def test_adopt_refuses_unmanaged_key_without_revealing_its_value(tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "adopt.env"
    path.write_text("LEGACY_X=legacy-placeholder\n", encoding="utf-8")

    with pytest.raises(ValueError) as exc_info:
        render_module.write_env_file(
            path,
            f"{render_module.HEADER_LINE}\nCURRENT=present\n",
            adopt=True,
        )

    assert type(exc_info.value) is ValueError
    message = str(exc_info.value)
    assert "LEGACY_X" in message
    assert "legacy-placeholder" not in message


def test_adopt_allows_explicit_unmanaged_key(tmp_path: Path):
    _, render_module = _modules()
    path = tmp_path / "adopt.env"
    path.write_text("LEGACY_X=legacy-placeholder\n", encoding="utf-8")
    new_text = f"{render_module.HEADER_LINE}\nCURRENT=present\n"

    render_module.write_env_file(
        path,
        new_text,
        adopt=True,
        allow_unmanaged=frozenset({"LEGACY_X"}),
    )

    assert path.read_text(encoding="utf-8") == new_text


def test_check_example_returns_empty_for_matching_file(write_manifest, tmp_path: Path):
    _, render_module = _modules()
    root = write_manifest(
        _targets(example="app/.env.example"),
        **{
            "10-check": f"version = 1\n\n"
            f"{_var('APP_MODE', example='dev', values={'local': 'dev'})}"
        },
    )
    repo_root = tmp_path / "repo"
    example_path = repo_root / "app/.env.example"
    example_path.parent.mkdir(parents=True)
    manifest = importlib.import_module("env.manifest").load_manifest(root)
    example_path.write_text(render_module.render_target(manifest, "t", None), encoding="utf-8")

    assert render_module.check_example(manifest, "t", repo_root) == []


def test_check_example_reports_drift_with_target_or_path(write_manifest, tmp_path: Path):
    _, render_module = _modules()
    root = write_manifest(
        _targets(example="app/.env.example"),
        **{
            "10-check": f"version = 1\n\n"
            f"{_var('APP_MODE', example='dev', values={'local': 'dev'})}"
        },
    )
    repo_root = tmp_path / "repo"
    example_path = repo_root / "app/.env.example"
    example_path.parent.mkdir(parents=True)
    manifest = importlib.import_module("env.manifest").load_manifest(root)
    rendered = render_module.render_target(manifest, "t", None)
    example_path.write_text(rendered, encoding="utf-8")
    drifted_bytes = example_path.read_bytes().replace(b"APP_MODE=dev", b"APP_MODE=dew")
    assert drifted_bytes != rendered.encode("utf-8")
    example_path.write_bytes(drifted_bytes)

    messages = render_module.check_example(manifest, "t", repo_root)

    assert messages
    assert any(str(example_path) in message or "app/.env.example" in message for message in messages)


def test_check_runtime_hides_both_secret_values_on_mismatch(write_manifest, tmp_path: Path):
    _, render_module = _modules()
    root = write_manifest(
        _targets(),
        **{
            "10-check": (
                "version = 1\n\n"
                + _var("SERVICE_PASSWORD", cls="secret", secret={"local": "env:ACX_SECRET"})
            )
        },
    )
    manifest = importlib.import_module("env.manifest").load_manifest(root)
    path = tmp_path / "runtime.env"
    old_secret = "s3cr3t-old"
    new_secret = "s3cr3t-new"
    old_text = render_module.render_target(
        manifest, "t", "local", resolve=lambda name, ref: old_secret
    )
    path.write_text(old_text, encoding="utf-8")
    path.chmod(0o600)

    messages = render_module.check_runtime(
        manifest,
        "t",
        "local",
        path,
        resolve=lambda name, ref: new_secret,
    )

    assert messages == ["SERVICE_PASSWORD: secret differs"]
    assert all(old_secret not in message and new_secret not in message for message in messages)


def test_cli_renders_and_checks_all_examples_then_detects_drift(write_manifest, tmp_path: Path):
    _modules()
    targets = """version = 1

[targets.t]
audience = "backend"
envs = ["local"]
example = "app/.env.example"
sections = ["Application"]

[targets.u]
audience = "backend"
envs = ["local"]
example = "other/.env.example"
sections = ["Other"]
"""
    fragment = """version = 1

[[var]]
name = "APP_MODE"
class = "config"
targets = ["t"]
section = "Application"
example = "dev"
values = { local = "dev" }

[[var]]
name = "OTHER_MODE"
class = "config"
targets = ["u"]
section = "Other"
example = "ready"
values = { local = "ready" }
"""
    root = write_manifest(
        targets,
        **{"10-cli": fragment},
    )
    repo_root = tmp_path / "repo"
    example_paths = (
        repo_root / "app/.env.example",
        repo_root / "other/.env.example",
    )
    for example_path in example_paths:
        example_path.parent.mkdir(parents=True)
    child_env = _cli_env(ACX_T_SECRET=None)

    rendered = _run_cli(root, repo_root, "render", "--all-examples", env=child_env)
    assert rendered.returncode == 0, rendered.stderr
    assert all(example_path.is_file() for example_path in example_paths)

    checked = _run_cli(root, repo_root, "check", "--all-examples", env=child_env)
    assert checked.returncode == 0, checked.stderr
    later_example_path = example_paths[1]
    original_bytes = later_example_path.read_bytes()
    drifted_bytes = original_bytes.replace(b"OTHER_MODE=ready", b"OTHER_MODE=readx")
    assert drifted_bytes != original_bytes
    later_example_path.write_bytes(drifted_bytes)
    drifted = _run_cli(root, repo_root, "check", "--all-examples", env=child_env)
    assert drifted.returncode == 1


def test_cli_reports_malformed_manifest_with_exit_code_2(write_manifest, tmp_path: Path):
    _modules()
    root = write_manifest(_targets(version=2))
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    result = _run_cli(root, repo_root, "check", "--all-examples", env=_cli_env())

    assert result.returncode == 2


def test_cli_runtime_secret_fails_closed_then_writes_without_echo(write_manifest, tmp_path: Path):
    _modules()
    root = write_manifest(
        _targets(path="app/.env"),
        **{
            "10-cli-secret": (
                "version = 1\n\n"
                + _var(
                    "ACX_T_SECRET",
                    cls="secret",
                    secret={"local": "env:ACX_T_SECRET"},
                )
            )
        },
    )
    repo_root = tmp_path / "repo"
    (repo_root / "app").mkdir(parents=True)
    missing = _run_cli(
        root,
        repo_root,
        "render",
        "--env",
        "local",
        "--target",
        "t",
        env=_cli_env(ACX_T_SECRET=None),
    )
    assert missing.returncode == 3

    fake_secret = "cli-secret-value"
    rendered = _run_cli(
        root,
        repo_root,
        "render",
        "--env",
        "local",
        "--target",
        "t",
        env=_cli_env(ACX_T_SECRET=fake_secret),
    )
    assert rendered.returncode == 0, rendered.stderr
    output = rendered.stdout + rendered.stderr + missing.stdout + missing.stderr
    assert fake_secret not in output
    runtime_path = repo_root / "app/.env"
    assert f"ACX_T_SECRET={fake_secret}" in runtime_path.read_text(encoding="utf-8")
    assert stat.S_IMODE(runtime_path.stat().st_mode) == 0o600


@pytest.mark.parametrize('env', [None, 'local'])
def test_v2_target_preamble_exact_layout(write_manifest, env):
    module, render = _modules()
    root = write_manifest(_targets() + '\ndoc = "instructions\\n"',
        **{'10-main': 'version=1\n' + _var('VALUE', example='base', values={'local': 'base'})})
    manifest = module.load_manifest(root)
    assert render.render_target(manifest, 't', env) == (
        f'{HEADER_LINE}\n# target: t env: {env or "example"} digest: '
        f'{module.target_digest(manifest, "t")}\n\n'
        '# instructions\n#\n\n# == Database ==\nVALUE=base\n')


def test_v2_absent_target_doc_preserves_layout(write_manifest):
    module, render = _modules()
    root = write_manifest(_targets(), **{'10-main': 'version=1\n' +
        _var('VALUE', values={}, doc='doc line')})
    manifest = module.load_manifest(root)
    assert manifest.targets['t'].doc is None
    assert render.render_target(manifest, 't', None) == (
        f'{HEADER_LINE}\n# target: t env: example digest: '
        f'{module.target_digest(manifest, "t")}\n\n'
        '# == Database ==\n# doc line\nVALUE=example-value\n')


@pytest.mark.parametrize('doc_owner', ['target', 'var', 'override'])
def test_v2_doc_lines_preserve_leading_and_strip_trailing_spaces(write_manifest, doc_owner):
    module, render = _modules()
    doc = ' install -m 0600 x y  \n\nnext\t'
    targets = _targets()
    fragment = 'version=1\n' + _var('VALUE', values={}, doc=doc if doc_owner == 'var' else None)
    if doc_owner == 'target':
        targets += '\ndoc = ' + json.dumps(doc)
    if doc_owner == 'override':
        fragment += '\n[[override]]\nname="VALUE"\ntarget="t"\ndoc=' + json.dumps(doc)
    manifest = module.load_manifest(write_manifest(targets, **{'10-main': fragment}))
    assert '#  install -m 0600 x y\n#\n# next\n' in render.render_target(manifest, 't', None)


def _v2_render_manifest(write_manifest, override):
    module, _ = _modules()
    targets = '''version=1
[targets.t]
audience="backend"
envs=["local"]
sections=["Database", "Other"]
example="t.example"
[targets.u]
audience="backend"
envs=["local"]
sections=["Database", "Other"]
example="u.example"
'''
    fragment = 'version=1\n' + '\n'.join(
        _var(name, example='base', values={'local': 'runtime'}).replace(
            'targets = ["t"]', 'targets = ["t", "u"]')
        for name in ('FIRST', 'VALUE', 'LAST'))
    fragment += '\n[[override]]\nname="VALUE"\ntarget="t"\n' + override
    return module.load_manifest(write_manifest(targets, **{'10-main': fragment}))


def test_v2_override_example_is_target_specific(write_manifest):
    _, render = _modules()
    manifest = _v2_render_manifest(write_manifest, 'example="custom"')
    assert 'VALUE=custom' in render.render_target(manifest, 't', None).splitlines()
    assert 'VALUE=base' in render.render_target(manifest, 'u', None).splitlines()


def test_v2_override_required_is_target_specific(write_manifest):
    _, render = _modules()
    manifest = _v2_render_manifest(write_manifest, 'required=false')
    assert '# VALUE=base' in render.render_target(manifest, 't', None).splitlines()
    assert 'VALUE=base' in render.render_target(manifest, 'u', None).splitlines()


@pytest.mark.parametrize('env', [None, 'local'])
def test_v2_override_section_moves_only_target_var(write_manifest, env):
    _, render = _modules()
    manifest = _v2_render_manifest(write_manifest, 'section="Other"')
    value = 'base' if env is None else 'runtime'
    assert render.render_target(manifest, 't', env).split('\n\n', 1)[1] == (
        f'# == Database ==\nFIRST={value}\nLAST={value}\n\n# == Other ==\nVALUE={value}\n')
    assert render.render_target(manifest, 'u', env).split('\n\n', 1)[1] == (
        f'# == Database ==\nFIRST={value}\nVALUE={value}\nLAST={value}\n\n# == Other ==\n')


@pytest.mark.parametrize('env', [None, 'local'])
def test_v2_override_keeps_declaration_order(write_manifest, env):
    _, render = _modules()
    manifest = _v2_render_manifest(write_manifest, 'section="Database"')
    lines = render.render_target(manifest, 't', env).splitlines()
    names = [line.split('=')[0] for line in lines if '=' in line and not line.startswith('#')]
    assert names == ['FIRST', 'VALUE', 'LAST']


@pytest.mark.parametrize(('target', 'env', 'value'), [('a', 'local', 'x'), ('b', 'dev', 'y')])
def test_v2_render_uses_target_env_from_union(write_manifest, target, env, value):
    module, render = _modules()
    targets = '''version=1
[targets.a]
audience="backend"
envs=["local"]
sections=["Database"]
[targets.b]
audience="backend"
envs=["dev"]
sections=["Database"]
'''
    var = _var('VALUE', values={'local': 'x', 'dev': 'y'}).replace(
        'targets = ["t"]', 'targets = ["a", "b"]')
    manifest = module.load_manifest(write_manifest(targets, **{'10-main': 'version=1\n' + var}))
    assert f'VALUE={value}' in render.render_target(manifest, target, env).splitlines()


@pytest.mark.parametrize('mode', ['example', 'runtime'])
def test_v2_check_uses_effective_var(write_manifest, tmp_path, mode):
    module, render = _modules()
    manifest = _v2_render_manifest(write_manifest, 'example="custom"\nsection="Other"\ndoc="overridden"')
    env = None if mode == 'example' else 'local'
    value = 'base' if env is None else 'runtime'
    selected = 'custom' if env is None else 'runtime'
    expected = (f'{HEADER_LINE}\n# target: t env: {env or "example"} digest: '
        f'{module.target_digest(manifest, "t")}\n\n'
        f'# == Database ==\nFIRST={value}\nLAST={value}\n\n'
        f'# == Other ==\n# overridden\nVALUE={selected}\n')
    path = tmp_path / 't.example'
    path.write_text(expected, encoding='utf-8')
    path.chmod(0o600)
    messages = (render.check_example(manifest, 't', tmp_path) if env is None else
                render.check_runtime(manifest, 't', env, path))
    assert messages == []
