from __future__ import annotations

import io
from pathlib import Path

from conftest import load_module


INTO = "/opt/acx-backend/dev/.env"


def _manifest(write_manifest):
    return write_manifest(
        """
        version = 1

        [targets.t]
        audience = "backend"
        envs = ["dev"]
        sections = ["S"]
        remote_paths = {dev = "/opt/acx-backend/dev/.env"}
        """,
        **{
            "10-adopt": """
                version = 1

                [[var]]
                name = "LOG_LEVEL"
                class = "config"
                targets = ["t"]
                section = "S"
                example = "info"
                values = {dev = "info"}
            """
        },
    )


def _case(tmp_path: Path, write_manifest, old: bytes, backup: bytes):
    root = _manifest(write_manifest)
    fs = tmp_path / "fs"
    path = fs / INTO.lstrip("/")
    path.parent.mkdir(parents=True)
    path.write_bytes(old)
    path.chmod(0o600)
    backup_path = Path(f"{path}.pre-envman")
    backup_path.write_bytes(backup)
    return root, fs, path, backup_path


def _adopt(root: Path, fs: Path, tmp_path: Path) -> int:
    materialize = load_module("materialize")
    return materialize.run(
        root,
        env="dev",
        target="t",
        into=INTO,
        adopt=True,
        fs_root=fs,
        backup_root=tmp_path / "backups",
        now=lambda: 1_000_000.0,
        out=io.StringIO(),
        err=io.StringIO(),
    )


def test_adopt_converges_when_backup_matches_unheaded_file(tmp_path: Path, write_manifest):
    old = b"LOG_LEVEL=debug\n"
    root, fs, path, backup_path = _case(tmp_path, write_manifest, old, old)
    backup_inode = backup_path.stat().st_ino

    assert _adopt(root, fs, tmp_path) == 0

    assert path.read_bytes().startswith(b"# GENERATED by make env-render")
    assert backup_path.read_bytes() == old
    assert backup_path.stat().st_ino == backup_inode


def test_adopt_refuses_backup_that_differs_from_unheaded_file(tmp_path: Path, write_manifest):
    old = b"LOG_LEVEL=debug\n"
    other = b"LOG_LEVEL=warn\n"
    root, fs, path, backup_path = _case(tmp_path, write_manifest, old, other)

    assert _adopt(root, fs, tmp_path) == 2

    assert path.read_bytes() == old
    assert backup_path.read_bytes() == other
