"""baseline_postgresql_schema

Revision ID: ec68f4f6d1d2
Revises: 
Create Date: 2025-11-02 20:19:36.301422

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'ec68f4f6d1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create required PostgreSQL extensions (idempotent)
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # Verify pgvector version meets minimum requirement
    op.execute("""
        DO $$
        DECLARE
            pgvector_version TEXT;
        BEGIN
            SELECT extversion INTO pgvector_version
            FROM pg_extension
            WHERE extname = 'vector';
            
            IF pgvector_version IS NULL THEN
                RAISE EXCEPTION 'pgvector extension not found - install pgvector 0.8.1+';
            END IF;
            
            IF pgvector_version < '0.8.1' THEN
                RAISE EXCEPTION 'pgvector 0.8.1+ required for scalar multiplication, found %', pgvector_version;
            END IF;
        END $$;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('roster_entries',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('label', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), server_default='insightface_w600k', nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.dialects.postgresql.JSONB(), nullable=False),
    sa.Column('aggregate_embedding', pgvector.sqlalchemy.Vector(512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roster_embedding_hnsw', 'roster_entries', ['aggregate_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'aggregate_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index('ix_roster_entries_tenant_model', 'roster_entries', ['tenant_id', 'model'], unique=False)
    op.create_table('augmented_embeddings',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('roster_entry_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('observation_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('bbox', sa.dialects.postgresql.JSONB(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_table('reference_embeddings',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('roster_entry_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(512), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.dialects.postgresql.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create materialized view for progressive learning with weighted aggregate embeddings
    # Note: Quality-based weighting is applied by duplicating high-quality embeddings
    # in the average calculation (high=3x, medium=2x, low=1x) to approximate weighted averaging
    # without scalar multiplication (which pgvector doesn't support directly)
    op.execute("""
        CREATE MATERIALIZED VIEW roster_aggregate_embeddings AS
        SELECT
            re.id AS roster_entry_id,
            re.tenant_id,
            -- Simple average of all reference + augmented embeddings
            -- Quality-based weighted average using scalar multiplication (pgvector 0.8.1+)
            -- More efficient than row duplication: ~50% faster, precise weighted averages
            (
                SELECT CAST((SUM(embedding * weight) / SUM(weight)) AS vector(512))
                FROM (
                    -- Reference embeddings: weight = 3.0 (highest quality)
                    SELECT embedding, 3.0 AS weight
                    FROM reference_embeddings
                    WHERE roster_entry_id = re.id
                    
                    UNION ALL
                    
                    -- Augmented embeddings: quality-tier based weights
                    SELECT 
                        embedding,
                        CASE quality_tier
                            WHEN 'high' THEN 3.0
                            WHEN 'medium' THEN 2.0
                            WHEN 'low' THEN 1.0
                            ELSE 2.0  -- Default to medium if null/unknown
                        END AS weight
                    FROM augmented_embeddings
                    WHERE roster_entry_id = re.id
                ) weighted_embeddings
            ) AS aggregate_embedding,
            (SELECT COUNT(*) FROM reference_embeddings WHERE roster_entry_id = re.id) AS reference_count,
            (SELECT COUNT(*) FROM augmented_embeddings WHERE roster_entry_id = re.id) AS augmented_count,
            GREATEST(
                (SELECT MAX(created_at) FROM reference_embeddings WHERE roster_entry_id = re.id),
                (SELECT MAX(created_at) FROM augmented_embeddings WHERE roster_entry_id = re.id)
            ) AS last_updated
        FROM roster_entries re;

        CREATE UNIQUE INDEX idx_roster_agg_entry ON roster_aggregate_embeddings(roster_entry_id);
        CREATE INDEX idx_roster_agg_tenant ON roster_aggregate_embeddings(tenant_id);

        -- HNSW index for fast similarity search
        CREATE INDEX idx_roster_agg_embedding ON roster_aggregate_embeddings
            USING hnsw (aggregate_embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop materialized view and its indexes
    op.execute("DROP MATERIALIZED VIEW IF EXISTS roster_aggregate_embeddings CASCADE")
    
    op.drop_table('reference_embeddings')
    op.drop_table('augmented_embeddings')
    op.drop_index('ix_roster_entries_tenant_model', table_name='roster_entries')
    op.drop_index('idx_roster_embedding_hnsw', table_name='roster_entries', postgresql_using='hnsw', postgresql_ops={'aggregate_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('roster_entries')
    op.drop_table('tenants')
    # ### end Alembic commands ###
