"""baseline schema

Revision ID: 1238b18da821
Revises: 
Create Date: 2025-11-01 15:47:21.556778

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '1238b18da821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('roster_entries',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('label', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), server_default='insightface_w600k', nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.dialects.postgresql.JSONB(), nullable=False),
    sa.Column('aggregate_embedding', pgvector.sqlalchemy.Vector(512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roster_embedding_hnsw', 'roster_entries', ['aggregate_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'aggregate_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index('ix_roster_entries_tenant_model', 'roster_entries', ['tenant_id', 'model'], unique=False)
    op.create_table('augmented_embeddings',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('roster_entry_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('observation_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('bbox', sa.dialects.postgresql.JSONB(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_table('reference_embeddings',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('roster_entry_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(512), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.dialects.postgresql.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_embeddings')
    op.drop_table('augmented_embeddings')
    op.drop_index('ix_roster_entries_tenant_model', table_name='roster_entries')
    op.drop_index('idx_roster_embedding_hnsw', table_name='roster_entries', postgresql_using='hnsw', postgresql_ops={'aggregate_embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('roster_entries')
    op.drop_table('tenants')
    # ### end Alembic commands ###
