"""baseline schema

Revision ID: 7fe9d9f2b08f
Revises: 
Create Date: 2025-11-01 14:21:44.273920

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from db.models import JSONType, UUIDType, VectorType


revision = '7fe9d9f2b08f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('roster_entries',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('tenant_id', UUIDType(), nullable=False),
    sa.Column('label', sa.String(length=191), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), server_default='insightface_w600k', nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('aggregate_embedding', VectorType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roster_entries_tenant_model', 'roster_entries', ['tenant_id', 'model'], unique=False)
    op.create_table('augmented_embeddings',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('roster_entry_id', UUIDType(), nullable=False),
    sa.Column('observation_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', VectorType(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('bbox', JSONType(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_table('reference_embeddings',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('roster_entry_id', UUIDType(), nullable=False),
    sa.Column('embedding', VectorType(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_embeddings')
    op.drop_table('augmented_embeddings')
    op.drop_index('ix_roster_entries_tenant_model', table_name='roster_entries')
    op.drop_table('roster_entries')
    op.drop_table('tenants')
    # ### end Alembic commands ###
