<?php

declare(strict_types=1);

namespace ContextAltText\Recognition;

use WP_Error;
use WP_Image_Editor;
use function __;
use function get_attached_file;
use function is_wp_error;
use function wp_get_image_editor;

/**
 * Image Crop Utility
 *
 * @deprecated No longer used. Face thumbnails are now generated by the recognition service
 *             and included in the API response as base64-encoded images.
 *             
 * Historically cropped face regions from WordPress attachments for recognition processing.
 * Handled normalized bounding box coordinates, EXIF orientation, and
 * resizing to model input dimensions (112x112).
 *
 * @package ContextAltText\Recognition
 * @since 1.0.0
 */
class ImageCropUtility
{
    /** Model input size (InsightFace expects 112x112) */
    private const MODEL_INPUT_SIZE = 112;

    /**
     * Crop a face region from an attachment
     *
     * @param int $attachmentId WordPress attachment ID
     * @param array{x: float, y: float, width: float, height: float} $bbox Normalized bounding box (0-1 coordinates)
     * @return array{success: true, base64: string}|WP_Error Success with base64 image or error
     */
    public function cropFaceRegion(int $attachmentId, array $bbox): string|WP_Error
    {
        // Validate attachment exists
        $attachment = get_post($attachmentId);
        if ($attachment === null || $attachment->post_type !== 'attachment') {
            return new WP_Error(
                'invalid_attachment',
                sprintf('Invalid attachment ID: %d', $attachmentId),
                ['status' => 400]
            );
        }

        // Validate bbox coordinates
        $validation = $this->validateBbox($bbox);
        if (is_wp_error($validation)) {
            return $validation;
        }

        // Get attachment file path
        $filePath = get_attached_file($attachmentId);
        if ($filePath === false || $filePath === '') {
            return new WP_Error(
                'file_not_found',
                sprintf('Attachment file not found for ID %d', $attachmentId),
                ['status' => 404]
            );
        }

        // Check if file exists on disk
        // Support test mocking via global variable
        $fileExists = isset($GLOBALS['__cat_existing_files'][$filePath])
            ? $GLOBALS['__cat_existing_files'][$filePath]
            : file_exists($filePath);
        
        if (!$fileExists) {
            return new WP_Error(
                'file_not_found',
                sprintf('File does not exist: %s', $filePath),
                ['status' => 404]
            );
        }

        // Load image editor
        $editor = wp_get_image_editor($filePath);
        if (is_wp_error($editor)) {
            return new WP_Error(
                'image_editor_failed',
                'Failed to load image editor: ' . $editor->get_error_message(),
                ['status' => 500]
            );
        }

        // Get image dimensions
        $size = $editor->get_size();
        if ($size === false) {
            return new WP_Error(
                'image_size_failed',
                __('Failed to get image dimensions', 'context-alt-text'),
                ['status' => 500]
            );
        }

        $imageWidth = $size['width'];
        $imageHeight = $size['height'];

        // Convert normalized bbox to pixel coordinates
        $x = (int) round($bbox['x'] * $imageWidth);
        $y = (int) round($bbox['y'] * $imageHeight);
        $width = (int) round($bbox['width'] * $imageWidth);
        $height = (int) round($bbox['height'] * $imageHeight);

        // Ensure dimensions are within image bounds
        $x = max(0, min($x, $imageWidth - 1));
        $y = max(0, min($y, $imageHeight - 1));
        $width = max(1, min($width, $imageWidth - $x));
        $height = max(1, min($height, $imageHeight - $y));

        error_log(sprintf('[ImageCropUtility] Attachment %d: Image %dx%d, Crop region (%d,%d) %dx%d', 
            $attachmentId, $imageWidth, $imageHeight, $x, $y, $width, $height));

        // Crop the region
        $cropResult = $editor->crop($x, $y, $width, $height);
        if (is_wp_error($cropResult) || $cropResult === false) {
            error_log(sprintf('[ImageCropUtility] Crop operation failed for attachment %d', $attachmentId));
            return new WP_Error(
                'crop_failed',
                __('Failed to crop image region', 'context-alt-text'),
                ['status' => 500]
            );
        }

        // Resize to model input size (112x112)
        $resizeResult = $editor->resize(self::MODEL_INPUT_SIZE, self::MODEL_INPUT_SIZE, false);

        if (is_wp_error($resizeResult) || $resizeResult === false) {
            $currentSize = $editor->get_size();
            $canUpscale = $currentSize !== false
                && ($currentSize['width'] < self::MODEL_INPUT_SIZE || $currentSize['height'] < self::MODEL_INPUT_SIZE);

            if ($canUpscale) {
                $resizeResult = $editor->resize(self::MODEL_INPUT_SIZE, self::MODEL_INPUT_SIZE, true);
            }

            if (is_wp_error($resizeResult) || $resizeResult === false) {
                $errorMessage = is_wp_error($resizeResult)
                    ? $resizeResult->get_error_message()
                    : __('Failed to resize cropped region', 'context-alt-text');

                error_log(sprintf('[ImageCropUtility] Resize failed for attachment %d: %s', $attachmentId, $errorMessage));

                return new WP_Error(
                    'resize_failed',
                    $errorMessage,
                    ['status' => 500]
                );
            }
        }

        // Capture output buffer for base64 encoding
        ob_start();
        $streamResult = $editor->stream('image/jpeg');
        $imageContent = ob_get_clean();

        if ($streamResult === false || $imageContent === false || $imageContent === '') {
            return new WP_Error(
                'encode_failed',
                __('Failed to capture image data', 'context-alt-text'),
                ['status' => 500]
            );
        }

        $base64 = base64_encode($imageContent);
        return 'data:image/jpeg;base64,' . $base64;
    }

    /**
     * Validate bounding box coordinates
     *
     * @param array<string,mixed> $bbox Bounding box to validate
     * @return WP_Error|null Error if invalid, null if valid
     */
    private function validateBbox(array $bbox): ?WP_Error
    {
        $requiredKeys = ['x', 'y', 'width', 'height'];

        foreach ($requiredKeys as $key) {
            if (!isset($bbox[$key])) {
                return new WP_Error(
                    'invalid_bbox',
                    sprintf(__('Missing bbox coordinate: %s', 'context-alt-text'), $key),
                    ['status' => 400]
                );
            }

            $value = $bbox[$key];
            if (!is_numeric($value)) {
                return new WP_Error(
                    'invalid_bbox',
                    sprintf(__('Invalid bbox coordinate type: %s must be numeric', 'context-alt-text'), $key),
                    ['status' => 400]
                );
            }

            // Validate range (0-1 for normalized coordinates)
            $numericValue = (float) $value;
            if ($numericValue < 0.0 || $numericValue > 1.0) {
                return new WP_Error(
                    'invalid_bbox',
                    sprintf(
                        __('Bbox coordinate out of range: %s must be between 0 and 1', 'context-alt-text'),
                        $key
                    ),
                    ['status' => 400]
                );
            }
        }

        return null;
    }
}
