#!/usr/bin/env python3
"""Persist a minted GPU Vault secret OCID into its manifest refs."""

from __future__ import annotations

import argparse
import copy
import fcntl
import hashlib
import os
import re
import stat
import subprocess
import sys
import tempfile
import time
import tomllib
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator


_SECRET_OCID_PATTERN = r"ocid1\.vaultsecret\.oc[0-9]+\.[A-Za-z0-9_-]*\.[A-Za-z0-9._-]{20,}"
_SECRET_OCID = re.compile(rf"^{_SECRET_OCID_PATTERN}$")
# Used only to exercise the updater before writer contact; its result is discarded.
_PREFLIGHT_PROBE_OCID = "ocid1.vaultsecret.oc1.iad." + "p" * 24
_TABLE_HEADER = re.compile(r"(?m)^\[\[[^\]]+\]\][ \t]*\r?$")
_VAR_HEADER = re.compile(r"(?m)^\[\[var\]\][ \t]*\r?$")
_SECRET_LINE = re.compile(r"(?m)^secret\s*=\s*\{[^\n]*\}\r?$")
_TERRAFORM_INPUT_LINE = re.compile(
    r'^# Generated by scripts/deploy/gpu-key-mint\.sh; identifier only\.\n'
    rf'gpu_api_key_secret_ocid = "(?P<ocid>{_SECRET_OCID_PATTERN})"\n$'
)
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_TRANSACTION_LOCKED_ENV = "GPU_KEY_MINT_TRANSACTION_LOCKED"
_TRANSACTION_LOCK_FD_ENV = "GPU_KEY_MINT_TRANSACTION_LOCK_FD"
_MANIFEST_LOCK_TIMEOUT_SECONDS = 5.0
_MANIFEST_LOCK_RETRY_SECONDS = 0.05


def _replace_env_ref(secret_line: str, env: str, value: str) -> str:
    pattern = re.compile(
        rf"(?<![A-Za-z0-9_])({re.escape(env)}\s*=\s*)"
        r"(?P<quote>[\"'])(?P<value>[^\"'\n]*)(?P=quote)(?=\s*(?:,|\}))"
    )
    updated, count = pattern.subn(rf'\g<1>"{value}"', secret_line)
    if count != 1:
        raise ValueError(f"GPU key manifest must contain exactly one {env} secret ref")
    return updated


def validate_manifest_ready(document: dict[str, object]) -> None:
    """Require the derived four-secret prod map before any GPU key mutation."""
    maps = [row for row in document.get("var", []) if row.get("name") == "RECOGNITION_VAULT_SECRET_MAP"]
    if len(maps) != 1:
        raise ValueError("GPU mint requires one RECOGNITION_VAULT_SECRET_MAP var")
    map_var = maps[0]
    if (
        map_var.get("class") != "config"
        or map_var.get("derive_vault_map") is not True
        or not _targets_include_svc_vm(map_var)
    ):
        raise ValueError("GPU mint requires the svc-vm derived Vault secret map")
    if any(source in map_var for source in ("values", "secret", "derive", "secret_refs")):
        raise ValueError("GPU mint requires an exclusive derived Vault secret map")

    required_names = ("PGPASSWORD", "POSTGRES_DSN", "POSTGRES_SYNC_DSN", "RECOGNITION_ADMIN_TOKEN")
    for name in required_names:
        refs = [row for row in document.get("var", []) if row.get("name") == name]
        if len(refs) != 1 or not _targets_include_svc_vm(refs[0]):
            raise ValueError(f"GPU mint requires a svc-vm {name} Vault ref")
        if refs[0].get("class") != "secret":
            raise ValueError(f"GPU mint requires a secret-class {name} Vault ref")
        secret_refs = refs[0].get("secret")
        if not isinstance(secret_refs, dict):
            raise ValueError(f"GPU mint requires a prod Vault ref for {name}")
        reference = secret_refs.get("prod")
        if not isinstance(reference, str):
            raise ValueError(f"GPU mint requires a prod Vault ref for {name}")
        scheme, separator, ocid = reference.partition(":")
        if scheme != "vault" or not separator or not _SECRET_OCID.fullmatch(ocid):
            raise ValueError(f"GPU mint requires a real prod vault ref for {name}")

    variable = _unique_gpu_key_var(document)
    if variable.get("class") != "secret" or not _targets_include_svc_vm(variable):
        raise ValueError("GPU key manifest var must remain a svc-vm secret")
    _gpu_key_secret_refs(variable)


def _targets_include_svc_vm(variable: dict[str, object]) -> bool:
    """Match the manifest loader's required list-of-strings target shape."""
    targets = variable.get("targets")
    return (
        isinstance(targets, list)
        and all(isinstance(target, str) for target in targets)
        and "svc-vm" in targets
    )


def _valid_secret_reference(reference: object) -> bool:
    """Check ref syntax without resolving the secret or contacting a provider."""
    if not isinstance(reference, str):
        return False
    scheme, separator, location = reference.partition(":")
    if not separator:
        return False
    if scheme == "host":
        return not location
    if scheme == "env":
        return bool(location)
    if scheme == "keychain":
        service, slash, account = location.partition("/")
        return bool(slash and service and account)
    if scheme in {"vault", "oci"}:
        # The shared manifest loader accepts this OCID under either `vault` or `oci`.
        return _SECRET_OCID.fullmatch(location) is not None
    return False


def _gpu_key_secret_refs(variable: dict[str, object]) -> dict[str, object]:
    refs = variable.get("secret")
    required = {"dev", "staging", "prod"}
    if not isinstance(refs, dict) or not required <= refs.keys():
        raise ValueError("GPU key manifest must define dev, staging, and prod refs")
    if any(not _valid_secret_reference(reference) for reference in refs.values()):
        raise ValueError("GPU key manifest contains an invalid secret ref")
    return refs


def _unique_gpu_key_var(document: dict[str, object]) -> dict[str, object]:
    variables = [
        row for row in document.get("var", [])
        if row.get("name") == "ACX_GPU_ENDPOINT_API_KEY"
    ]
    if len(variables) != 1:
        raise ValueError("GPU key manifest must contain exactly one ACX_GPU_ENDPOINT_API_KEY var")
    return variables[0]


def update_manifest_text(text: str, secret_ocid: str) -> str:
    """Return updated TOML, changing only the GPU key's dev/prod references."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    try:
        document = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError("GPU key manifest is not valid TOML") from exc
    validate_manifest_ready(document)

    return _update_gpu_key_text(text, secret_ocid)


def _update_gpu_key_text(text: str, secret_ocid: str) -> str:
    try:
        document = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError("GPU key manifest is not valid TOML") from exc

    variable = _unique_gpu_key_var(document)
    if variable.get("class") != "secret" or not _targets_include_svc_vm(variable):
        raise ValueError("GPU key manifest var must remain a svc-vm secret")

    refs = _gpu_key_secret_refs(variable)
    expected_refs = {"dev": f"oci:{secret_ocid}", "prod": f"vault:{secret_ocid}"}
    for env, expected in expected_refs.items():
        if refs[env] not in {"host:", expected}:
            raise ValueError(f"refusing to replace existing {env} GPU key ref")

    matches = list(_VAR_HEADER.finditer(text))
    blocks = []
    for match in matches:
        end = _TABLE_HEADER.search(text, match.end())
        block_end = end.start() if end is not None else len(text)
        block = text[match.start():block_end]
        try:
            parsed = tomllib.loads(block)
        except tomllib.TOMLDecodeError:
            continue
        row = parsed.get("var", [{}])[0]
        if row.get("name") == "ACX_GPU_ENDPOINT_API_KEY":
            blocks.append((match.start(), block_end, block))
    if len(blocks) != 1:
        raise ValueError("could not isolate GPU key manifest var")

    start, end, block = blocks[0]
    secret_lines = list(_SECRET_LINE.finditer(block))
    if len(secret_lines) != 1:
        raise ValueError("GPU key manifest var must contain one inline secret map")
    secret_line = secret_lines[0].group(0)
    for env, expected in expected_refs.items():
        scheme, _, existing_ocid = refs[env].partition(":")
        if scheme == "host":
            secret_line = _replace_env_ref(secret_line, env, expected)
        elif existing_ocid != secret_ocid:
            raise ValueError(f"refusing to replace existing {env} GPU key OCID")
    updated_block = block[:secret_lines[0].start()] + secret_line + block[secret_lines[0].end():]
    updated_text = text[:start] + updated_block + text[end:]
    try:
        updated_document = tomllib.loads(updated_text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError("GPU key update would produce invalid TOML") from exc

    expected_document = copy.deepcopy(document)
    expected_refs = _unique_gpu_key_var(expected_document)["secret"]
    expected_refs["dev"] = f"oci:{secret_ocid}"
    expected_refs["prod"] = f"vault:{secret_ocid}"
    if updated_document != expected_document:
        raise ValueError("GPU key update changed unrelated manifest values")
    return updated_text


def _validate_gpu_owner_publishable(owner_text: str, current_ocid: str | None) -> None:
    """Run the persistence updater before contacting the remote writer."""
    _update_gpu_key_text(owner_text, current_ocid or _PREFLIGHT_PROBE_OCID)


def _manifest_fragment_paths(path: Path) -> list[Path]:
    if path.is_dir():
        directory = path
        requested_fragment = None
    else:
        try:
            source_stat = path.lstat()
        except OSError as exc:
            raise ValueError("cannot read GPU key manifest") from exc
        if not stat.S_ISREG(source_stat.st_mode):
            raise ValueError("GPU key manifest must be a regular file or fragment directory")
        directory = path.parent
        requested_fragment = path

    try:
        fragments = sorted(
            fragment
            for fragment in directory.glob("*.toml")
            if fragment.name != "targets.toml"
        )
    except OSError as exc:
        raise ValueError("cannot list GPU key manifest fragments") from exc
    if not fragments or (requested_fragment is not None and requested_fragment not in fragments):
        raise ValueError("cannot read GPU key manifest")
    return fragments


def _load_manifest_fragments(
    path: Path,
) -> tuple[dict[str, object], dict[Path, tuple[str, dict[str, object], bytes]]]:
    all_variables: list[dict[str, object]] = []
    fragments: dict[Path, tuple[str, dict[str, object], bytes]] = {}
    for fragment_path in _manifest_fragment_paths(path):
        try:
            raw_text = fragment_path.read_bytes()
            text = raw_text.decode("utf-8")
        except (OSError, UnicodeError) as exc:
            raise ValueError("cannot read GPU key manifest") from exc
        try:
            fragment = tomllib.loads(text)
        except tomllib.TOMLDecodeError as exc:
            raise ValueError("GPU key manifest is not valid TOML") from exc
        fragment_variables = fragment.get("var", [])
        if not isinstance(fragment_variables, list) or any(
            not isinstance(row, dict) for row in fragment_variables
        ):
            raise ValueError("GPU key manifest var entries must be tables")
        all_variables.extend(fragment_variables)
        fragments[fragment_path] = (text, fragment, raw_text)
    return {"var": all_variables}, fragments


def manifest_write_lock_path(manifest_path: Path) -> Path:
    """Return the environment-root lock path shared with the harvest CLI."""
    directory = manifest_path if manifest_path.is_dir() else manifest_path.parent
    canonical_directory = directory.resolve()
    if canonical_directory.name == "manifest.d":
        canonical_directory = canonical_directory.parent
    digest = hashlib.sha256(os.fsencode(str(canonical_directory))).hexdigest()
    return Path(f"/tmp/acx-envman-manifest-write-{os.getuid()}-{digest}.lock")


def _open_manifest_write_lock(manifest_path: Path) -> int:
    lock_path = manifest_write_lock_path(manifest_path)
    descriptor = -1
    try:
        descriptor = os.open(
            lock_path,
            os.O_CREAT
            | os.O_RDWR
            | getattr(os, "O_NOFOLLOW", 0)
            | getattr(os, "O_CLOEXEC", 0),
            0o600,
        )
        lock_stat = os.fstat(descriptor)
        if (
            not stat.S_ISREG(lock_stat.st_mode)
            or lock_stat.st_uid != os.getuid()
            or lock_stat.st_nlink != 1
        ):
            raise ValueError("manifest write lock must be a private regular owner file")
        os.fchmod(descriptor, 0o600)
        lock_stat = os.fstat(descriptor)
        if stat.S_IMODE(lock_stat.st_mode) != 0o600:
            raise ValueError("manifest write lock must be owner-only")
        deadline = time.monotonic() + _MANIFEST_LOCK_TIMEOUT_SECONDS
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise ValueError("timed out acquiring GPU key manifest write lock")
            try:
                fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
                return descriptor
            except BlockingIOError:
                time.sleep(min(_MANIFEST_LOCK_RETRY_SECONDS, remaining))
    except OSError as exc:
        if descriptor >= 0:
            os.close(descriptor)
        raise ValueError("cannot lock GPU key manifest directory") from exc
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        raise


@contextmanager
def _manifest_write_lock(manifest_path: Path) -> Iterator[None]:
    """Acquire the shared ABI lock for standalone manifest operations."""
    descriptor = _open_manifest_write_lock(manifest_path)
    try:
        yield
    finally:
        os.close(descriptor)


def _verify_transaction_lock_handoff(manifest_path: Path) -> None:
    """Require the internal caller's inherited descriptor to hold this lock."""
    raw_descriptor = os.environ.get(_TRANSACTION_LOCK_FD_ENV, "")
    if not raw_descriptor.isascii() or not raw_descriptor.isdecimal() or len(raw_descriptor) > 10:
        raise ValueError("GPU key transaction lock handoff is missing")
    descriptor = int(raw_descriptor)
    lock_path = manifest_write_lock_path(manifest_path)
    try:
        inherited_stat = os.fstat(descriptor)
        path_stat = lock_path.lstat()
    except OSError as exc:
        raise ValueError("GPU key transaction lock handoff is invalid") from exc
    if (
        not stat.S_ISREG(inherited_stat.st_mode)
        or inherited_stat.st_uid != os.getuid()
        or inherited_stat.st_nlink != 1
        or stat.S_IMODE(inherited_stat.st_mode) != 0o600
        or (inherited_stat.st_dev, inherited_stat.st_ino)
        != (path_stat.st_dev, path_stat.st_ino)
    ):
        raise ValueError("GPU key transaction lock handoff is invalid")
    try:
        fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise ValueError("GPU key transaction lock is not held") from exc
    except OSError as exc:
        raise ValueError("GPU key transaction lock handoff is invalid") from exc


def _validate_transaction_handoff(
    manifest_path: Path,
    terraform_input_path: Path,
    expected_owner_sha256: str,
    expected_terraform_input_sha256: str,
    expected_secret_id: str | None,
) -> None:
    _verify_transaction_lock_handoff(manifest_path)
    if not _SHA256.fullmatch(expected_owner_sha256):
        raise ValueError("invalid expected manifest preimage hash")
    if expected_terraform_input_sha256 != "missing" and not _SHA256.fullmatch(
        expected_terraform_input_sha256
    ):
        raise ValueError("invalid expected Terraform input preimage hash")
    current_secret_id, owner_path, preimages = _preflight_mint_transaction(
        manifest_path,
        terraform_input_path,
    )
    if expected_secret_id != current_secret_id:
        raise ValueError("GPU key secret identity changed before writer contact")
    expected_input_hash = (
        None if expected_terraform_input_sha256 == "missing" else expected_terraform_input_sha256
    )
    if (
        preimages[owner_path] != expected_owner_sha256
        or preimages[terraform_input_path] != expected_input_hash
    ):
        raise ValueError("GPU key mint transaction preimage changed before writer contact")


def check_manifest_ready(path: Path) -> None:
    with _manifest_write_lock(path):
        document, _, owner_text, _ = _manifest_gpu_owner(path)
        _validate_gpu_owner_publishable(owner_text, _current_gpu_key_ocid(document))


def _durable_replace(path: Path, updated_text: str, mode: int) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f"{path.name}.envman-tmp-",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as stream:
            descriptor = -1
            stream.write(updated_text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
        directory_fd = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass


def _fsync_directory(directory: Path) -> None:
    directory_fd = os.open(directory, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def _stage_bytes(path: Path, content: bytes, mode: int) -> Path:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f"{path.name}.envman-tmp-",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "wb") as stream:
            descriptor = -1
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        temporary_path.unlink(missing_ok=True)
        raise
    return temporary_path


def _content_sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _file_sha256_or_missing(path: Path) -> str | None:
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ValueError("cannot inspect GPU key persistence destination") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("GPU key persistence destination must be a regular file")
    try:
        return _content_sha256(path.read_bytes())
    except OSError as exc:
        raise ValueError("cannot read GPU key persistence destination") from exc


def _assert_preimage(path: Path, expected_sha256: str | None) -> None:
    if _file_sha256_or_missing(path) != expected_sha256:
        raise ValueError("GPU key persistence destination changed during GPU key mint transaction")


def _publish_atomic_updates(
    updates: list[tuple[Path, bytes, int]],
    expected_preimages: dict[Path, str | None] | None = None,
) -> None:
    """Prepare all files, publish them, and restore preimages after any late error."""
    plans: list[dict[str, object]] = []
    try:
        for path, content, mode in updates:
            try:
                source_stat = path.lstat()
            except FileNotFoundError:
                existed = False
                old_content = None
                old_mode = mode
            except OSError as exc:
                raise ValueError("cannot inspect GPU key persistence destination") from exc
            else:
                if not stat.S_ISREG(source_stat.st_mode):
                    raise ValueError("GPU key persistence destination must be a regular file")
                try:
                    old_content = path.read_bytes()
                except OSError as exc:
                    raise ValueError("cannot read GPU key persistence destination") from exc
                existed = True
                old_mode = stat.S_IMODE(source_stat.st_mode)
            if existed and old_content == content and old_mode == mode:
                continue
            staged = _stage_bytes(path, content, mode)
            try:
                restore = _stage_bytes(path, old_content, old_mode) if existed else None
            except BaseException:
                staged.unlink(missing_ok=True)
                raise
            plans.append(
                {
                    "path": path,
                    "staged": staged,
                    "restore": restore,
                    "existed": existed,
                }
            )
    except OSError as exc:
        for plan in plans:
            for key in ("staged", "restore"):
                temporary = plan[key]
                if isinstance(temporary, Path):
                    temporary.unlink(missing_ok=True)
        raise ValueError("cannot prepare GPU key persistence destinations") from exc
    except BaseException:
        for plan in plans:
            for key in ("staged", "restore"):
                temporary = plan[key]
                if isinstance(temporary, Path):
                    temporary.unlink(missing_ok=True)
        raise

    attempted: list[dict[str, object]] = []
    try:
        for plan in plans:
            path = plan["path"]
            staged = plan["staged"]
            assert isinstance(path, Path) and isinstance(staged, Path)
            if expected_preimages is not None and path in expected_preimages:
                _assert_preimage(path, expected_preimages[path])
            attempted.append(plan)
            os.replace(staged, path)
            plan["staged"] = None
            _fsync_directory(path.parent)
    except BaseException as exc:
        rollback_failed = False
        for plan in reversed(attempted):
            path = plan["path"]
            restore = plan["restore"]
            existed = plan["existed"]
            assert isinstance(path, Path) and isinstance(existed, bool)
            try:
                if existed:
                    assert isinstance(restore, Path)
                    os.replace(restore, path)
                    plan["restore"] = None
                else:
                    path.unlink(missing_ok=True)
                _fsync_directory(path.parent)
            except OSError:
                rollback_failed = True
        if rollback_failed:
            raise ValueError("GPU key persistence failed and rollback was incomplete") from exc
        if isinstance(exc, OSError):
            raise ValueError("GPU key persistence failed; local updates rolled back") from exc
        raise
    finally:
        for plan in plans:
            for key in ("staged", "restore"):
                temporary = plan[key]
                if isinstance(temporary, Path):
                    temporary.unlink(missing_ok=True)


def _test_writable_destination(path: Path) -> None:
    if not path.parent.is_dir():
        raise ValueError("GPU key persistence destination parent must be a directory")
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        pass
    except OSError as exc:
        raise ValueError("cannot inspect GPU key persistence destination") from exc
    else:
        if not stat.S_ISREG(source_stat.st_mode):
            raise ValueError("GPU key persistence destination must be a regular file")
    descriptor = -1
    temporary_path: Path | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.gpu-key-preflight-",
            dir=path.parent,
        )
        temporary_path = Path(temporary_name)
        os.fsync(descriptor)
    except OSError as exc:
        raise ValueError("GPU key persistence destination is not writable") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary_path is not None:
            try:
                temporary_path.unlink()
            except OSError as exc:
                raise ValueError("cannot clean GPU key persistence preflight file") from exc


def _current_gpu_key_ocid(document: dict[str, object]) -> str | None:
    refs = _unique_gpu_key_var(document).get("secret")
    if not isinstance(refs, dict):
        raise ValueError("GPU key manifest must define secret refs")
    dev = refs.get("dev", "")
    prod = refs.get("prod", "")
    if not isinstance(dev, str) or not isinstance(prod, str):
        raise ValueError("GPU key manifest dev/prod refs are inconsistent")
    if dev == "host:" and prod == "host:":
        return None
    dev_scheme, dev_separator, dev_ocid = dev.partition(":")
    prod_scheme, prod_separator, prod_ocid = prod.partition(":")
    if (
        dev_scheme != "oci"
        or prod_scheme != "vault"
        or not dev_separator
        or not prod_separator
        or dev_ocid != prod_ocid
        or not _SECRET_OCID.fullmatch(dev_ocid)
    ):
        raise ValueError("GPU key manifest dev/prod refs are inconsistent")
    return dev_ocid


def _terraform_input_text(secret_ocid: str) -> str:
    return (
        "# Generated by scripts/deploy/gpu-key-mint.sh; identifier only.\n"
        f'gpu_api_key_secret_ocid = "{secret_ocid}"\n'
    )


def _existing_terraform_input_ocid(path: Path) -> str | None:
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ValueError("cannot inspect Terraform GPU key input") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("Terraform GPU key input must be a regular file")
    try:
        existing_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError("cannot read Terraform GPU key input") from exc
    match = _TERRAFORM_INPUT_LINE.fullmatch(existing_text)
    if match is None:
        raise ValueError("refusing unknown or stale Terraform GPU key input")
    return match.group("ocid")


def _manifest_gpu_owner(
    path: Path,
) -> tuple[dict[str, object], Path, str, dict[Path, tuple[str, dict[str, object], bytes]]]:
    document, fragments = _load_manifest_fragments(path)
    validate_manifest_ready(document)
    owners = [
        (fragment_path, text)
        for fragment_path, (text, fragment, _) in fragments.items()
        if any(row.get("name") == "ACX_GPU_ENDPOINT_API_KEY" for row in fragment.get("var", []))
    ]
    if len(owners) != 1:
        raise ValueError("GPU key manifest must contain exactly one ACX_GPU_ENDPOINT_API_KEY var")
    owner_path, owner_text = owners[0]
    return document, owner_path, owner_text, fragments


def _preflight_mint_transaction(
    manifest_path: Path,
    terraform_input_path: Path,
) -> tuple[str | None, Path, dict[Path, str | None]]:
    document, owner_path, owner_text, fragments = _manifest_gpu_owner(manifest_path)
    if owner_path.resolve() == terraform_input_path.resolve():
        raise ValueError("GPU manifest and Terraform input destinations must differ")
    current_ocid = _current_gpu_key_ocid(document)
    _validate_gpu_owner_publishable(owner_text, current_ocid)
    artifact_ocid = _existing_terraform_input_ocid(terraform_input_path)
    if artifact_ocid is not None and artifact_ocid != current_ocid:
        raise ValueError("refusing conflicting or stale Terraform GPU key input")
    _test_writable_destination(owner_path)
    _test_writable_destination(terraform_input_path)
    return current_ocid, owner_path, {
        owner_path: _content_sha256(fragments[owner_path][2]),
        terraform_input_path: _file_sha256_or_missing(terraform_input_path),
    }


def _persist_mint_result_unlocked(
    manifest_path: Path,
    terraform_input_path: Path,
    secret_ocid: str,
    expected_preimages: dict[Path, str | None] | None = None,
) -> None:
    """Persist manifest and Terraform identifiers as one rollback-capable local transaction."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    document, owner_path, owner_text, _ = _manifest_gpu_owner(manifest_path)
    if owner_path.resolve() == terraform_input_path.resolve():
        raise ValueError("GPU manifest and Terraform input destinations must differ")
    current_ocid = _current_gpu_key_ocid(document)
    artifact_ocid = _existing_terraform_input_ocid(terraform_input_path)
    if artifact_ocid is not None and artifact_ocid != current_ocid:
        raise ValueError("refusing conflicting or stale Terraform GPU key input")
    if expected_preimages is not None:
        if set(expected_preimages) != {owner_path, terraform_input_path}:
            raise ValueError("GPU key transaction preimage snapshot is incomplete")
        for path, expected_sha256 in expected_preimages.items():
            _assert_preimage(path, expected_sha256)

    updated_manifest = _update_gpu_key_text(owner_text, secret_ocid)
    updated_input = _terraform_input_text(secret_ocid)
    manifest_stat = owner_path.lstat()
    terraform_mode = 0o600
    try:
        terraform_stat = terraform_input_path.lstat()
    except FileNotFoundError:
        pass
    else:
        if not stat.S_ISREG(terraform_stat.st_mode):
            raise ValueError("Terraform GPU key input must be a regular file")
    _publish_atomic_updates(
        [
            (owner_path, updated_manifest.encode("utf-8"), stat.S_IMODE(manifest_stat.st_mode)),
            (terraform_input_path, updated_input.encode("utf-8"), terraform_mode),
        ],
        expected_preimages,
    )


def persist_mint_result(
    manifest_path: Path,
    terraform_input_path: Path,
    secret_ocid: str,
    expected_preimages: dict[Path, str | None] | None = None,
) -> None:
    """Persist both identifiers while holding the shared manifest-directory lock."""
    with _manifest_write_lock(manifest_path):
        _persist_mint_result_unlocked(
            manifest_path,
            terraform_input_path,
            secret_ocid,
            expected_preimages,
        )


def persist_manifest(path: Path, updated_text: str) -> None:
    """Durably atomically replace the regular manifest file."""
    try:
        source_stat = path.lstat()
    except OSError as exc:
        raise ValueError("cannot inspect GPU key manifest") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("GPU key manifest must be a regular file")
    _durable_replace(path, updated_text, stat.S_IMODE(source_stat.st_mode))


def write_terraform_input(path: Path, secret_ocid: str) -> None:
    """Create a durable Terraform input file containing only the secret OCID."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    updated_text = _terraform_input_text(secret_ocid)
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        _durable_replace(path, updated_text, 0o600)
        return
    except OSError as exc:
        raise ValueError("cannot inspect Terraform GPU key input") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("Terraform GPU key input must be a regular file")
    try:
        existing_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError("cannot read Terraform GPU key input") from exc
    if existing_text == updated_text and stat.S_IMODE(source_stat.st_mode) == 0o600:
        return
    if existing_text != updated_text:
        raise ValueError("refusing to replace existing Terraform GPU key input")
    _durable_replace(path, updated_text, 0o600)


def set_gpu_key_ocid(path: Path, secret_ocid: str) -> None:
    """Update the manifest with the real OCID returned by the Vault writer."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    with _manifest_write_lock(path):
        _, owner_path, original, _ = _manifest_gpu_owner(path)
        updated = _update_gpu_key_text(original, secret_ocid)
        if updated != original:
            persist_manifest(owner_path, updated)


def _run_locked_transaction(
    manifest_path: Path,
    terraform_input_path: Path,
    rotate: bool,
    approve_mint: bool,
) -> int:
    if not approve_mint:
        raise ValueError("--run-locked requires explicit --approve-mint")
    descriptor = -1
    try:
        descriptor = _open_manifest_write_lock(manifest_path)
        expected_secret_id, owner_path, expected_preimages = _preflight_mint_transaction(
            manifest_path,
            terraform_input_path,
        )
        if rotate and expected_secret_id is None:
            raise ValueError("GPU key rotation requires a recorded GPU secret OCID; bootstrap first")
        command = [
            "bash",
            str(Path(__file__).with_name("gpu-key-mint.sh")),
        ]
        if approve_mint:
            command.append("--approve-mint")
        command.extend([
            "--manifest",
            str(manifest_path),
            "--terraform-input",
            str(terraform_input_path),
            "--expected-owner-sha256",
            expected_preimages[owner_path] or "missing",
            "--expected-terraform-input-sha256",
            expected_preimages[terraform_input_path] or "missing",
        ])
        if expected_secret_id is not None:
            command.extend(["--expected-secret-id", expected_secret_id])
        if rotate:
            command.append("--rotate")
        environment = os.environ.copy()
        environment["GPU_KEY_MINT_TRANSACTION_LOCKED"] = "1"
        environment[_TRANSACTION_LOCK_FD_ENV] = str(descriptor)
        completed = subprocess.run(
            command,
            check=False,
            env=environment,
            pass_fds=(descriptor,),
            capture_output=True,
            text=True,
        )
        if completed.stderr:
            sys.stderr.write(completed.stderr)
        if completed.returncode != 0:
            return completed.returncode
        result = completed.stdout
        if not result.endswith("\n") or result.count("\n") != 1:
            raise ValueError("GPU key writer returned an invalid result")
        fields = result[:-1].split()
        if len(fields) != 2 or not _SECRET_OCID.fullmatch(fields[0]) or fields[1] != "64":
            raise ValueError("GPU key writer returned an invalid result")
        if expected_secret_id is not None and fields[0] != expected_secret_id:
            raise ValueError("Vault writer returned a different GPU key secret identity")
        _persist_mint_result_unlocked(
            manifest_path,
            terraform_input_path,
            fields[0],
            expected_preimages,
        )
        sys.stdout.write(result)
        return 0
    except OSError as exc:
        raise ValueError("cannot lock or run GPU key mint transaction") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)


def default_manifest_path() -> Path:
    return Path(__file__).resolve().parents[2] / "config/env/manifest.d/10-service-shared.toml"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("secret_ocid", nargs="?")
    parser.add_argument("--manifest", type=Path, default=default_manifest_path())
    parser.add_argument("--terraform-input", type=Path)
    parser.add_argument("--check-ready", action="store_true")
    parser.add_argument("--run-locked", action="store_true")
    parser.add_argument("--approve-mint", action="store_true")
    parser.add_argument("--validate-transaction", action="store_true")
    parser.add_argument("--rotate", action="store_true")
    parser.add_argument("--expected-owner-sha256")
    parser.add_argument("--expected-terraform-input-sha256")
    parser.add_argument("--expected-secret-id")
    args = parser.parse_args()
    if args.run_locked:
        if (
            args.secret_ocid is not None
            or args.check_ready
            or args.validate_transaction
            or args.terraform_input is None
            or args.expected_owner_sha256 is not None
            or args.expected_terraform_input_sha256 is not None
            or args.expected_secret_id is not None
        ):
            parser.error("--run-locked requires --terraform-input and does not accept other modes")
        if not args.approve_mint:
            parser.error("--run-locked requires explicit --approve-mint")
        return _run_locked_transaction(
            args.manifest,
            args.terraform_input,
            args.rotate,
            args.approve_mint,
        )
    if args.validate_transaction:
        if (
            args.secret_ocid is not None
            or args.check_ready
            or args.run_locked
            or args.approve_mint
            or args.terraform_input is None
            or args.rotate
            or args.expected_owner_sha256 is None
            or args.expected_terraform_input_sha256 is None
        ):
            parser.error("--validate-transaction requires preimage hashes and --terraform-input")
        if args.expected_secret_id is not None and not _SECRET_OCID.fullmatch(args.expected_secret_id):
            parser.error("invalid expected GPU key secret ID")
        _validate_transaction_handoff(
            args.manifest,
            args.terraform_input,
            args.expected_owner_sha256,
            args.expected_terraform_input_sha256,
            args.expected_secret_id,
        )
        return 0
    if args.check_ready:
        if (
            args.secret_ocid is not None
            or args.terraform_input is not None
            or args.approve_mint
            or args.rotate
            or args.expected_owner_sha256 is not None
            or args.expected_terraform_input_sha256 is not None
            or args.expected_secret_id is not None
        ):
            parser.error("--check-ready does not accept mint arguments")
        check_manifest_ready(args.manifest)
        return 0
    if args.approve_mint:
        parser.error("--approve-mint requires --run-locked")
    if args.secret_ocid is None:
        parser.error("secret_ocid is required")
    if args.expected_secret_id is not None:
        parser.error("--expected-secret-id requires --validate-transaction")
    if args.terraform_input is not None:
        if (args.expected_owner_sha256 is None) != (args.expected_terraform_input_sha256 is None):
            parser.error("expected both manifest and Terraform input preimage hashes")
        expected_preimages = None
        if args.expected_owner_sha256 is not None:
            if not _SHA256.fullmatch(args.expected_owner_sha256):
                parser.error("invalid expected manifest preimage hash")
            expected_input_hash = args.expected_terraform_input_sha256
            if expected_input_hash != "missing" and not _SHA256.fullmatch(expected_input_hash or ""):
                parser.error("invalid expected Terraform input preimage hash")
            _, owner_path, _, _ = _manifest_gpu_owner(args.manifest)
            expected_preimages = {
                owner_path: args.expected_owner_sha256,
                args.terraform_input: None if expected_input_hash == "missing" else expected_input_hash,
            }
        persist_mint_result(args.manifest, args.terraform_input, args.secret_ocid, expected_preimages)
    else:
        if args.expected_owner_sha256 is not None or args.expected_terraform_input_sha256 is not None:
            parser.error("preimage hashes require --terraform-input")
        set_gpu_key_ocid(args.manifest, args.secret_ocid)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as exc:
        raise SystemExit(str(exc)) from None
