#!/usr/bin/env python3
"""Persist a minted GPU Vault secret OCID into its manifest refs."""

from __future__ import annotations

import argparse
import fcntl
import os
import re
import stat
import subprocess
import tempfile
import tomllib
from pathlib import Path


_SECRET_OCID = re.compile(r"^ocid1\.vaultsecret\.oc[0-9]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9._-]+$")
_TABLE_HEADER = re.compile(r"(?m)^\[\[[^\]]+\]\][ \t]*$")
_VAR_HEADER = re.compile(r"(?m)^\[\[var\]\][ \t]*$")
_SECRET_LINE = re.compile(r"(?m)^secret\s*=\s*\{[^\n]*\}$")
_TERRAFORM_INPUT_LINE = re.compile(
    r'^# Generated by scripts/deploy/gpu-key-mint\.sh; identifier only\.\n'
    r'gpu_api_key_secret_ocid = "(?P<ocid>ocid1\.vaultsecret\.oc[0-9]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9._-]+)"\n$'
)


def _replace_env_ref(secret_line: str, env: str, value: str) -> str:
    pattern = re.compile(rf"(?<![A-Za-z0-9_])({re.escape(env)}\s*=\s*)\"[^\"]*\"")
    updated, count = pattern.subn(rf'\g<1>"{value}"', secret_line)
    if count != 1:
        raise ValueError(f"GPU key manifest must contain exactly one {env} secret ref")
    return updated


def validate_manifest_ready(document: dict[str, object]) -> None:
    """Require the derived four-secret prod map before any GPU key mutation."""
    maps = [row for row in document.get("var", []) if row.get("name") == "RECOGNITION_VAULT_SECRET_MAP"]
    if len(maps) != 1:
        raise ValueError("GPU mint requires one RECOGNITION_VAULT_SECRET_MAP var")
    map_var = maps[0]
    if (
        map_var.get("class") != "config"
        or map_var.get("derive_vault_map") is not True
        or "svc-vm" not in map_var.get("targets", [])
    ):
        raise ValueError("GPU mint requires the svc-vm derived Vault secret map")

    required_names = ("PGPASSWORD", "POSTGRES_DSN", "POSTGRES_SYNC_DSN", "RECOGNITION_ADMIN_TOKEN")
    for name in required_names:
        refs = [row for row in document.get("var", []) if row.get("name") == name]
        if len(refs) != 1 or "svc-vm" not in refs[0].get("targets", []):
            raise ValueError(f"GPU mint requires a svc-vm {name} Vault ref")
        secret_refs = refs[0].get("secret")
        if not isinstance(secret_refs, dict):
            raise ValueError(f"GPU mint requires a prod Vault ref for {name}")
        reference = secret_refs.get("prod", "")
        scheme, separator, ocid = reference.partition(":")
        if scheme != "vault" or not separator or not _SECRET_OCID.fullmatch(ocid):
            raise ValueError(f"GPU mint requires a real prod vault ref for {name}")

    variable = _unique_gpu_key_var(document)
    if variable.get("class") != "secret" or "svc-vm" not in variable.get("targets", []):
        raise ValueError("GPU key manifest var must remain a svc-vm secret")
    refs = variable.get("secret")
    if not isinstance(refs, dict) or not {"dev", "staging", "prod"} <= refs.keys():
        raise ValueError("GPU key manifest must define dev, staging, and prod refs")


def _unique_gpu_key_var(document: dict[str, object]) -> dict[str, object]:
    variables = [
        row for row in document.get("var", [])
        if row.get("name") == "ACX_GPU_ENDPOINT_API_KEY"
    ]
    if len(variables) != 1:
        raise ValueError("GPU key manifest must contain exactly one ACX_GPU_ENDPOINT_API_KEY var")
    return variables[0]


def update_manifest_text(text: str, secret_ocid: str) -> str:
    """Return updated TOML, changing only the GPU key's dev/prod references."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    try:
        document = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError("GPU key manifest is not valid TOML") from exc
    validate_manifest_ready(document)

    return _update_gpu_key_text(text, secret_ocid)


def _update_gpu_key_text(text: str, secret_ocid: str) -> str:
    try:
        document = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError("GPU key manifest is not valid TOML") from exc

    variable = _unique_gpu_key_var(document)
    if variable.get("class") != "secret" or "svc-vm" not in variable.get("targets", []):
        raise ValueError("GPU key manifest var must remain a svc-vm secret")

    refs = variable.get("secret")
    if not isinstance(refs, dict) or not {"dev", "staging", "prod"} <= refs.keys():
        raise ValueError("GPU key manifest must define dev, staging, and prod refs")
    expected_refs = {"dev": f"oci:{secret_ocid}", "prod": f"vault:{secret_ocid}"}
    for env, expected in expected_refs.items():
        if refs[env] not in {"host:", expected}:
            raise ValueError(f"refusing to replace existing {env} GPU key ref")

    matches = list(_VAR_HEADER.finditer(text))
    blocks = []
    for match in matches:
        end = _TABLE_HEADER.search(text, match.end())
        block_end = end.start() if end is not None else len(text)
        block = text[match.start():block_end]
        try:
            parsed = tomllib.loads(block)
        except tomllib.TOMLDecodeError:
            continue
        row = parsed.get("var", [{}])[0]
        if row.get("name") == "ACX_GPU_ENDPOINT_API_KEY":
            blocks.append((match.start(), block_end, block))
    if len(blocks) != 1:
        raise ValueError("could not isolate GPU key manifest var")

    start, end, block = blocks[0]
    secret_lines = list(_SECRET_LINE.finditer(block))
    if len(secret_lines) != 1:
        raise ValueError("GPU key manifest var must contain one inline secret map")
    secret_line = secret_lines[0].group(0)
    for env, expected in expected_refs.items():
        scheme, _, existing_ocid = refs[env].partition(":")
        if scheme == "host":
            secret_line = _replace_env_ref(secret_line, env, expected)
        elif existing_ocid != secret_ocid:
            raise ValueError(f"refusing to replace existing {env} GPU key OCID")
    updated_block = block[:secret_lines[0].start()] + secret_line + block[secret_lines[0].end():]
    return text[:start] + updated_block + text[end:]


def _manifest_fragment_paths(path: Path) -> list[Path]:
    if path.is_dir():
        directory = path
        requested_fragment = None
    else:
        try:
            source_stat = path.lstat()
        except OSError as exc:
            raise ValueError("cannot read GPU key manifest") from exc
        if not stat.S_ISREG(source_stat.st_mode):
            raise ValueError("GPU key manifest must be a regular file or fragment directory")
        directory = path.parent
        requested_fragment = path

    try:
        fragments = sorted(
            fragment
            for fragment in directory.glob("*.toml")
            if fragment.name != "targets.toml"
        )
    except OSError as exc:
        raise ValueError("cannot list GPU key manifest fragments") from exc
    if not fragments or (requested_fragment is not None and requested_fragment not in fragments):
        raise ValueError("cannot read GPU key manifest")
    return fragments


def _load_manifest_fragments(
    path: Path,
) -> tuple[dict[str, object], dict[Path, tuple[str, dict[str, object]]]]:
    all_variables: list[dict[str, object]] = []
    fragments: dict[Path, tuple[str, dict[str, object]]] = {}
    for fragment_path in _manifest_fragment_paths(path):
        try:
            text = fragment_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ValueError("cannot read GPU key manifest") from exc
        try:
            fragment = tomllib.loads(text)
        except tomllib.TOMLDecodeError as exc:
            raise ValueError("GPU key manifest is not valid TOML") from exc
        fragment_variables = fragment.get("var", [])
        if not isinstance(fragment_variables, list) or any(
            not isinstance(row, dict) for row in fragment_variables
        ):
            raise ValueError("GPU key manifest var entries must be tables")
        all_variables.extend(fragment_variables)
        fragments[fragment_path] = (text, fragment)
    return {"var": all_variables}, fragments


def check_manifest_ready(path: Path) -> None:
    document, _ = _load_manifest_fragments(path)
    validate_manifest_ready(document)


def _durable_replace(path: Path, updated_text: str, mode: int) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f"{path.name}.envman-tmp-",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as stream:
            descriptor = -1
            stream.write(updated_text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
        directory_fd = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass


def _fsync_directory(directory: Path) -> None:
    directory_fd = os.open(directory, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def _stage_bytes(path: Path, content: bytes, mode: int) -> Path:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f"{path.name}.envman-tmp-",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "wb") as stream:
            descriptor = -1
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        temporary_path.unlink(missing_ok=True)
        raise
    return temporary_path


def _publish_atomic_updates(updates: list[tuple[Path, bytes, int]]) -> None:
    """Prepare all files, publish them, and restore preimages after any late error."""
    plans: list[dict[str, object]] = []
    try:
        for path, content, mode in updates:
            try:
                source_stat = path.lstat()
            except FileNotFoundError:
                existed = False
                old_content = None
                old_mode = mode
            except OSError as exc:
                raise ValueError("cannot inspect GPU key persistence destination") from exc
            else:
                if not stat.S_ISREG(source_stat.st_mode):
                    raise ValueError("GPU key persistence destination must be a regular file")
                try:
                    old_content = path.read_bytes()
                except OSError as exc:
                    raise ValueError("cannot read GPU key persistence destination") from exc
                existed = True
                old_mode = stat.S_IMODE(source_stat.st_mode)
            if existed and old_content == content and old_mode == mode:
                continue
            staged = _stage_bytes(path, content, mode)
            try:
                restore = _stage_bytes(path, old_content, old_mode) if existed else None
            except BaseException:
                staged.unlink(missing_ok=True)
                raise
            plans.append(
                {
                    "path": path,
                    "staged": staged,
                    "restore": restore,
                    "existed": existed,
                }
            )
    except OSError as exc:
        for plan in plans:
            for key in ("staged", "restore"):
                temporary = plan[key]
                if isinstance(temporary, Path):
                    temporary.unlink(missing_ok=True)
        raise ValueError("cannot prepare GPU key persistence destinations") from exc
    except BaseException:
        for plan in plans:
            for key in ("staged", "restore"):
                temporary = plan[key]
                if isinstance(temporary, Path):
                    temporary.unlink(missing_ok=True)
        raise

    attempted: list[dict[str, object]] = []
    try:
        for plan in plans:
            path = plan["path"]
            staged = plan["staged"]
            assert isinstance(path, Path) and isinstance(staged, Path)
            attempted.append(plan)
            os.replace(staged, path)
            plan["staged"] = None
            _fsync_directory(path.parent)
    except BaseException as exc:
        rollback_failed = False
        for plan in reversed(attempted):
            path = plan["path"]
            restore = plan["restore"]
            existed = plan["existed"]
            assert isinstance(path, Path) and isinstance(existed, bool)
            try:
                if existed:
                    assert isinstance(restore, Path)
                    os.replace(restore, path)
                    plan["restore"] = None
                else:
                    path.unlink(missing_ok=True)
                _fsync_directory(path.parent)
            except OSError:
                rollback_failed = True
        if rollback_failed:
            raise ValueError("GPU key persistence failed and rollback was incomplete") from exc
        if isinstance(exc, OSError):
            raise ValueError("GPU key persistence failed; local updates rolled back") from exc
        raise
    finally:
        for plan in plans:
            for key in ("staged", "restore"):
                temporary = plan[key]
                if isinstance(temporary, Path):
                    temporary.unlink(missing_ok=True)


def _test_writable_destination(path: Path) -> None:
    if not path.parent.is_dir():
        raise ValueError("GPU key persistence destination parent must be a directory")
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        pass
    except OSError as exc:
        raise ValueError("cannot inspect GPU key persistence destination") from exc
    else:
        if not stat.S_ISREG(source_stat.st_mode):
            raise ValueError("GPU key persistence destination must be a regular file")
    descriptor = -1
    temporary_path: Path | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.gpu-key-preflight-",
            dir=path.parent,
        )
        temporary_path = Path(temporary_name)
        os.fsync(descriptor)
    except OSError as exc:
        raise ValueError("GPU key persistence destination is not writable") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary_path is not None:
            try:
                temporary_path.unlink()
            except OSError as exc:
                raise ValueError("cannot clean GPU key persistence preflight file") from exc


def _current_gpu_key_ocid(document: dict[str, object]) -> str | None:
    refs = _unique_gpu_key_var(document).get("secret")
    if not isinstance(refs, dict):
        raise ValueError("GPU key manifest must define secret refs")
    dev = refs.get("dev", "")
    prod = refs.get("prod", "")
    if dev == "host:" and prod == "host:":
        return None
    dev_scheme, dev_separator, dev_ocid = dev.partition(":")
    prod_scheme, prod_separator, prod_ocid = prod.partition(":")
    if (
        dev_scheme != "oci"
        or prod_scheme != "vault"
        or not dev_separator
        or not prod_separator
        or dev_ocid != prod_ocid
        or not _SECRET_OCID.fullmatch(dev_ocid)
    ):
        raise ValueError("GPU key manifest dev/prod refs are inconsistent")
    return dev_ocid


def _terraform_input_text(secret_ocid: str) -> str:
    return (
        "# Generated by scripts/deploy/gpu-key-mint.sh; identifier only.\n"
        f'gpu_api_key_secret_ocid = "{secret_ocid}"\n'
    )


def _existing_terraform_input_ocid(path: Path) -> str | None:
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ValueError("cannot inspect Terraform GPU key input") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("Terraform GPU key input must be a regular file")
    try:
        existing_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError("cannot read Terraform GPU key input") from exc
    match = _TERRAFORM_INPUT_LINE.fullmatch(existing_text)
    if match is None:
        raise ValueError("refusing unknown or stale Terraform GPU key input")
    return match.group("ocid")


def _manifest_gpu_owner(
    path: Path,
) -> tuple[dict[str, object], Path, str, dict[Path, tuple[str, dict[str, object]]]]:
    document, fragments = _load_manifest_fragments(path)
    validate_manifest_ready(document)
    owners = [
        (fragment_path, text)
        for fragment_path, (text, fragment) in fragments.items()
        if any(row.get("name") == "ACX_GPU_ENDPOINT_API_KEY" for row in fragment.get("var", []))
    ]
    if len(owners) != 1:
        raise ValueError("GPU key manifest must contain exactly one ACX_GPU_ENDPOINT_API_KEY var")
    owner_path, owner_text = owners[0]
    return document, owner_path, owner_text, fragments


def _preflight_mint_transaction(manifest_path: Path, terraform_input_path: Path) -> None:
    document, owner_path, _, _ = _manifest_gpu_owner(manifest_path)
    if owner_path.resolve() == terraform_input_path.resolve():
        raise ValueError("GPU manifest and Terraform input destinations must differ")
    current_ocid = _current_gpu_key_ocid(document)
    artifact_ocid = _existing_terraform_input_ocid(terraform_input_path)
    if artifact_ocid is not None and artifact_ocid != current_ocid:
        raise ValueError("refusing conflicting or stale Terraform GPU key input")
    _test_writable_destination(owner_path)
    _test_writable_destination(terraform_input_path)


def persist_mint_result(manifest_path: Path, terraform_input_path: Path, secret_ocid: str) -> None:
    """Persist manifest and Terraform identifiers as one rollback-capable local transaction."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    document, owner_path, owner_text, _ = _manifest_gpu_owner(manifest_path)
    if owner_path.resolve() == terraform_input_path.resolve():
        raise ValueError("GPU manifest and Terraform input destinations must differ")
    current_ocid = _current_gpu_key_ocid(document)
    artifact_ocid = _existing_terraform_input_ocid(terraform_input_path)
    if artifact_ocid is not None and artifact_ocid != current_ocid:
        raise ValueError("refusing conflicting or stale Terraform GPU key input")

    updated_manifest = _update_gpu_key_text(owner_text, secret_ocid)
    updated_input = _terraform_input_text(secret_ocid)
    manifest_stat = owner_path.lstat()
    terraform_mode = 0o600
    try:
        terraform_stat = terraform_input_path.lstat()
    except FileNotFoundError:
        pass
    else:
        if not stat.S_ISREG(terraform_stat.st_mode):
            raise ValueError("Terraform GPU key input must be a regular file")
    _publish_atomic_updates(
        [
            (owner_path, updated_manifest.encode("utf-8"), stat.S_IMODE(manifest_stat.st_mode)),
            (terraform_input_path, updated_input.encode("utf-8"), terraform_mode),
        ]
    )


def persist_manifest(path: Path, updated_text: str) -> None:
    """Durably atomically replace the regular manifest file."""
    try:
        source_stat = path.lstat()
    except OSError as exc:
        raise ValueError("cannot inspect GPU key manifest") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("GPU key manifest must be a regular file")
    _durable_replace(path, updated_text, stat.S_IMODE(source_stat.st_mode))


def write_terraform_input(path: Path, secret_ocid: str) -> None:
    """Create a durable Terraform input file containing only the secret OCID."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    updated_text = _terraform_input_text(secret_ocid)
    try:
        source_stat = path.lstat()
    except FileNotFoundError:
        _durable_replace(path, updated_text, 0o600)
        return
    except OSError as exc:
        raise ValueError("cannot inspect Terraform GPU key input") from exc
    if not stat.S_ISREG(source_stat.st_mode):
        raise ValueError("Terraform GPU key input must be a regular file")
    try:
        existing_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError("cannot read Terraform GPU key input") from exc
    if existing_text == updated_text and stat.S_IMODE(source_stat.st_mode) == 0o600:
        return
    if existing_text != updated_text:
        raise ValueError("refusing to replace existing Terraform GPU key input")
    _durable_replace(path, updated_text, 0o600)


def set_gpu_key_ocid(path: Path, secret_ocid: str) -> None:
    """Update the manifest with the real OCID returned by the Vault writer."""
    if not _SECRET_OCID.fullmatch(secret_ocid):
        raise ValueError("refusing invalid Vault secret OCID")
    _, owner_path, original, _ = _manifest_gpu_owner(path)
    updated = _update_gpu_key_text(original, secret_ocid)
    if updated != original:
        persist_manifest(owner_path, updated)


def _run_locked_transaction(
    manifest_path: Path,
    terraform_input_path: Path,
    ssh_target: str,
    rotate: bool,
) -> int:
    if not ssh_target:
        raise ValueError("--run-locked requires an SSH target")
    lock_path = Path(f"/tmp/acx-gpu-key-mint-{os.getuid()}.lock")
    descriptor = -1
    try:
        descriptor = os.open(
            lock_path,
            os.O_CREAT | os.O_RDWR | getattr(os, "O_NOFOLLOW", 0),
            0o600,
        )
        lock_stat = os.fstat(descriptor)
        if (
            not stat.S_ISREG(lock_stat.st_mode)
            or lock_stat.st_uid != os.getuid()
            or lock_stat.st_nlink != 1
        ):
            raise ValueError("GPU key transaction lock must be a private regular file")
        os.fchmod(descriptor, 0o600)
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        _preflight_mint_transaction(manifest_path, terraform_input_path)
        command = [
            "bash",
            str(Path(__file__).with_name("gpu-key-mint.sh")),
            "--approve-mint",
            "--ssh-target",
            ssh_target,
            "--manifest",
            str(manifest_path),
            "--terraform-input",
            str(terraform_input_path),
        ]
        if rotate:
            command.append("--rotate")
        environment = os.environ.copy()
        environment["GPU_KEY_MINT_TRANSACTION_LOCKED"] = "1"
        return subprocess.run(command, check=False, env=environment).returncode
    except OSError as exc:
        raise ValueError("cannot lock or run GPU key mint transaction") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)


def default_manifest_path() -> Path:
    return Path(__file__).resolve().parents[2] / "config/env/manifest.d/10-service-shared.toml"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("secret_ocid", nargs="?")
    parser.add_argument("--manifest", type=Path, default=default_manifest_path())
    parser.add_argument("--terraform-input", type=Path)
    parser.add_argument("--check-ready", action="store_true")
    parser.add_argument("--run-locked", action="store_true")
    parser.add_argument("--ssh-target")
    parser.add_argument("--rotate", action="store_true")
    args = parser.parse_args()
    if args.run_locked:
        if args.secret_ocid is not None or args.check_ready or args.terraform_input is None:
            parser.error("--run-locked requires --terraform-input and does not accept other modes")
        return _run_locked_transaction(args.manifest, args.terraform_input, args.ssh_target or "", args.rotate)
    if args.check_ready:
        if args.secret_ocid is not None or args.terraform_input is not None or args.ssh_target or args.rotate:
            parser.error("--check-ready does not accept mint arguments")
        check_manifest_ready(args.manifest)
        return 0
    if args.secret_ocid is None:
        parser.error("secret_ocid is required")
    if args.terraform_input is not None:
        persist_mint_result(args.manifest, args.terraform_input, args.secret_ocid)
    else:
        set_gpu_key_ocid(args.manifest, args.secret_ocid)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as exc:
        raise SystemExit(str(exc)) from None
