import asyncio
import logging
import random
from typing import NamedTuple

import numpy as np
import pytest
from sklearn.metrics import adjusted_rand_score, completeness_score, homogeneity_score

from db.models import IdentityCluster, MediaIdentity
from recognition.application.clustering.chinese_whispers import ChineseWhispersClustering
from recognition.application.clustering.clustering_settings import ClusteringSettings

logger = logging.getLogger(__name__)


class SyntheticData(NamedTuple):
    identities: list[MediaIdentity]
    true_labels: list[int]
    num_people: int
    samples_per_person: int


def generate_synthetic_data(num_people=20, samples_per_person=10, noise_level=0.1) -> SyntheticData:
    """
    Generate synthetic face embeddings.
    Each person has a 'center' in 128-d space.
    Samples are generated by adding gaussian noise to the center.
    """
    np.random.seed(42)
    dim = 128
    identities = []
    true_labels = []

    for person_id in range(num_people):
        # Generate a random center on the unit hypersphere
        center = np.random.randn(dim)
        center /= np.linalg.norm(center)

        for _ in range(samples_per_person):
            # Add noise
            noise = np.random.randn(dim) * noise_level
            embedding = center + noise
            # Normalize
            embedding /= np.linalg.norm(embedding)

            identity = MediaIdentity(
                id=random.randint(10000, 99999),  # Mock ID
                media_id=random.randint(1000, 9999),
                embedding=embedding.tolist(),
                confidence=0.99,
            )
            identities.append(identity)
            true_labels.append(person_id)

    return SyntheticData(identities, true_labels, num_people, samples_per_person)


async def mock_create_cluster(members):
    # Mock cluster creation
    cluster = IdentityCluster(id=random.randint(1, 1000))
    return cluster, None


@pytest.mark.asyncio
async def test_cw_clustering_accuracy():
    """
    Benchmark Chinese Whispers clustering accuracy on synthetic data.
    """
    # 1. Easy dataset (low noise)
    data_easy = generate_synthetic_data(num_people=10, samples_per_person=10, noise_level=0.05)
    settings = ClusteringSettings(cw_threshold=0.75, cw_iterations=20)
    cw = ChineseWhispersClustering(settings)

    identity_to_cluster_map = {}

    async def capture_create_cluster(members):
        cluster_id = random.randint(1, 10000)
        c = IdentityCluster(id=cluster_id)
        for m in members:
            identity_to_cluster_map[m] = cluster_id
        return c, None

    await cw.cluster(data_easy.identities, create_cluster=capture_create_cluster)

    pred_labels = []
    for identity in data_easy.identities:
        pred_labels.append(identity_to_cluster_map.get(identity, -1))

    ari = adjusted_rand_score(data_easy.true_labels, pred_labels)
    hom = homogeneity_score(data_easy.true_labels, pred_labels)
    comp = completeness_score(data_easy.true_labels, pred_labels)

    print(f"\nCW Accuracy (Easy): ARI={ari:.4f}, Homogeneity={hom:.4f}, Completeness={comp:.4f}")

    # 2. Medium/Hard dataset (realistic noise)
    # Noise 0.05 was Easy (ARI~1.0). Noise 0.12 was Impossible (ARI=0.0).
    # Try 0.08 for a challenging but possible dataset.
    data_hard = generate_synthetic_data(num_people=10, samples_per_person=10, noise_level=0.08)

    # Run CW on harder data
    settings_cw = ClusteringSettings(cw_threshold=0.65, cw_iterations=20)
    cw_hard = ChineseWhispersClustering(settings_cw)

    identity_to_cluster_map.clear()
    await cw_hard.cluster(data_hard.identities, create_cluster=capture_create_cluster)
    pred_labels_cw = [identity_to_cluster_map.get(i, -1) for i in data_hard.identities]
    ari_cw = adjusted_rand_score(data_hard.true_labels, pred_labels_cw)
    print(f"\nCW Accuracy (Medium, noise=0.08): ARI={ari_cw:.4f}")

    # 3. PCA + Whitening
    from sklearn.decomposition import PCA

    # Fit PCA on the data (simulating learning from a larger corpus)
    # We use all data here for simplicity, but in prod it would be a pre-computed transform
    embeddings = np.array([i.embedding for i in data_hard.identities])

    # Keep 95% variance or specific components (e.g. 64 out of 128)
    pca = PCA(n_components=0.95, whiten=True)
    embeddings_pca = pca.fit_transform(embeddings)

    # Re-normalize after whitening (critical for cosine similarity)
    from sklearn.preprocessing import normalize

    embeddings_pca = normalize(embeddings_pca)

    # Create new identities with transformed embeddings
    identities_pca = []
    for idx, identity in enumerate(data_hard.identities):
        new_identity = MediaIdentity(
            id=identity.id,
            media_id=identity.media_id,
            embedding=embeddings_pca[idx].tolist(),
            confidence=identity.confidence,
        )
        identities_pca.append(new_identity)

    identity_to_cluster_map.clear()
    await cw_hard.cluster(identities_pca, create_cluster=capture_create_cluster)
    pred_labels_pca = [identity_to_cluster_map.get(i, -1) for i in identities_pca]
    ari_pca = adjusted_rand_score(data_hard.true_labels, pred_labels_pca)
    print(f"CW Accuracy (PCA+Whitening): ARI={ari_pca:.4f} (Components: {pca.n_components_})")
