/**
 * Pure renderer for the E15-28 public-demo walkthrough smoke-log fragment.
 *
 * The Playwright evidence spec (`tests/e2e/evidence/demo-walkthrough.spec.ts`)
 * captures screenshots and assembles a {@link DemoWalkthroughManifest}, then
 * writes both the manifest JSON and the markdown produced here into the
 * task-scoped artifact dir. Keeping the rendering pure (no fs, no clock) lets
 * `make demo-walkthrough-proof`'s emitted fragment be unit-tested without a
 * browser — see `demo-smoke-log.test.ts`. The headings mirror
 * `docs/tasks/15.0/E15-28-demo-smoke-log.md` so an operator can paste the
 * fragment straight into the smoke log.
 */

export const DEMO_WALKTHROUGH_FRAGMENT_FILENAME = 'demo-walkthrough-smoke-log-fragment.md';

export interface DemoWalkthroughManifest {
  task_ref: string;
  /** ISO-8601 capture timestamp, stamped by the spec at run time. */
  captured_at: string;
  /** Public WordPress origin under test (e.g. https://demo.altcontext.com). */
  base_url: string;
  /** Backend recognition base URL the demo paired against. */
  recognition_url: string;
  /** Deploy commit SHA the proof ran against, when known. */
  deploy_commit_sha: string | null;
  settings: {
    constant_provenance_visible: boolean;
    /**
     * Whether constant-provenance gated the verdict this run. The demo requires it
     * (non-derived identity); LocalWP runs legitimately lack constants and opt out
     * via ACX_E2E_REQUIRE_CONSTANT_PROVENANCE=0, so a missing provenance does not
     * force verdict=fail there.
     */
    constant_provenance_required: boolean;
    probe_outcome: string | null;
  };
  scan: {
    triggered: boolean;
    processed_samples: number[];
    monotonic: boolean;
    had_failures: boolean;
  };
  sovereignty: {
    degraded_banner_captured: boolean;
    local_read_ok: boolean;
    recovery_captured: boolean;
  };
  /** Screenshot filename -> whether it was captured this run. */
  captures: Record<string, boolean>;
  verdict: 'pass' | 'fail';
}

const yesNo = (value: boolean): string => (value ? 'yes' : 'no');

const capturedArtifactNames = (captures: Record<string, boolean>): string[] =>
  Object.entries(captures)
    .filter(([, captured]) => captured)
    .map(([name]) => name)
    .sort((a, b) => a.localeCompare(b));

const monotonicLine = (scan: DemoWalkthroughManifest['scan']): string => {
  if (!scan.monotonic) {
    return 'Monotonic processed-count: no';
  }

  const samples = scan.processed_samples.join(', ');
  return samples.length > 0
    ? `Monotonic processed-count: yes (samples: ${samples})`
    : 'Monotonic processed-count: yes';
};

/**
 * Render the markdown smoke-log fragment for one demo-walkthrough proof run.
 * Pure: identical input always yields identical output.
 */
export const renderDemoSmokeLogFragment = (manifest: DemoWalkthroughManifest): string => {
  const artifacts = capturedArtifactNames(manifest.captures);
  const artifactLines =
    artifacts.length > 0 ? artifacts.map((name) => `- ${name}`).join('\n') : '- (none captured)';

  return `<!-- generated by demo-walkthrough.spec.ts — do not edit; regenerate with \`make demo-walkthrough-proof\` -->
# E15-28 demo walkthrough proof fragment

## Run Metadata

- Run date: ${manifest.captured_at}
- Task ref: ${manifest.task_ref}
- Public WP origin: ${manifest.base_url}
- Backend base URL: ${manifest.recognition_url}
- Deploy commit SHA: ${manifest.deploy_commit_sha ?? '(unset)'}

## Settings + Pairing Proof

- Constant-provenance fields read-only: ${yesNo(manifest.settings.constant_provenance_visible)}
- Constant-provenance required for verdict: ${yesNo(manifest.settings.constant_provenance_required)}
- Test Connection outcome: ${manifest.settings.probe_outcome ?? '(not run)'}

## Live Round-Trip Summary

- Scan triggered: ${yesNo(manifest.scan.triggered)}
- ${monotonicLine(manifest.scan)}
- Scan failures: ${manifest.scan.had_failures ? 'yes' : 'none'}

## Sovereign Boundary Evidence (E15-26)

- Degraded banner captured: ${yesNo(manifest.sovereignty.degraded_banner_captured)}
- Local read still works: ${yesNo(manifest.sovereignty.local_read_ok)}
- Recovery after restart captured: ${yesNo(manifest.sovereignty.recovery_captured)}

## Captured Artifacts

${artifactLines}

## Outcome

- Public demo walkthrough verdict: ${manifest.verdict}
`;
};
