import { describe, expect, it } from 'vitest';

import {
  DEMO_WALKTHROUGH_FRAGMENT_FILENAME,
  renderDemoSmokeLogFragment,
  type DemoWalkthroughManifest,
} from './demo-smoke-log';

const passingManifest = (): DemoWalkthroughManifest => ({
  task_ref: 'E15-28',
  captured_at: '2026-06-12T15:00:00.000Z',
  base_url: 'https://demo.altcontext.com',
  recognition_url: 'https://staging.api.altcontext.com',
  deploy_commit_sha: '2b87aa0db8a6ae7e1acf47cba6d77e15e79778fb',
  settings: { constant_provenance_visible: true, probe_outcome: 'connected' },
  scan: { triggered: true, processed_samples: [1, 3, 5], monotonic: true, had_failures: false },
  sovereignty: { degraded_banner_captured: true, local_read_ok: true, recovery_captured: true },
  captures: {
    'demo-settings-provenance.png': true,
    'demo-degraded-banner.png': true,
    'demo-unavailable-surface.png': false,
  },
  verdict: 'pass',
});

describe('renderDemoSmokeLogFragment', () => {
  it('exposes a stable fragment filename for the proof pipeline', () => {
    expect(DEMO_WALKTHROUGH_FRAGMENT_FILENAME).toBe('demo-walkthrough-smoke-log-fragment.md');
  });

  it('renders a generated-by banner that names the regenerating target', () => {
    const fragment = renderDemoSmokeLogFragment(passingManifest());

    expect(fragment).toContain('<!-- generated by');
    expect(fragment).toContain('make demo-walkthrough-proof');
  });

  it('fills run metadata from the manifest', () => {
    const fragment = renderDemoSmokeLogFragment(passingManifest());

    expect(fragment).toContain('Task ref: E15-28');
    expect(fragment).toContain('Public WP origin: https://demo.altcontext.com');
    expect(fragment).toContain('Backend base URL: https://staging.api.altcontext.com');
    expect(fragment).toContain('Run date: 2026-06-12T15:00:00.000Z');
    expect(fragment).toContain('Deploy commit SHA: 2b87aa0db8a6ae7e1acf47cba6d77e15e79778fb');
  });

  it('renders settings, scan, and sovereign sections with yes/no values', () => {
    const fragment = renderDemoSmokeLogFragment(passingManifest());

    expect(fragment).toContain('Constant-provenance fields read-only: yes');
    expect(fragment).toContain('Test Connection outcome: connected');
    expect(fragment).toContain('Monotonic processed-count: yes (samples: 1, 3, 5)');
    expect(fragment).toContain('Scan failures: none');
    expect(fragment).toContain('Degraded banner captured: yes');
    expect(fragment).toContain('Local read still works: yes');
    expect(fragment).toContain('Recovery after restart captured: yes');
  });

  it('lists only captured artifacts, sorted, and renders the verdict', () => {
    const fragment = renderDemoSmokeLogFragment(passingManifest());

    expect(fragment).toContain('- demo-degraded-banner.png');
    expect(fragment).toContain('- demo-settings-provenance.png');
    expect(fragment).not.toContain('demo-unavailable-surface.png');
    // sorted: degraded before settings
    expect(fragment.indexOf('demo-degraded-banner.png')).toBeLessThan(
      fragment.indexOf('demo-settings-provenance.png'),
    );
    expect(fragment).toContain('Public demo walkthrough verdict: pass');
  });

  it('degrades gracefully on a failed run with no captures and a missing probe', () => {
    const failing: DemoWalkthroughManifest = {
      ...passingManifest(),
      deploy_commit_sha: null,
      settings: { constant_provenance_visible: false, probe_outcome: null },
      scan: { triggered: false, processed_samples: [], monotonic: false, had_failures: true },
      sovereignty: { degraded_banner_captured: false, local_read_ok: false, recovery_captured: false },
      captures: { 'demo-settings-provenance.png': false },
      verdict: 'fail',
    };

    const fragment = renderDemoSmokeLogFragment(failing);

    expect(fragment).toContain('Deploy commit SHA: (unset)');
    expect(fragment).toContain('Constant-provenance fields read-only: no');
    expect(fragment).toContain('Test Connection outcome: (not run)');
    expect(fragment).toContain('Monotonic processed-count: no');
    expect(fragment).toContain('Scan failures: yes');
    expect(fragment).toContain('Degraded banner captured: no');
    expect(fragment).toContain('(none captured)');
    expect(fragment).toContain('Public demo walkthrough verdict: fail');
  });
});
