services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: prototype_description_db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - ./db/docker-init:/docker-entrypoint-initdb.d
      - prototype_description_pgdata:/var/lib/postgresql/data
    networks:
      - prototype_description_network

volumes:
  prototype_description_pgdata:
    name: prototype_description_pgdata

networks:
  prototype_description_network:
    name: prototype_description_network
    driver: bridge
