import React from 'react';

export interface GuidedPrototypeEntranceProps {
  onBegin: () => void;
}

export const GuidedPrototypeEntrance = ({ onBegin }: GuidedPrototypeEntranceProps): React.JSX.Element => (
  <section className="acx-guided-entrance" aria-labelledby="acx-guided-entrance-title">
    <div className="acx-guided-entrance__brand" aria-label="AltContext">
      <span className="acx-guided-entrance__mark" aria-hidden="true">
        AC
      </span>
      <span>AltContext</span>
    </div>
    <p className="acx-guided-entrance__eyebrow">Guided WordPress prototype</p>
    <h1 id="acx-guided-entrance-title">AltContext — guided WordPress prototype</h1>
    <p className="acx-guided-entrance__intro">
      Open one saved example and follow the evidence from image context to a reviewed description. You decide what gets
      applied to the practice copy.
    </p>

    <div className="acx-guided-entrance__status">
      <strong>Current build</strong>
      <span>Saved example is available. Live description generation is unavailable in this build.</span>
    </div>

    <button type="button" className="acx-button acx-button--primary" onClick={onBegin}>
      Open a saved example
    </button>

    <p className="acx-guided-entrance__boundary">
      <strong>Implementation status:</strong> Illustrative scenario—not generated by the current service. Practice
      changes stay in this tab and reset on refresh. Live generation and guest access remain under development.{' '}
      <a
        className="acx-button acx-button--secondary acx-guided-entrance__case-study"
        href="https://darce.xyz/projects/altcontext/"
        target="_blank"
        rel="noreferrer"
      >
        Read the AltContext case study
      </a>
      .
    </p>
  </section>
);

GuidedPrototypeEntrance.displayName = 'GuidedPrototypeEntrance';
