#!/usr/bin/env python3
"""Consumer-side MCP package pin-parity guard.

Single source of truth for the workstate MCP runtime pins is the root
``Makefile`` (``MCP_HANDOFF_PACKAGE`` / ``MCP_ORCHESTRATOR_PACKAGE``). Every
other *current-pin* reference in this repo (harness configs, CI, operational
docs, doc-tests) must agree with it. This catches the manual fan-out drift that
left ``.github/copilot-instructions.md`` two minor versions stale.

Ownership note (coordinated with E17-15 / ADR-010): the live harness configs
(``.mcp.json`` / ``.vscode/mcp.json`` / ``.codex/config.toml``) are the pin
source of truth; emitted plugin manifests *preserve* these pins, and the plugin
generator + ``config/agent-workflows/mcp_servers.yaml`` manifest live in
``agentic-protocol-monorepo`` (out of bounds here). This guard is the consumer
"manifest check" that E17-15's verification calls for. The overlay
``mcp_servers.yaml`` is reported as an ADVISORY (not a hard failure) when it
drifts, because the bump belongs upstream.

Classification:
  - ERROR    : a strict pin (``pkg@X.Y.Z`` / ``pkg==X.Y.Z``) or a git-tag pin
               (``tag = "mcp-workstate-<pkg>-vX.Y.Z"``) in an editable,
               non-frozen file disagrees with the Makefile canonical.
  - ADVISORY : drift in an overlay symlink (e.g. mcp_servers.yaml), a range
               form (``>=a,<b``), a git+ssh tag scheme (different from PyPI), or
               a git-tag pin inside a regenerated lockfile (``uv.lock``).
  - OK       : matches canonical, or lives in a frozen as-of record.

Exit code 0 = no errors; 1 = at least one ERROR; 2 = guard misconfiguration.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

PACKAGES = ("mcp-workstate-handoff", "mcp-workstate-orchestrator")

# Frozen as-of records: ADRs, specs, and task plans legitimately pin the pin
# value that was current when they were written. Never fail on these.
FROZEN_PREFIXES = ("docs/adrs/", "docs/specs/", "docs/tasks/")

# Generated / vendored / overlay clone roots: not scanned at all.
SKIP_PREFIXES = (
    ".workstate/remote/",
    "node_modules/",
    "dist/",
    ".task-state/",
)
SKIP_EXACT = {"DASHBOARD.txt", "CURRENT_TASK.json", "scripts/check_mcp_pins.py"}

STRICT_RE = re.compile(
    r"\b(mcp-workstate-(?:handoff|orchestrator))(?:@|==)(\d+\.\d+\.\d+)\b"
)
RANGE_RE = re.compile(r"\b(mcp-workstate-(?:handoff|orchestrator))\s*(>=|<=|~=|>|<)")
# Terminator alternation includes end-of-string so a git+ssh pin that is the last
# token on a line (no trailing quote/space/backslash) is still matched.
GITSSH_RE = re.compile(
    r"git\+ssh\S*?(mcp-workstate-(?:handoff|orchestrator))\.git@(v?\S+?)([\"'\s\\]|$)"
)
# Git-tag pin form used by the codex-subagent-bridge:
#   pyproject.toml -> tag = "mcp-workstate-handoff-v0.12.3"
#   uv.lock        -> ...&tag=mcp-workstate-orchestrator-v0.6.0[#sha]
# The version is embedded in the tag string; capture it and compare to canonical.
TAG_RE = re.compile(r"(mcp-workstate-(?:handoff|orchestrator))-v(\d+\.\d+\.\d+)")
# Lockfiles are regenerated by the resolver; tag drift there is advisory, not an
# error (the authoritative source is the pyproject [tool.uv.sources] declaration).
LOCKFILE_SUFFIXES = (".lock",)


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return Path(out)


def parse_canonical(makefile: Path) -> dict[str, str]:
    """Extract canonical pins from Makefile MCP_*_PACKAGE assignments."""
    text = makefile.read_text(encoding="utf-8")
    pins: dict[str, str] = {}
    for m in re.finditer(
        r"MCP_\w+_PACKAGE\s*\??=\s*(mcp-workstate-(?:handoff|orchestrator))==(\d+\.\d+\.\d+)",
        text,
    ):
        pins[m.group(1)] = m.group(2)
    return pins


def tracked_files(root: Path) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return [p for p in out if p]


def is_overlay_symlink(root: Path, rel: str) -> bool:
    """True iff ``rel`` is a symlink whose target is rooted under the overlay
    clone (``<root>/.workstate/remote/``).

    Resolves the link target against the known overlay prefix instead of a loose
    substring test, so a symlink that merely *contains* "workstate/remote"
    elsewhere in its path (or an unrelated relative link) is not mis-classified
    as an overlay and cannot silently downgrade a genuine ERROR to an ADVISORY.
    A broken overlay symlink (target not materialised, e.g. in a linked
    worktree) still classifies as overlay so the advisory path fires.
    """
    p = root / rel
    if not p.is_symlink():
        return False
    overlay_prefix = Path(os.path.realpath(root / ".workstate" / "remote"))
    try:
        target = os.readlink(p)
    except OSError:
        return False
    # Resolve real directory components of the (possibly relative, possibly
    # absolute, possibly broken) target via realpath, which resolves the
    # existing leading path and leaves any non-existent tail intact. This keeps
    # the comparison symlink-safe (e.g. /tmp -> /private/tmp on macOS) and
    # worktree-independent without requiring the target to exist.
    candidate = (
        target if os.path.isabs(target) else os.path.join(os.path.dirname(p), target)
    )
    resolved = Path(os.path.realpath(candidate))
    try:
        resolved.relative_to(overlay_prefix)
    except ValueError:
        return False
    return True


def main() -> int:
    root = repo_root()
    canonical = parse_canonical(root / "Makefile")
    if set(canonical) != set(PACKAGES):
        print(
            f"check-mcp-pins: could not parse canonical pins from Makefile (got {canonical})",
            file=sys.stderr,
        )
        return 2

    banner = "check-mcp-pins: canonical (Makefile) = " + ", ".join(
        f"{k}=={v}" for k, v in sorted(canonical.items())
    )

    errors: list[str] = []
    advisories: list[str] = []

    for rel in tracked_files(root):
        if rel in SKIP_EXACT or any(rel.startswith(p) for p in SKIP_PREFIXES):
            continue
        path = root / rel
        overlay = is_overlay_symlink(root, rel)
        try:
            if path.is_dir():
                continue
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        except FileNotFoundError:
            # A broken overlay symlink (target not materialised, e.g. in a linked
            # worktree where the overlay clone is absent) raises here. The
            # overlay content is untracked (.workstate/remote/ is gitignored) so
            # there is no blob to read; emit an explicit advisory instead of
            # swallowing it, so the overlay-advisory path is not silently dead in
            # worktrees. The root worktree resolves the symlink and scans content.
            if overlay:
                advisories.append(
                    f"  [overlay] {rel}: overlay symlink not materialised in this worktree — "
                    "pin parity unverifiable here; run check-mcp-pins from the root worktree"
                )
            continue
        except IsADirectoryError:
            continue

        frozen = any(rel.startswith(p) for p in FROZEN_PREFIXES)
        is_lockfile = path.name.endswith(LOCKFILE_SUFFIXES)

        for lineno, line in enumerate(text.splitlines(), 1):
            for pkg, ver in STRICT_RE.findall(line):
                if ver == canonical[pkg]:
                    continue
                loc = f"{rel}:{lineno}"
                if overlay:
                    advisories.append(
                        f"  [overlay] {loc}: {pkg}=={ver} (canonical {canonical[pkg]}) — bump upstream in workstate-system / agentic-protocol-monorepo"
                    )
                elif frozen:
                    pass  # as-of record, allowed
                else:
                    errors.append(
                        f"  {loc}: {pkg}=={ver} != canonical {canonical[pkg]}"
                    )
            for pkg, op in RANGE_RE.findall(line):
                if not frozen:
                    advisories.append(
                        f"  [range] {rel}:{lineno}: {pkg}{op}... — prefer exact canonical pin {canonical[pkg]}"
                    )
            for pkg, tag, _term in GITSSH_RE.findall(line):
                advisories.append(
                    f"  [git+ssh] {rel}:{lineno}: {pkg}.git@{tag} — private-repo tag scheme, distinct from PyPI {canonical[pkg]}; unverifiable from this checkout"
                )
            for pkg, ver in TAG_RE.findall(line):
                if ver == canonical[pkg]:
                    continue
                loc = f"{rel}:{lineno}"
                if overlay:
                    advisories.append(
                        f"  [overlay] {loc}: {pkg}-v{ver} (canonical {canonical[pkg]}) — bump upstream in workstate-system / agentic-protocol-monorepo"
                    )
                elif frozen or is_lockfile:
                    # Lockfiles are regenerated from the pyproject sources; flag,
                    # but do not fail the build on lockfile-only tag drift.
                    advisories.append(
                        f"  [git-tag] {loc}: {pkg}-v{ver} != canonical {canonical[pkg]} — regenerate lockfile after the pyproject source bump"
                    )
                else:
                    errors.append(
                        f"  {loc}: {pkg}-v{ver} (git tag) != canonical {canonical[pkg]}"
                    )

    # Emit everything to a single stream order: banner, then advisories, then
    # errors. On the error path the whole block goes to stderr so CI logs stay
    # coherent (the canonical banner can no longer print after the error list);
    # on the success path the same block goes to stdout.
    out = sys.stderr if errors else sys.stdout
    print(banner, file=out)

    if advisories:
        print(
            "\ncheck-mcp-pins: ADVISORIES (not failures — upstream/out-of-bounds or non-pin forms):",
            file=out,
        )
        for a in sorted(set(advisories)):
            print(a, file=out)

    if errors:
        print(
            "\ncheck-mcp-pins: ERROR — pins disagree with Makefile canonical:",
            file=sys.stderr,
        )
        for e in sorted(set(errors)):
            print(e, file=sys.stderr)
        print(
            "\nFix: align the offending pin(s) with the Makefile MCP_*_PACKAGE values,",
            file=sys.stderr,
        )
        print(
            "or move the reference into a frozen record (docs/adrs|specs|tasks/).",
            file=sys.stderr,
        )
        return 1

    print("\ncheck-mcp-pins: OK — all editable current-pin references match canonical.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
