#!/usr/bin/env python3
"""Generate host-specific workflow adapters from the canonical manifest."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

GENERATOR_TAG = "<!-- GENERATED by scripts/generate_agent_workflows.py; do not edit by hand. -->\n"
CLAUDE_HEADER = "# /{command_id}\n\n"
PROMPT_HEADER = "# /{command_id}\n\n"
CODEX_ROUTER_HEADER = "# Portable Command Router\n\n"
CODEX_ROUTER_BEGIN = "<!-- BEGIN GENERATED: codex-command-router -->"
CODEX_ROUTER_END = "<!-- END GENERATED: codex-command-router -->"
CODEX_ROUTER_CONSUMERS = (
    Path("docs/agentic/instructions.md"),
    Path("CLAUDE.md"),
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _default_manifest_path() -> Path:
    return _repo_root() / "config" / "agent-workflows" / "portable_commands.json"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=_default_manifest_path())
    parser.add_argument("--claude-out", type=Path)
    parser.add_argument("--prompts-out", type=Path)
    parser.add_argument("--codex-router-out", type=Path)
    parser.add_argument(
        "--check-codex-router-blocks",
        action="store_true",
        help="Fail if the marker-delimited Codex router blocks drift from the manifest-rendered content.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if generated outputs differ from committed files.")
    return parser.parse_args()


def _load_manifest(path: Path) -> dict:
    try:
        payload = json.loads(path.read_text())
    except FileNotFoundError as exc:
        raise SystemExit(f"Manifest not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(payload, dict):
        raise SystemExit(f"{path} must contain a JSON object.")

    version = payload.get("version")
    if version != 1:
        raise SystemExit(f"{path} must declare version=1; found {version!r}.")

    commands = payload.get("commands")
    if not isinstance(commands, list) or not commands:
        raise SystemExit(f"{path} must declare a non-empty commands list.")

    seen_ids: set[str] = set()
    for index, command in enumerate(commands):
        _validate_command(command, index)
        command_id = command["command_id"]
        if command_id in seen_ids:
            raise SystemExit(f"Duplicate command_id {command_id!r} in {path}.")
        seen_ids.add(command_id)
    return payload


def _validate_command(command: object, index: int) -> None:
    if not isinstance(command, dict):
        raise SystemExit(f"commands[{index}] must be an object.")

    required_string_fields = ("command_id", "skill", "makefile_target", "description", "execution_context")
    for field in required_string_fields:
        value = command.get(field)
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"commands[{index}].{field} must be a non-empty string.")

    command_id = command["command_id"]
    if any(ch not in "abcdefghijklmnopqrstuvwxyz0123456789-" for ch in command_id):
        raise SystemExit(f"commands[{index}].command_id must be lowercase kebab-case; found {command_id!r}.")

    loop = command.get("loop")
    if not isinstance(loop, list) or not loop or not all(isinstance(item, str) and item.strip() for item in loop):
        raise SystemExit(f"commands[{index}].loop must be a non-empty list of strings.")

    secondary_targets = command.get("secondary_targets", [])
    if secondary_targets != [] and (
        not isinstance(secondary_targets, list)
        or not all(isinstance(item, str) and item.strip() for item in secondary_targets)
    ):
        raise SystemExit(f"commands[{index}].secondary_targets must be a list of strings when present.")

    argument_schema = command.get("argument_schema")
    if not isinstance(argument_schema, list):
        raise SystemExit(f"commands[{index}].argument_schema must be a list.")
    for arg_index, arg in enumerate(argument_schema):
        if not isinstance(arg, dict):
            raise SystemExit(f"commands[{index}].argument_schema[{arg_index}] must be an object.")
        name = arg.get("name")
        description = arg.get("description")
        required = arg.get("required")
        if not isinstance(name, str) or not name.strip():
            raise SystemExit(f"commands[{index}].argument_schema[{arg_index}].name must be a non-empty string.")
        if not isinstance(description, str) or not description.strip():
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].description must be a non-empty string."
            )
        if not isinstance(required, bool):
            raise SystemExit(f"commands[{index}].argument_schema[{arg_index}].required must be boolean.")


def _render_arguments(command: dict) -> list[str]:
    args = command.get("argument_schema", [])
    if not args:
        return ["Arguments: none."]
    lines = ["Arguments:"]
    for arg in args:
        status = "required" if arg["required"] else "optional"
        lines.append(f"- `{arg['name']}` ({status}): {arg['description']}")
    return lines


def _render_targets(command: dict) -> list[str]:
    lines = [f"Makefile entry point: `{command['makefile_target']}`"]
    secondary = command.get("secondary_targets", [])
    if secondary:
        lines.append("Secondary entry points:")
        lines.extend(f"- `{target}`" for target in secondary)
    return lines


def _render_claude(command: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        CLAUDE_HEADER.format(command_id=command["command_id"]).rstrip(),
        "",
        f"Active skill: `{command['skill']}`",
        "",
        *_render_targets(command),
        "",
        *_render_arguments(command),
        "",
        f"Execution context: {command['execution_context']}",
        "",
        "Loop:",
        *(f"- {item}" for item in command["loop"]),
        "",
    ]
    return "\n".join(lines)


def _render_prompt(command: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        PROMPT_HEADER.format(command_id=command["command_id"]).rstrip(),
        "",
        f"Load the `{command['skill']}` skill for this workflow.",
        "",
        f"Description: {command['description']}",
        "",
        *_render_targets(command),
        "",
        *_render_arguments(command),
        "",
        f"Execution context: {command['execution_context']}",
        "",
        "Loop:",
        *(f"- {item}" for item in command["loop"]),
        "",
    ]
    return "\n".join(lines)


def _render_codex_router_body(manifest: dict) -> list[str]:
    commands: list[dict] = manifest["commands"]
    managed_ids = ", ".join(f"`/{command['command_id']}`" for command in commands)
    return [
        (
            "If a user prompt begins with a registered `/command_id`, treat that prefix as a portable workflow "
            "command routed through `config/agent-workflows/portable_commands.json`."
        ),
        "",
        f"Current managed ids: {managed_ids}.",
        "",
        "Routing rules:",
        "- Strip the leading `/command_id` token before normal intent analysis.",
        "- Load the mapped skill from the manifest and use its `makefile_target` as the primary entry point when one exists.",
        "- Interpret the remainder of the user message using the manifest-defined argument names.",
        "- If generated adapters drift from the manifest, run `make generate-agent-workflows`; `make check-agent-workflows` verifies Claude, VS Code, and Codex outputs together.",
        "",
        "Command map:",
        *(
            f"- `/{command['command_id']}` -> skill `{command['skill']}` -> `{command['makefile_target']}`"
            for command in commands
        ),
    ]


def _render_codex_router(manifest: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        CODEX_ROUTER_HEADER.rstrip(),
        "",
        *_render_codex_router_body(manifest),
        "",
    ]
    return "\n".join(lines)


def _render_codex_router_embed(manifest: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        *_render_codex_router_body(manifest),
        "",
    ]
    return "\n".join(lines)


def _replace_marked_block(content: str, replacement: str) -> tuple[str, bool]:
    begin = content.find(CODEX_ROUTER_BEGIN)
    end = content.find(CODEX_ROUTER_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError("missing codex router markers")
    if content.find(CODEX_ROUTER_BEGIN, begin + 1) != -1 or content.find(CODEX_ROUTER_END, end + 1) != -1:
        raise ValueError("multiple codex router marker blocks")

    block_start = begin + len(CODEX_ROUTER_BEGIN)
    before = content[:block_start]
    current = content[block_start:end]
    after = content[end:]
    new_block = f"\n{replacement}\n"
    return before + new_block + after, current != new_block


def _sync_codex_router_consumers(manifest: dict, repo_root: Path, check: bool) -> list[str]:
    replacement = _render_codex_router_embed(manifest)
    failures: list[str] = []
    for relative_path in CODEX_ROUTER_CONSUMERS:
        absolute_path = repo_root / relative_path
        try:
            content = absolute_path.read_text()
        except FileNotFoundError:
            failures.append(f"missing codex router consumer: {absolute_path}")
            continue

        try:
            updated, changed = _replace_marked_block(content, replacement)
        except ValueError as exc:
            failures.append(f"{absolute_path}: {exc}")
            continue

        if check:
            if changed:
                failures.append(f"codex router drift detected: {absolute_path}")
            continue

        if changed:
            absolute_path.write_text(updated)
    return failures


def _expected_outputs(manifest: dict, claude_out: Path, prompts_out: Path, codex_router_out: Path) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for command in manifest["commands"]:
        command_id = command["command_id"]
        outputs[claude_out / f"{command_id}.md"] = _render_claude(command)
        outputs[prompts_out / f"{command_id}.prompt.md"] = _render_prompt(command)
    outputs[codex_router_out / "codex-command-router.md"] = _render_codex_router(manifest)
    return outputs


def _write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def _extra_generated_files(root: Path, expected_paths: set[Path]) -> list[Path]:
    if not root.exists():
        return []
    extras: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path in expected_paths:
            continue
        try:
            content = path.read_text()
        except OSError:
            continue
        if content.startswith(GENERATOR_TAG):
            extras.append(path)
    return sorted(extras)


def _check_outputs(outputs: dict[Path, str], claude_out: Path, prompts_out: Path, codex_router_out: Path) -> int:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            failures.append(f"missing generated file: {path}")
            continue
        actual = path.read_text()
        if actual != expected:
            failures.append(f"drift detected: {path}")

    expected_paths = set(outputs)
    extras = (
        _extra_generated_files(claude_out, expected_paths)
        + _extra_generated_files(prompts_out, expected_paths)
        + _extra_generated_files(codex_router_out, expected_paths)
    )
    for path in extras:
        failures.append(f"stale generated file not declared in manifest: {path}")

    if failures:
        print("Agent workflow adapters are out of sync with the manifest:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("✓ agent-workflows: generated adapters match the manifest.")
    return 0


def main() -> int:
    args = _parse_args()
    manifest = _load_manifest(args.manifest)
    repo_root = args.manifest.resolve().parents[2]
    claude_out = args.claude_out or (repo_root / ".claude" / "commands")
    prompts_out = args.prompts_out or (repo_root / ".github" / "prompts")
    codex_router_out = args.codex_router_out or (repo_root / "docs" / "agentic" / "generated")
    outputs = _expected_outputs(manifest, claude_out, prompts_out, codex_router_out)

    if args.check_codex_router_blocks:
        failures = _sync_codex_router_consumers(manifest, repo_root, check=True)
        if failures:
            print("Codex router consumer docs are out of sync with the manifest:", file=sys.stderr)
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
            return 1
        print("✓ codex-router: consumer docs match the manifest-rendered block.")
        return 0

    if args.check:
        return _check_outputs(outputs, claude_out, prompts_out, codex_router_out)

    _write_outputs(outputs)
    failures = _sync_codex_router_consumers(manifest, repo_root, check=False)
    if failures:
        raise SystemExit("\n".join(failures))
    print(f"✓ agent-workflows: wrote {len(outputs)} adapter files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
