import samplePhoto from '../assets/guided/altcontext-sample.jpeg';

export type GuidedCandidateStatus = 'ready' | 'edited' | 'rejected';
export type GuidedIdentityStatus = 'unconfirmed' | 'confirmed' | 'unidentified';

export type GuidedMatchStrength = 'strong' | 'weak';

export interface GuidedFaceBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** A face-recognition result saved from an earlier run. The demo never runs recognition live. */
export interface GuidedFaceMatch {
  faceCount: number;
  box: GuidedFaceBox;
  matchedPersonName: string;
  similarPhotoCount: number;
  strength: GuidedMatchStrength;
  source: 'saved-example';
}

export interface GuidedIdentity {
  status: GuidedIdentityStatus;
  name?: string;
  source: 'sample-record' | 'none';
}

export interface GuidedHistoryEvent {
  kind: 'identity-confirmed' | 'identity-unidentified' | 'edit-saved' | 'rejected' | 'applied' | 'application-undone';
  text?: string;
  previousAppliedText?: string;
}

export type GuidedScenarioOrigin = 'illustrative' | 'saved-build';

export const GUIDED_SCENARIO_ORIGIN_LABELS: Record<GuidedScenarioOrigin, string> = {
  illustrative: 'Illustrative example — not generated by the current service',
  'saved-build': 'Saved from a real build run',
};

export interface GuidedScenario {
  origin: GuidedScenarioOrigin;
  scenarioVersion: string;
  originalMedia: {
    src: string;
    altText: string;
  };
  sourceRecord: {
    name: string;
    credit: string;
    note: string;
  };
  pageContext: {
    title: string;
    summary: string;
  };
  visualFacts: string[];
  faceMatch: GuidedFaceMatch;
  genericDraft: string;
  namedDraft: string;
  unnamedDraft: string;
  identity: GuidedIdentity;
  candidate: {
    text: string;
    status: GuidedCandidateStatus;
  };
  appliedText: string;
  history: GuidedHistoryEvent[];
}

const GUIDED_SCENARIO_SEED: Omit<GuidedScenario, 'identity' | 'candidate' | 'appliedText' | 'history'> = {
  origin: 'illustrative',
  scenarioVersion: 'guided-portrait-v1',
  originalMedia: {
    src: samplePhoto,
    altText: 'Portrait of a person in a grey jacket.',
  },
  sourceRecord: {
    name: 'Keanu Reeves',
    credit: 'Governo do Estado de São Paulo',
    note: 'Sample record metadata is evidence for practice. It is not facial identification by the tour.',
  },
  pageContext: {
    title: 'Illustrative actor profile',
    summary: 'A portrait used in an actor profile where a confirmed name helps the description make sense.',
  },
  visualFacts: ['Portrait crop', 'Grey jacket', 'Plain background'],
  faceMatch: {
    faceCount: 1,
    box: { x: 370, y: 320, width: 660, height: 800 },
    matchedPersonName: 'Keanu Reeves',
    similarPhotoCount: 3,
    strength: 'strong',
    source: 'saved-example',
  },
  genericDraft: 'Portrait of a person in a grey jacket.',
  namedDraft: 'Keanu Reeves wears a grey jacket against a plain background.',
  unnamedDraft: 'Portrait of a person in a grey jacket.',
};

const cloneSeed = (): Omit<GuidedScenario, 'identity' | 'candidate' | 'appliedText' | 'history'> => ({
  ...GUIDED_SCENARIO_SEED,
  originalMedia: { ...GUIDED_SCENARIO_SEED.originalMedia },
  sourceRecord: { ...GUIDED_SCENARIO_SEED.sourceRecord },
  pageContext: { ...GUIDED_SCENARIO_SEED.pageContext },
  visualFacts: [...GUIDED_SCENARIO_SEED.visualFacts],
  faceMatch: { ...GUIDED_SCENARIO_SEED.faceMatch, box: { ...GUIDED_SCENARIO_SEED.faceMatch.box } },
});

const cloneScenario = (scenario: GuidedScenario): GuidedScenario => ({
  ...scenario,
  originalMedia: { ...scenario.originalMedia },
  sourceRecord: { ...scenario.sourceRecord },
  pageContext: { ...scenario.pageContext },
  visualFacts: [...scenario.visualFacts],
  faceMatch: { ...scenario.faceMatch, box: { ...scenario.faceMatch.box } },
  identity: { ...scenario.identity },
  candidate: { ...scenario.candidate },
  history: scenario.history.map((event) => ({ ...event })),
});

const withHistory = (scenario: GuidedScenario, event: GuidedHistoryEvent): GuidedScenario => ({
  ...cloneScenario(scenario),
  history: [...scenario.history.map((item) => ({ ...item })), event],
});

export const createGuidedScenario = (): GuidedScenario => ({
  ...cloneSeed(),
  identity: { status: 'unconfirmed', source: 'none' },
  candidate: { text: GUIDED_SCENARIO_SEED.genericDraft, status: 'ready' },
  appliedText: GUIDED_SCENARIO_SEED.originalMedia.altText,
  history: [],
});

export const resetGuidedScenario = (): GuidedScenario => createGuidedScenario();

const containsSampleIdentity = (text: string, name: string): boolean => {
  const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`\\b${escapedName}\\b`, 'i').test(text);
};

const assertCandidateIdentity = (scenario: GuidedScenario): void => {
  const sampleName = scenario.sourceRecord.name.trim();
  if (sampleName === '' || !containsSampleIdentity(scenario.candidate.text, sampleName)) {
    return;
  }

  if (
    scenario.identity.status !== 'confirmed' ||
    scenario.identity.source !== 'sample-record' ||
    scenario.identity.name?.trim().toLowerCase() !== sampleName.toLowerCase()
  ) {
    throw new Error('Cannot use the sample name until the identity is confirmed from the sample record.');
  }
};

const availableGuidedApplications = (history: GuidedHistoryEvent[]): GuidedHistoryEvent[] => {
  const availableApplications: GuidedHistoryEvent[] = [];
  for (const event of history) {
    if (event.kind === 'applied') {
      availableApplications.push(event);
    } else if (event.kind === 'application-undone') {
      availableApplications.pop();
    }
  }
  return availableApplications;
};

export const getLastGuidedApplication = (history: GuidedHistoryEvent[]): GuidedHistoryEvent | undefined =>
  availableGuidedApplications(history).at(-1);

export const confirmGuidedIdentity = (scenario: GuidedScenario): GuidedScenario =>
  withHistory(
    {
      ...cloneScenario(scenario),
      identity: { status: 'confirmed', name: scenario.sourceRecord.name, source: 'sample-record' },
      candidate: { text: scenario.namedDraft, status: 'ready' },
    },
    { kind: 'identity-confirmed' },
  );

export const leaveGuidedIdentityUnidentified = (scenario: GuidedScenario): GuidedScenario =>
  withHistory(
    {
      ...cloneScenario(scenario),
      identity: { status: 'unidentified', source: 'none' },
      candidate: { text: scenario.unnamedDraft, status: 'ready' },
    },
    { kind: 'identity-unidentified' },
  );

export const saveGuidedEdit = (scenario: GuidedScenario, text: string): GuidedScenario => {
  const trimmedText = text.trim();
  if (trimmedText === '') {
    throw new Error('A description cannot be empty.');
  }

  const editedScenario = {
    ...cloneScenario(scenario),
    candidate: { text: trimmedText, status: 'edited' as const },
  };
  assertCandidateIdentity(editedScenario);

  return withHistory(editedScenario, { kind: 'edit-saved', text: trimmedText });
};

export const rejectGuidedCandidate = (scenario: GuidedScenario): GuidedScenario =>
  withHistory(
    {
      ...cloneScenario(scenario),
      candidate: { ...scenario.candidate, status: 'rejected' },
    },
    { kind: 'rejected', text: scenario.candidate.text },
  );

export const applyGuidedCandidate = (scenario: GuidedScenario): GuidedScenario => {
  if (scenario.candidate.status === 'rejected') {
    throw new Error('Cannot apply a rejected description.');
  }

  assertCandidateIdentity(scenario);

  if (scenario.candidate.text === scenario.appliedText) {
    return cloneScenario(scenario);
  }

  return withHistory(
    { ...cloneScenario(scenario), appliedText: scenario.candidate.text },
    { kind: 'applied', text: scenario.candidate.text, previousAppliedText: scenario.appliedText },
  );
};

export const undoGuidedApplication = (scenario: GuidedScenario): GuidedScenario => {
  const lastApplication = getLastGuidedApplication(scenario.history);
  if (lastApplication?.previousAppliedText === undefined) {
    return cloneScenario(scenario);
  }

  return withHistory(
    { ...cloneScenario(scenario), appliedText: lastApplication.previousAppliedText },
    { kind: 'application-undone', text: lastApplication.previousAppliedText },
  );
};
