import guidedJustinTrudeauPhoto2024 from '../assets/guided/guided-justin-trudeau-2024.jpg';
import guidedJustinTrudeauPhoto from '../assets/guided/guided-justin-trudeau-2025.jpg';
import guidedJustinTrudeauPhoto2023 from '../assets/guided/guided-justin-trudeau-2023.jpg';
import guidedKatyPerryPhoto from '../assets/guided/guided-katy-perry-2026.jpg';
import guidedKatyPerryPhoto2019 from '../assets/guided/guided-katy-perry-2019.jpg';
import guidedKatyPerryPhoto2016 from '../assets/guided/guided-katy-perry-2016.jpg';
import guidedPressPhoto from '../assets/guided/guided-press-tribeca-2026.jpg';

import { guidedCopy, type GuidedCopyKey } from './copy';

export const GUIDED_STEP = {
  CONTEXT: 'context',
  NAMES: 'names',
  DRAFT: 'draft',
  APPLY: 'apply',
} as const;

export const GUIDED_NAME_CHOICE = {
  UNDECIDED: 'undecided',
  INCLUDE: 'include',
  OMIT: 'omit',
} as const;

export const GUIDED_DRAFT_ORIGIN = {
  NONE: 'none',
  RECORDED_SAMPLE: 'recorded_sample',
  VISITOR_EDIT: 'visitor_edit',
} as const;

export const GUIDED_DRAFT_STATUS = {
  BLOCKED: 'blocked',
  READY: 'ready',
  FIXTURE_MISSING: 'fixture_missing',
} as const;

export const GUIDED_OUTCOME = {
  NOT_FINISHED: 'not_finished',
  APPLIED: 'applied',
  KEPT: 'kept',
} as const;

export type GuidedStep = (typeof GUIDED_STEP)[keyof typeof GUIDED_STEP];
export type GuidedNameChoice = (typeof GUIDED_NAME_CHOICE)[keyof typeof GUIDED_NAME_CHOICE];
export type GuidedDraftOrigin = (typeof GUIDED_DRAFT_ORIGIN)[keyof typeof GUIDED_DRAFT_ORIGIN];
export type GuidedDraftStatus = (typeof GUIDED_DRAFT_STATUS)[keyof typeof GUIDED_DRAFT_STATUS];
export type GuidedOutcome = (typeof GUIDED_OUTCOME)[keyof typeof GUIDED_OUTCOME];
export type GuidedRestoreMode = 'full' | 'copy_only';
export type GuidedMatchStrength = 'strong' | 'weak';
export type GuidedPersonKey = 'katy-perry' | 'justin-trudeau';
export const GUIDED_PERSON_KEYS: readonly GuidedPersonKey[] = ['katy-perry', 'justin-trudeau'];
export type GuidedFacePosition = 'left' | 'right';
export type GuidedDraftKey = 'none' | 'katy-perry' | 'justin-trudeau' | 'both';
export type GuidedFaceSource = 'saved-run' | 'user-supplied';

export interface GuidedFaceBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface GuidedGalleryPhoto {
  src: string;
  altText: string;
  credit: string;
}

export interface GuidedLabeledPerson {
  key: GuidedPersonKey;
  name: string;
  clusterId: string;
  savedPhotoCount: number;
  galleryPhotos: GuidedGalleryPhoto[];
}

export interface GuidedFace {
  id: GuidedPersonKey;
  position: GuidedFacePosition;
  box: GuidedFaceBox;
  matchedPersonKey: GuidedPersonKey;
  /** Null when a fixture has a user-supplied label but no recognition result. */
  similarity: number | null;
  /** Null when no recognition confidence/strength was recorded for the fixture. */
  strength: GuidedMatchStrength | null;
  note?: string;
  source: GuidedFaceSource;
}

export interface GuidedProvenance {
  service: string;
  model: string;
  runDate: string;
  /** Null when the scenario has no recognition threshold to report. */
  threshold: number | null;
  note: string;
  alsoChecked: string;
}

export type GuidedScenarioOrigin = 'illustrative' | 'saved-build' | 'user-supplied';

export interface GuidedScenarioIdentitySource {
  kind: 'saved-run' | 'user-supplied';
  names: Record<GuidedFacePosition, string>;
  source: string;
  note: string;
}

export const GUIDED_SCENARIO_ORIGIN_LABELS: Record<GuidedScenarioOrigin, string> = {
  illustrative: 'Illustrative example — not generated by the current service',
  'saved-build': 'Saved from a real build run',
  'user-supplied': 'User-supplied fixture — labels are not independently verified',
};

export interface GuidedScenario {
  origin: GuidedScenarioOrigin;
  scenarioVersion: string;
  pressPhoto: {
    src: string;
    altText: string;
    credit: string;
    event: string;
    source?: string;
  };
  pageContext: {
    title: string;
    summary: string;
    runDate: string;
  };
  people: GuidedLabeledPerson[];
  faces: GuidedFace[];
  visualFacts: string[];
  samples: Record<GuidedDraftKey, string | null>;
  provenance: GuidedProvenance;
  /** Optional because the incumbent saved-build fixture predates this field. */
  identitySource?: GuidedScenarioIdentitySource;
}

export interface GuidedChoices {
  left: GuidedNameChoice;
  right: GuidedNameChoice;
}

export interface GuidedPendingChoiceChange {
  position: GuidedFacePosition;
  choice: GuidedNameChoice;
}

export interface GuidedDraftRevision {
  revisionId: string;
  text: string;
  origin: GuidedDraftOrigin;
  choices: GuidedChoices;
  draftVersion: number;
}

export interface GuidedApplicationRecord {
  previousAltText: string;
  appliedDraftVersion: number;
  sequence: number;
}

export interface GuidedActionHistoryEntry {
  event: string;
  sequence: number;
  scope: 'local';
  summary: string;
}

export interface GuidedNameCoverage {
  key: GuidedPersonKey;
  shown: number;
  total: number;
}

export interface GuidedDemoState {
  activeStep: GuidedStep;
  choices: GuidedChoices;
  draftText: string | null;
  draftOrigin: GuidedDraftOrigin;
  draftStatus: GuidedDraftStatus;
  draftVersion: number;
  previewedVersion: number | null;
  draftHistory: GuidedDraftRevision[];
  pendingChoiceChange: GuidedPendingChoiceChange | null;
  appliedAltText: string;
  applicationUndoStack: GuidedApplicationRecord[];
  outcome: GuidedOutcome;
  actionHistory: GuidedActionHistoryEntry[];
}

const INITIAL_APPLIED_ALT_TEXT = 'A man in a black suit and a woman in a white dress pose together, smiling, in front of a Tribeca Festival step-and-repeat backdrop.';

const GUIDED_SCENARIO_SEED: GuidedScenario = {
  origin: 'saved-build',
  scenarioVersion: 'guided-people-v4',
  pressPhoto: {
    src: guidedPressPhoto,
    altText: INITIAL_APPLIED_ALT_TEXT,
    credit: 'Colleen Sturtevant, CC BY-SA 4.0, resized',
    event: 'Tribeca Festival, New York, June 2026',
  },
  pageContext: {
    title: 'Tribeca Festival 2026: red carpet photos',
    summary: 'A photo gallery from the opening nights of the Tribeca Festival in New York, June 2026.',
    runDate: '2026-09-06',
  },
  people: [
    {
      key: 'katy-perry',
      name: 'Katy Perry',
      clusterId: '68adc97c-f81f-42c3-9e5c-061f16770361',
      savedPhotoCount: 5,
      galleryPhotos: [
        {
          src: guidedKatyPerryPhoto,
          altText: 'Katy Perry at a microphone, reading from a note, in front of a red curtain.',
          credit: 'Justin Higuchi, CC BY 4.0, resized',
        },
        {
          src: guidedKatyPerryPhoto2019,
          altText: 'Katy Perry smiling at the camera, blonde hair with a headband, red lips, checked shirt.',
          credit: 'Glenn Francis (Toglenn), CC BY-SA 4.0, resized',
        },
        {
          src: guidedKatyPerryPhoto2016,
          altText:
            'Katy Perry singing into a microphone, long dark hair, silver striped dress, blue and red lights behind her.',
          credit: 'Voice of America, public domain',
        },
      ],
    },
    {
      key: 'justin-trudeau',
      name: 'Justin Trudeau',
      clusterId: 'fd0d2b5d-108a-42b7-af25-f028e40d5778',
      savedPhotoCount: 3,
      galleryPhotos: [
        {
          src: guidedJustinTrudeauPhoto,
          altText: 'Justin Trudeau, close up, in a grey suit and green tie, with flags behind him.',
          credit: '© European Union, 2025, EU reuse licence, resized',
        },
        {
          src: guidedJustinTrudeauPhoto2023,
          altText: 'Justin Trudeau in a grey suit, blue shirt and patterned blue tie, looking slightly to the side.',
          credit: 'Lea-Kim Chateauneuf, CC BY-SA 4.0, resized',
        },
        {
          src: guidedJustinTrudeauPhoto2024,
          altText: 'Justin Trudeau speaking in a blue suit, white shirt and navy polka-dot tie.',
          credit: 'Jonathan Miranda / Presidencia de la República del Ecuador, public domain',
        },
      ],
    },
  ],
  faces: [
    {
      id: 'justin-trudeau',
      position: 'left',
      box: { x: 514, y: 77, width: 132, height: 189 },
      matchedPersonKey: 'justin-trudeau',
      similarity: 0.686,
      strength: 'strong',
      source: 'saved-run',
    },
    {
      id: 'katy-perry',
      position: 'right',
      box: { x: 707, y: 140, width: 121, height: 181 },
      matchedPersonKey: 'katy-perry',
      similarity: 0.742,
      strength: 'strong',
      note: 'Her face is turned a little to the side.',
      source: 'saved-run',
    },
  ],
  visualFacts: [
    'Two people stand side by side in front of a white wall of Tribeca Festival logos.',
    'The man on the left wears a black tuxedo with a white shirt.',
    'The woman on the right wears a white draped gown with her dark hair pinned up.',
    'Her hand rests on his chest.',
  ],
  samples: {
    "none": "A man and a woman pose together on a red carpet in front of a backdrop featuring the Tribeca Festival and 10 Lives Studios logos. The man wears a black tuxedo with a white shirt, and the woman is in a white sleeveless dress with a draped design, smiling as she places her hand on his chest.",
    "katy-perry": "Katy Perry and a man pose together on a red carpet in front of a backdrop for the Tribeca Festival. Perry, on the right, wears a white dress and smiles while placing her hand on the man's chest. The man, on the left, wears a black tuxedo and white shirt. The background features repeating logos for \"TRIBECA FESTIVAL\" and \"10 LIVES STUDIOS.\"",
    "justin-trudeau": "Justin Trudeau stands on a red carpet at the Tribeca Festival, posing with a woman in a white dress. He is wearing a black tuxedo with a white shirt, and she has her hand on his chest, showing a ring on her finger. The background is a white wall with repeating \"Tribeca Festival\" and \"10 Lives Studios\" logos.",
    "both": "Justin Trudeau and Katy Perry pose together on the red carpet at the Tribeca Festival, standing in front of a backdrop with the event's logo. Trudeau is wearing a black tuxedo with a white shirt, while Perry is in a white sleeveless dress with a draped design. Perry has her arm around Trudeau and is smiling, showing off a ring on her left hand.",
  },
  provenance: {
    service: 'AltContext recognition service (dev build)',
    model: 'InsightFace buffalo_l',
    runDate: '2026-09-06',
    threshold: 0.6,
    note: 'Saved from a real run. The demo does not run recognition live.',
    alsoChecked:
      'A Coachella press photo of the same two people matched both, even with a hand over her mouth. It is not bundled because of licensing.',
  },
};

const cloneScenario = (scenario: GuidedScenario): GuidedScenario => ({
  ...scenario,
  pressPhoto: { ...scenario.pressPhoto },
  pageContext: { ...scenario.pageContext },
  people: scenario.people.map((person) => ({
    ...person,
    galleryPhotos: person.galleryPhotos.map((photo) => ({ ...photo })),
  })),
  faces: scenario.faces.map((face) => ({ ...face, box: { ...face.box } })),
  visualFacts: [...scenario.visualFacts],
  samples: { ...scenario.samples },
  provenance: { ...scenario.provenance },
  ...(scenario.identitySource
    ? {
        identitySource: {
          ...scenario.identitySource,
          names: { ...scenario.identitySource.names },
        },
      }
    : {}),
});

const assertPresent: <T>(value: T | undefined, description: string) => asserts value is T = (value, description) => {
  if (value === undefined) {
    throw new Error(`Missing guided scenario ${description}.`);
  }
};

export const getGuidedPerson = (scenario: GuidedScenario, key: GuidedPersonKey): GuidedLabeledPerson => {
  const person = scenario.people.find((candidate) => candidate.key === key);
  assertPresent(person, `person: ${key}`);
  return person;
};

export const getGuidedFace = (scenario: GuidedScenario, faceId: GuidedPersonKey): GuidedFace => {
  const face = scenario.faces.find((candidate) => candidate.id === faceId);
  assertPresent(face, `face: ${faceId}`);
  return face;
};

export const createGuidedScenario = (): GuidedScenario => cloneScenario(GUIDED_SCENARIO_SEED);

const cloneChoices = (choices: GuidedChoices): GuidedChoices => ({
  left: choices.left,
  right: choices.right,
});

const cloneState = (state: GuidedDemoState): GuidedDemoState => ({
  ...state,
  choices: cloneChoices(state.choices),
  draftHistory: state.draftHistory.map((revision) => ({
    ...revision,
    choices: cloneChoices(revision.choices),
  })),
  pendingChoiceChange: state.pendingChoiceChange === null ? null : { ...state.pendingChoiceChange },
  applicationUndoStack: state.applicationUndoStack.map((record) => ({ ...record })),
  actionHistory: state.actionHistory.map((entry) => ({ ...entry })),
});

const nextSequence = (state: GuidedDemoState): number => {
  const last = state.actionHistory.at(-1);
  return (last?.sequence ?? 0) + 1;
};

const withLocalAction = (
  state: GuidedDemoState,
  event: string,
  summaryKey: GuidedCopyKey,
  values: Record<string, string | number> = {},
): GuidedDemoState => ({
  ...state,
  actionHistory: [
    ...state.actionHistory,
    {
      event,
      sequence: nextSequence(state),
      scope: 'local',
      summary: guidedCopy(summaryKey, values),
    },
  ],
});

const personNameForPosition = (scenario: GuidedScenario, position: GuidedFacePosition): string => {
  const face = scenario.faces.find((candidate) => candidate.position === position);
  assertPresent(face, `face at ${position}`);
  return getGuidedPerson(scenario, face.matchedPersonKey).name;
};

const choicesMatch = (left: GuidedChoices, right: GuidedChoices): boolean =>
  left.left === right.left && left.right === right.right;

export const namesDecided = (state: GuidedDemoState): boolean =>
  state.choices.left !== GUIDED_NAME_CHOICE.UNDECIDED && state.choices.right !== GUIDED_NAME_CHOICE.UNDECIDED;

export const canPreview = (state: GuidedDemoState): boolean =>
  namesDecided(state) &&
  state.draftStatus === GUIDED_DRAFT_STATUS.READY &&
  state.draftText !== null &&
  state.draftText.trim().length > 0;

export const canApply = (state: GuidedDemoState): boolean =>
  canPreview(state) &&
  state.previewedVersion === state.draftVersion &&
  state.draftText !== state.appliedAltText &&
  state.pendingChoiceChange === null;

export const canUndo = (state: GuidedDemoState): boolean => state.applicationUndoStack.length > 0;

export const canRestoreRevision = (state: GuidedDemoState, revisionId: string): boolean => {
  const revision = state.draftHistory.find((entry) => entry.revisionId === revisionId);
  if (revision === undefined) {
    return false;
  }
  return choicesMatch(revision.choices, state.choices);
};

export const guidedDraftKeyFor = (choices: GuidedChoices): GuidedDraftKey | null => {
  if (choices.left === GUIDED_NAME_CHOICE.UNDECIDED || choices.right === GUIDED_NAME_CHOICE.UNDECIDED) {
    return null;
  }
  const leftIncluded = choices.left === GUIDED_NAME_CHOICE.INCLUDE;
  const rightIncluded = choices.right === GUIDED_NAME_CHOICE.INCLUDE;
  if (leftIncluded && rightIncluded) {
    return 'both';
  }
  if (leftIncluded) {
    return 'justin-trudeau';
  }
  if (rightIncluded) {
    return 'katy-perry';
  }
  return 'none';
};

export const guidedSampleFor = (scenario: GuidedScenario, choices: GuidedChoices): string | null => {
  const key = guidedDraftKeyFor(choices);
  if (key === null) {
    return null;
  }
  return scenario.samples[key];
};

export const guidedNameCoverage = (scenario: GuidedScenario): GuidedNameCoverage[] =>
  scenario.people.map((person) => ({
    key: person.key,
    shown: person.galleryPhotos.length,
    total: person.savedPhotoCount,
  }));

export const guidedStepIndex = (step: GuidedStep): number => {
  switch (step) {
    case GUIDED_STEP.CONTEXT:
      return 0;
    case GUIDED_STEP.NAMES:
      return 1;
    case GUIDED_STEP.DRAFT:
      return 2;
    case GUIDED_STEP.APPLY:
      return 3;
    default: {
      const exhaustive: never = step;
      return exhaustive;
    }
  }
};

const resolveSample = (
  scenario: GuidedScenario,
  choices: GuidedChoices,
): Pick<GuidedDemoState, 'draftText' | 'draftOrigin' | 'draftStatus'> => {
  if (choices.left === GUIDED_NAME_CHOICE.UNDECIDED || choices.right === GUIDED_NAME_CHOICE.UNDECIDED) {
    return {
      draftText: null,
      draftOrigin: GUIDED_DRAFT_ORIGIN.NONE,
      draftStatus: GUIDED_DRAFT_STATUS.BLOCKED,
    };
  }
  const sample = guidedSampleFor(scenario, choices);
  if (sample === null) {
    return {
      draftText: null,
      draftOrigin: GUIDED_DRAFT_ORIGIN.NONE,
      draftStatus: GUIDED_DRAFT_STATUS.FIXTURE_MISSING,
    };
  }
  return {
    draftText: sample,
    draftOrigin: GUIDED_DRAFT_ORIGIN.RECORDED_SAMPLE,
    draftStatus: GUIDED_DRAFT_STATUS.READY,
  };
};

const archiveCurrentDraft = (state: GuidedDemoState): GuidedDraftRevision[] => {
  if (state.draftText === null) {
    return state.draftHistory;
  }
  return [
    ...state.draftHistory,
    {
      revisionId: `rev-${state.draftHistory.length + 1}`,
      text: state.draftText,
      origin: state.draftOrigin,
      choices: cloneChoices(state.choices),
      draftVersion: state.draftVersion,
    },
  ];
};

const archiveManualDraft = (state: GuidedDemoState): GuidedDraftRevision[] => {
  if (state.draftOrigin !== GUIDED_DRAFT_ORIGIN.VISITOR_EDIT) {
    return state.draftHistory;
  }
  return archiveCurrentDraft(state);
};

export const createGuidedDemoState = (): GuidedDemoState => ({
  activeStep: GUIDED_STEP.CONTEXT,
  choices: {
    left: GUIDED_NAME_CHOICE.UNDECIDED,
    right: GUIDED_NAME_CHOICE.UNDECIDED,
  },
  draftText: null,
  draftOrigin: GUIDED_DRAFT_ORIGIN.NONE,
  draftStatus: GUIDED_DRAFT_STATUS.BLOCKED,
  draftVersion: 0,
  previewedVersion: null,
  draftHistory: [],
  pendingChoiceChange: null,
  appliedAltText: INITIAL_APPLIED_ALT_TEXT,
  applicationUndoStack: [],
  outcome: GUIDED_OUTCOME.NOT_FINISHED,
  actionHistory: [],
});

export const selectGuidedStep = (state: GuidedDemoState, step: GuidedStep): GuidedDemoState => {
  if (state.activeStep === step) {
    return state;
  }
  const next = cloneState(state);
  next.activeStep = step;
  return next;
};

export const chooseGuidedName = (
  state: GuidedDemoState,
  scenario: GuidedScenario,
  position: GuidedFacePosition,
  choice: GuidedNameChoice,
): GuidedDemoState => {
  if (state.pendingChoiceChange !== null) {
    return state;
  }
  if (state.choices[position] === choice) {
    return state;
  }
  if (state.draftOrigin === GUIDED_DRAFT_ORIGIN.VISITOR_EDIT) {
    // Park the intended change only. Confirm applies it; cancel is a no-op for
    // outcome, copy, and history of a choice that has not happened yet (T07).
    const next = cloneState(state);
    next.pendingChoiceChange = { position, choice };
    return next;
  }

  const choices = cloneChoices(state.choices);
  choices[position] = choice;
  const resolved = resolveSample(scenario, choices);
  const namesAreDecided =
    choices.left !== GUIDED_NAME_CHOICE.UNDECIDED && choices.right !== GUIDED_NAME_CHOICE.UNDECIDED;
  const summaryKey: GuidedCopyKey =
    choice === GUIDED_NAME_CHOICE.OMIT
      ? 'names.omitted'
      : choice === GUIDED_NAME_CHOICE.INCLUDE
        ? 'names.included'
        : 'names.pending';
  const summaryValues: Record<string, string | number> =
    choice === GUIDED_NAME_CHOICE.INCLUDE ? { name: personNameForPosition(scenario, position) } : {};

  return withLocalAction(
    {
      ...cloneState(state),
      choices,
      ...resolved,
      draftVersion: namesAreDecided ? state.draftVersion + 1 : state.draftVersion,
      previewedVersion: namesAreDecided ? null : state.previewedVersion,
      outcome: GUIDED_OUTCOME.NOT_FINISHED,
    },
    'choose_name_option',
    summaryKey,
    summaryValues,
  );
};

export const confirmGuidedChoiceReplacement = (state: GuidedDemoState, scenario: GuidedScenario): GuidedDemoState => {
  if (state.pendingChoiceChange === null) {
    return state;
  }
  const pending = state.pendingChoiceChange;
  const choices = cloneChoices(state.choices);
  choices[pending.position] = pending.choice;
  const resolved = resolveSample(scenario, choices);
  return withLocalAction(
    {
      ...cloneState(state),
      choices,
      ...resolved,
      draftHistory: archiveCurrentDraft(state),
      pendingChoiceChange: null,
      draftVersion: state.draftVersion + 1,
      previewedVersion: null,
      outcome: GUIDED_OUTCOME.NOT_FINISHED,
    },
    'confirm_choice_replacement',
    'names.change_status',
  );
};

export const cancelGuidedChoiceReplacement = (state: GuidedDemoState): GuidedDemoState => {
  if (state.pendingChoiceChange === null) {
    return state;
  }
  return withLocalAction(
    {
      ...cloneState(state),
      pendingChoiceChange: null,
    },
    'cancel_choice_replacement',
    'names.change_cancel',
  );
};

export const editGuidedDraft = (state: GuidedDemoState, text: string): GuidedDemoState => {
  if (!namesDecided(state) || state.draftStatus !== GUIDED_DRAFT_STATUS.READY) {
    return state;
  }
  return withLocalAction(
    {
      ...cloneState(state),
      draftText: text,
      draftOrigin: GUIDED_DRAFT_ORIGIN.VISITOR_EDIT,
      draftVersion: state.draftVersion + 1,
      previewedVersion: null,
      outcome: GUIDED_OUTCOME.NOT_FINISHED,
    },
    'edit_draft',
    'draft.origin_edited',
  );
};

export const previewGuidedDraft = (state: GuidedDemoState): GuidedDemoState => {
  if (!canPreview(state)) {
    return state;
  }
  return withLocalAction(
    {
      ...cloneState(state),
      previewedVersion: state.draftVersion,
      activeStep: GUIDED_STEP.APPLY,
    },
    'preview_draft',
    'draft.next',
  );
};

export const keepGuidedCurrentAltText = (state: GuidedDemoState): GuidedDemoState => {
  // KEPT means "the demo copy is unchanged". After apply, the current alt is
  // the draft; restore the original so the outcome and the copy agree.
  const originalAlt = state.applicationUndoStack[0]?.previousAltText ?? state.appliedAltText;
  return withLocalAction(
    {
      ...cloneState(state),
      outcome: GUIDED_OUTCOME.KEPT,
      appliedAltText: originalAlt,
      applicationUndoStack: [],
    },
    'keep_current_alt_text',
    'outcome.kept',
  );
};

export const applyGuidedDraft = (state: GuidedDemoState): GuidedDemoState => {
  if (!canApply(state) || state.draftText === null) {
    return state;
  }
  const sequence = nextSequence(state);
  return {
    ...cloneState(state),
    appliedAltText: state.draftText,
    outcome: GUIDED_OUTCOME.APPLIED,
    applicationUndoStack: [
      ...state.applicationUndoStack,
      {
        previousAltText: state.appliedAltText,
        appliedDraftVersion: state.draftVersion,
        sequence,
      },
    ],
    actionHistory: [
      ...state.actionHistory,
      {
        event: 'apply_draft',
        sequence,
        scope: 'local',
        summary: guidedCopy('apply.success'),
      },
    ],
  };
};

export const undoGuidedApplication = (state: GuidedDemoState): GuidedDemoState => {
  if (!canUndo(state)) {
    return state;
  }
  const stack = state.applicationUndoStack.map((record) => ({ ...record }));
  const restored = stack.pop();
  if (restored === undefined) {
    return state;
  }
  return withLocalAction(
    {
      ...cloneState(state),
      appliedAltText: restored.previousAltText,
      applicationUndoStack: stack,
      outcome: stack.length === 0 ? GUIDED_OUTCOME.NOT_FINISHED : GUIDED_OUTCOME.APPLIED,
    },
    'undo_application',
    'apply.undone',
  );
};

export const restoreGuidedRevision = (
  state: GuidedDemoState,
  revisionId: string,
  mode: GuidedRestoreMode,
): GuidedDemoState => {
  const revision = state.draftHistory.find((entry) => entry.revisionId === revisionId);
  if (revision === undefined) {
    return state;
  }
  if (mode === 'full' && !canRestoreRevision(state, revisionId)) {
    return state;
  }
  const summaryKey = mode === 'copy_only' ? 'draft.copy_revision' : 'draft.restore_revision';
  return withLocalAction(
    {
      ...cloneState(state),
      draftHistory: archiveManualDraft(state),
      draftText: revision.text,
      draftOrigin: GUIDED_DRAFT_ORIGIN.VISITOR_EDIT,
      draftStatus: namesDecided(state) ? GUIDED_DRAFT_STATUS.READY : state.draftStatus,
      draftVersion: state.draftVersion + 1,
      previewedVersion: null,
      outcome: GUIDED_OUTCOME.NOT_FINISHED,
    },
    'restore_draft_revision',
    summaryKey,
  );
};

export const resetGuidedDemoState = (state: GuidedDemoState): GuidedDemoState => {
  void state;
  return createGuidedDemoState();
};

export const retryGuidedFixture = (state: GuidedDemoState, scenario: GuidedScenario): GuidedDemoState => {
  if (state.draftStatus !== GUIDED_DRAFT_STATUS.FIXTURE_MISSING) {
    return state;
  }
  const resolved = resolveSample(scenario, state.choices);
  if (resolved.draftStatus === GUIDED_DRAFT_STATUS.FIXTURE_MISSING) {
    return state;
  }
  return withLocalAction(
    {
      ...cloneState(state),
      ...resolved,
      draftVersion: state.draftVersion + 1,
      previewedVersion: null,
      outcome: GUIDED_OUTCOME.NOT_FINISHED,
    },
    'retry_fixture',
    'draft.fixture_retry',
  );
};
